### ISSUE TITLE
Appear to be missing tests for powershell local transport?

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1076]
The inventory integration tests only appear to test the bash shell, not a Windows shell, specifically PowerShell.

https://github.com/puppetlabs/bolt/blob/b162c76abddd5db4a890b99ab1f9990a5ff710fd/spec/integration/inventory_spec.rb#L287

Should these be added?

**Comment by glennsarti** [comment]
Related #1077

**Comment by glennsarti** [comment]
@nicklewis The tests for powershell based transport are still missing.  I assume that closing this issue it's a case of "Won't Do" ?

**Comment by nicklewis** [comment]
Yeah, my overall thought was that that test file could probably be deleted with little consequence. 
It's mostly testing that should either be testable in inventory unit tests or in the tests for individual transports.
