### ISSUE TITLE
Add facts 

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/bolt#1097]
I am trying to add facts to nodes. 
I have a bunch of Linux Mint nodes, I want to provision them via ```apply```

For example - with docker, 

```
$results = apply($nodes, _run_as => root) {
    notice($::osfamily)
    include 'docker'
}
```

Docker module does not support Linux Mint. So I want to add fact that these nodes are Ubuntu actually

How can I do this?

**Comment by lucywyman** [comment]
First, I highly recommend joining our [community slack](http://slack.puppet.com/) - we have a lot of great community members who can answer these questions in addition to Bolt engineers.

Second, setting the fact will not affect whether the docker module works or not. Even if it did, the `osfamily` fact is deprecated, and even if it wasn't deprecated the default value for Mint is `Debian` which is the same as Ubuntu (see https://github.com/puppetlabs/facter/blob/e4efbc3e8046a4a8d7d2863ba2c156af2accd211/lib/src/facts/linux/os_linux.cc#L57-L64)

What are you trying to do, what do you expect to happen, and what is actually happening?

**Comment by luckyraul** [comment]
Arguments to Resource[] are all empty/undefined (file: Boltdir/modules/docker/manifests/repos.pp, line: 49, column: 41)
https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/repos.pp#L49 - $docker::prerequired_package - is empty

**Comment by lucywyman** [comment]
Ah ok - I wonder if that module will accept a PR to add Mint to it? @davejrt or @florindragos Do you know what the right thing to do here is?

**Comment by lucywyman** [comment]
@luckyraul Does https://github.com/puppetlabs/puppetlabs-docker/pull/519 fix your issue? I'm not sure if that's the only place where OS name is relevant in that module.

**Comment by luckyraul** [comment]
Not completely 
```The repository 'https://download.docker.com/linux/linuxmint sylvia Release' does not have a Release file.```

**Comment by florindragos** [comment]
@lucywyman We could accept https://github.com/puppetlabs/puppetlabs-docker/pull/519 if it is the only thing needed to get the docker module working on linux mint. As long as it does not break the module supported operating systems, I don't see a problem.

**Comment by sheenaajay** [comment]
@luckyraul Thank you for the response.

**Comment by luckyraul** [comment]
also link https://github.com/puppetlabs/facter/pull/1845

**Comment by luckyraul** [comment]
link https://github.com/puppetlabs/puppetlabs-apt/pull/890

**Comment by nicklewis** [comment]
Is this still an issue?
