### ISSUE TITLE
Clear API for the `Target` Datatype

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1125]
## Problem

The Target object in the plan language has a few well defined methods which are primarily around reading information. The current format of `Target.new` is not compatible with target objects defined in the inventory and there is no good way to change connection information for a target during a plan or create targets programmatically. 

## Impact

If you use the experimental v2 inventory file and use `Target.new` in your plans you may need to update them to support the new `Target` attributes.

### Changes to the `Target` object

New attributes for a target to support the use of `Target.new` from plans in a way that accepts the same data as a target declaration in the inventory file.

- `uri` Any data in the uri cannot be overridden by other config
- `name` If no name is specified the uri will be used as the name
- `config` May set the transport and/or config options for transports.
- `vars`
- `facts`
- `features`

In addition a new `display_name` method will be added to target. If a name was specified the name will be the display name. If the name is inferred from the uri then the display_name will exclude a password if specified in the URI.

The options attribute will no longer be available. 

### Examples

To create a new node with a name and host add it to a group for it's connection info

```
$target = Target.new(uri => 'my_node.example.com')
$target.add_to_group('my_config')
```

To create a node with a different name and uri. 
```
# Set the host with the URI
$target = Target.new(name => 'my_node', uri => '123.456.789.101')
# Or explicitly set the host on the transport.
$target = Target.new(name => 'my_node', config => { ssh => { host => '123.456.789.101' } } } )
```

To create new targets from the results of a target-lookups task

```
$target_data = run_task('module::my_lookup', 'localhost').first['targets']
$targets = $target_data.map |$data| { Target.new($data) }
```

### How data is tracked and merged

Conceptually there is a singleton target object for each unique target name. That object is stateful and tracks the connection information and other known data about the target. When a user accesses the data on a target object they will get the same result regardless of how they access the object `get_targets`, `Target.new()`, a `Target` parameter etc. 

#### Target and Group data are separate

In order to allow consistent data behavior target and group data will be treated separately in inventory version 2. Target level data will be computed once when the inventory is loaded and updated with the various setter functions on the target. IE `$target.add_facts`, `$target.set_var`, `target.set_config` etc. When a getter function is called ie `$target.vars` or connection information is accessed ie `run_task` the Target data for the target will be merged with the group data(where target level takes precedence).

#### Merge strategy

- `config` - deep merge of hashes. This allows `ssh` information to come from multiple locations
- `facts` - deep merge of hashes. This allows structured data to be set in mutiple locations and works with the `add_facts` function.
- `features` - All features are concatenated into a single feature set.
- `vars` - Shallow merge. The entire vars hash is merged but objects inside vars are not merged.

### Notes

- It is expected that users will not normally call `Target.new` with a target name that matches an existing target. Calling `Target.new` will overwrite any preexisting target level configuration but not change the groups the target is in.

### `get_target($TargetSpec $spec)`

This function resolves a `TargetSpec` similarly to `get_targets` but only returns a single `Target` object. If the targetspec resolves to more than one `Target` the function will error. 

To create a new target from a URI you can use `get_target` instead of `target.new`
```
get_target('ssh://me:secret@example.com')
```

To get a single object to operate on
```
$targ = get_target('my_target')
$targ.add_facts({<some facts>})
```

### `set_config(Target $target, Variant[String, Array] key_or_key_path, Any $value)`

Set a value at the target level of config.

To change the transport for a target
```
$targ.set_config('transport', 'pcp')
```

To set a password for a target
```
$targ.set_config(['ssh', 'password'], 'secret')
```

To override all of the ssh info for a target
```
$target.set_config('ssh', { user => 'me', password => 'secret' })
$target.add_to_group('no_hostkey')
```

order of groups should not matter so this is equivalent:
```
$target.add_to_group('no_hostkey')
$target.set_config('ssh', { user => 'me', password => 'secret' })
```

## Release Plan

In order to avoid breaking changes the new `Target` datatype should only be used if bolt is run with a `version: 2` inventory file.  The behavior of the ruby `Target` object is less important.

**Comment by nmaludy** [comment]
I would love to see this feature. We have several, very hacky, ways of working around this problem currently. Implementing this feature would allow me to delete a lot of code!

+100
