### ISSUE TITLE
Missing CHANGELOG.md

### ISSUE THREAD

**Issue by dhoppe** [puppetlabs/bolt#1138]
Please maintain a CHANGELOG.md. Bolt was released today in version 1.28.0 and the website knows only about version 1.27.1

**Comment by nicklewis** [comment]
We had a bit of a process hitch getting the doc updates published for this release, sorry about that!

We've also been discussing improvements to how we track and where we publish release notes, so I definitely appreciate your feedback about a CHANGELOG.md.

**Comment by lucywyman** [comment]
Are changelog and release notes different?  No - we currently have this concept spread across 3 sources. We should add New Features, Bug fixes, and other user-facing changes to the `CHANGELOG.md` in the PR where the change happened. We should not add maint or docs changes to the changelog - the git history should act as a more thorough changelog.

Part of this work is removing release notes docs from `pre-docs`

The existing (New Features)[https://puppet.com/docs/bolt/latest/bolt_new_features.html], (Deprecations)[https://puppet.com/docs/bolt/latest/bolt_deprecations_and_removals.html] and (Resolved Issues)[https://puppet.com/docs/bolt/latest/bolt_resolved_issues.html] content should be added to the new Changelog. The format of the changelog can be as such, but whoever picks this up should play with formatting to see what feels right (and research how other projects do it):
```
## Version 1.2.0
- (GH-1111)[link-to-github-issue] Title of Change **Type of change (ie. Feature, Bug, Breaking Change)**
Description of change

### (GH-1112)[link-to-gh-issue] Title of Change **Type of change**
Description of change
```
