### ISSUE TITLE
`--sudo-password` Warning message prints when `_run_as` is specified

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1145]
## Describe the Bug
When running a plan that contains functions that use the metaparameter `_run_as` and specifying `--sudo-password` on the command line, a warning is raised (4 times?) that you need to specify `--run-as`.

## Expected Behavior
The warning should only be raised if a user to run as is not specified anywhere.

## Steps to Reproduce

1. Create a plan that includes a function call with the `_run_as` metaparameter:
```
plan test(TargetSpec $nodes) {
  run_command('whoami', $nodes, _run_as => 'root')
}
```
2. Run the plan: `bolt plan run test -n localhost --sudo-password hunter2`

## Environment
 - Version 1.28.0
 - Platform Ubuntu 18.04

**Comment by nicklewis** [comment]
Is this warning helpful? Should we just remove it entirely?

**Comment by lucywyman** [comment]
Since `sudo-password` isn't used if `run-as` isn't specified, it does seem like if someone is set `sudo-password` they at least may have intended to also set `run-as`.  I think if we move the check to being on the target options (ie https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/local/shell.rb#L21) then it'll print for every node that the check fails for. In the case where you have `sudo-password` and `run-as` configured in inventory and just missed one node, that makes sense and seems helpful. In the case where you forgot to specify `run-as` for hundreds of nodes it seems very annoying.

**Comment by nicklewis** [comment]
There still seem to be more cases where it will trigger spuriously than correctly. For instance, if you have a broad setting in the inventory for `sudo-password` but you only sometimes use `run-as`. I think the case where you _forgot_ to specify `run-as` is fairly uncommon.

**Comment by lucywyman** [comment]
Ah - I was thinking that most users would have unique passwords so it made sense to set both sudo-password and run-as together. But I can see a case where only some nodes use the same run-as user, which has the same password. So there you'd want to set a 'broad' sudo-password, but only specify run-as sometimes.

Yeah, it seems more difficult to tell what the right message to send is than the message is worth. Removing it seems right.
