### ISSUE TITLE
Bolt missing error message context on error in module manifest

### ISSUE THREAD

**Issue by zonk1** [puppetlabs/bolt#1152]
## Describe the Bug
I've made an error in json manifest for task with implementations. My requirements stanza contained string instead of an array. Bolt issued an error message which doesn't help too much to find an error.

```
$ bolt task run --nodes mediapi upgrade::upgrade
Started on mediapi...
Failed on mediapi:
  value must be enumerable
Failed on 1 node: mediapi
Ran on 1 node in 0.11 seconds
```
Running with `--debug` doesn't help.

## Expected Behavior
Error messages for errors in config files should point to the place where the error is to allow to locate the problem even in larger code base or when testing bigger change. I would expect ideally filename and line.

```
Failed on mediapi:
      site-modules/upgrade/tasks/upgrade.json:4: "requirements": "raspbian": value must be enumerable
```

Or even `"requirements" should be an array`. But even showing just a field name and value as a context with the exception message could be a huge time saver.

## Steps to Reproduce
Create a module with manifest like below, where `features` is mistakenly set to just string instead of an array. 
```
$ cat site-modules/upgrade/tasks/upgrade.json
{
        "implementations": [
                {"name": "upgrade_debian.sh", "requirements": ["debian"]},
                {"name": "upgrade_raspbian.sh", "requirements": "raspbian"}
        ]
}
```

Run `bolt task run --nodes mediapi upgrade::upgrade`

Attached is a minimal set of config files that displays this behavior.
[bolt-error-message.tar.gz](https://github.com/puppetlabs/bolt/files/3506793/bolt-error-message.tar.gz)

## Environment
 - Version 1.28.0
 - Platform Debian 10

**Comment by donoghuc** [comment]
The underlying error handing has been fixed in puppet when loading task metadata. https://tickets.puppetlabs.com/browse/PUP-10095 tracks that work. It should be released in the next 6.4.z series as well as the next 6.x release.
