### ISSUE TITLE
Change Dockerfile name in root of repo

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1159]
## Describe the Bug
The Dockerfile at the root of the Bolt repo is used for bolt-server. Users who stumble on the Bolt repo and expect that file to build an image that includes Bolt don't expect a testing container used for bolt-server. See https://github.com/puppetlabs/tasks-playground/issues/12

## To do
We should investigate if this container is even being used, and if it is how. Hopefully we can just remove this, or move it to somewhere that makes more sense.

**Comment by lucywyman** [comment]
Notes: Ping Morgan about the Distelli pipelines this might affect.

**Comment by donoghuc** [comment]
Currently Travis is configured to push a bolt-server image to PCR internal https://pcr-internal.puppet.net/pe-and-platform/repositories/bolt-server with https://github.com/puppetlabs/bolt/blob/master/scripts/deploy.sh which uses this Dockerfile. Part of this work should include evaluating  if that is needed any longer or if it needs to be published somewhere else with a different pipeline.

**Comment by donoghuc** [comment]
It appears that the bolt-server is used in orchestrator CI. https://github.com/puppetlabs/orchestrator/blob/4ef187220b690b70875161d54b9720585179a757/test-resources/docker-compose-linux.yml

**Comment by lucywyman** [comment]
[So is pupperware](https://github.com/puppetlabs/pupperware-commercial/blob/02e75f38456adf085500cf3f2ec8c7cfc3f19a0b/docker-compose.yml#L79). Putting up a PR now
