### ISSUE TITLE
Allow tasks to specify defaults for parameters

### ISSUE THREAD

**Issue by gabe-sky** [puppetlabs/bolt#1173]
## Use
New users of my tasks should be able to omit parameters, and have a sensible default value applied.

## Describe the Solution You Would Like
I'd like it if the metadata.json file supported an optional "default" attribute on each parameter, the value of which would be used if the user omits it when invoking the task.  For instance:
```
  "parameters": {
    "port_number": {
      "description": "Port the remote service uses for HTTPS",
      "type": "String[1]",
      "default": "443"
    }
```

## Describe Alternatives You've Considered
I mark these parameters as optional in the metadata.json, and then my script itself silently supplies hardcoded defaults if the parameter is missing.

## Additional Context
This was originally filed in Jira as https://tickets.puppetlabs.com/browse/BOLT-305

**Comment by donoghuc** [comment]
First step is to put up a PR against puppet-specifications for review. Once that has been reviewed/merged we can implement this.

**Comment by nicklewis** [comment]
puppetlabs/puppet-specifications#145 is up with the spec change
