### ISSUE TITLE
What does ""message failed with error 1460" mean?

### ISSUE THREAD

**Issue by njia** [puppetlabs/bolt#1176]
## Describe the Bug
bolt command run uptime -n @host_list (40 hosts)
Failed on most hosts instantly with following messages
Failed to connect to <host>: Messages failed with error: 1460

authentication via LDAP and Yubikey
If I change bolt concurrency to 3, then all command run finished successfully.

## Environment
 - Version 1.29.1
 - Platform Windows 7, MSYS2, ruby 2.5.5.p157

**Comment by lucywyman** [comment]
The error code 1460 is coming from the machines you're trying to connect to. Assuming those are also windows nodes, it seems like there are 2 possibilities: [timeout](https://social.technet.microsoft.com/Forums/ie/en-US/059a64b2-199b-426b-a271-a2163ff09cb8/failed-connection-attempt-error-1460?forum=ForefrontedgePub) and [corrupt driver/filesystem](http://wiki-errors.com/err.php?wiki=1460). Given modifying the concurrency fixed the issue I'm guessing it's timing out.

The timeout is coming from the targest / WinRM itself, as Bolt will wait indefinitely for an operation to finish. It seems like WinRM might have a configurable timeout, so you could try setting that? https://ss64.com/nt/winrm.html
