### ISSUE TITLE
Installation size of Bolt is rather large on Windows

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1177]
From  https://tickets.puppetlabs.com/browse/BOLT-1357

---

I've noticed that bolt is getting longer to install on Windows due to the sheer number of files it lays down on disk. We've come across this in the PDK packaging and Tim Sharpe added a gem-prune script to remove files like spec, test etc. from the vendored gems to help remove the bloat.

Because bolt is just a runtime, so there's no need for these files which are never actually used

---

For comparison, on windows;
Windows 10 1703 default OS install 93,121 files and 19,296 dirs
Bolt 1.20.0 has 17,274 files and 2,141 dirs
Puppet Agent 7,382 files and 1,205 dirs
Microsoft Office Suite has 6,058 files and 612 dirs

**Comment by jpogran** [comment]
Thanks for the report. Apologies, but I created a duplicate (of sorts) of this issue in #2099. I have a PR https://github.com/puppetlabs/bolt-vanagon/pull/146 open which addresses this issue.

**Comment by jpogran** [comment]
Going to close this as duplicate
