### ISSUE TITLE
Make ResultSet array indexable

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1178]
## Use Case
As a plan author I want to access Result objects in a ResultSet by array indexing

## Describe the Solution You Would Like
```
$result = run_plan('module::plan', $nodes)
return $result[0].value
```
ResultSet should be able to be accessed like an array, and should behave similar to typical array accessing.

**Comment by donoghuc** [comment]
closed by https://github.com/puppetlabs/bolt/pull/1283
