### ISSUE TITLE
bolt task run using pcp transport does not work on Linux

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/bolt#1179]
I cannot get the following command to work on RedHat:

 bolt task run facter_task fact=os -n xxx.somecompany.net --transport pcp

The exact command, against the same PE, works fine in WIN.

The OS fact is here:

{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    config_mode => "permissive",
    config_policy => "targeted",
    current_mode => "permissive",
    enabled => true,
    enforced => false,
    policy_version => "28"
  }
}

I have tried this with both bolt 1.27.1 and 1.29.1.

**Comment by bryanjbelanger** [comment]
No, all classifications are managed within the UI.

**Comment by nicklewis** [comment]
This is definitely looking like a bug _somewhere_... Which version of PE are you on?

**Comment by bryanjbelanger** [comment]
2018.1.0

It may very well be a PE bug.

My concern… this command against the same PE works when using Bolt on WIN.

**Comment by lucywyman** [comment]
@bryanjbelanger Is this still an issue for you?
