### ISSUE TITLE
[UX] Displayed MODULEPATH does not match the required OS separator and conflicting docs

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1183]
## Describe the Bug
Running bolt task show emits the modulepath at the end, however it does not use the OS specific path separator, which is a bad user experience.

## Expected Behavior
Where OS specific text is used, it should be mirrored by bolt's output

## Steps to Reproduce
1. Install Bolt
2. Run `bolt task show`

```
C:\Source> bolt task show
facts                    Gather system facts
package                  Manage and inspect the state of packages
puppet_agent::install    Install the Puppet agent package
puppet_agent::version    Get the version of the Puppet agent package installed. Returns nothing if none present.
puppet_conf              Inspect puppet agent configuration settings
reboot                   Reboots a machine
reboot::last_boot_time   Gets the last boot time of a Linux or Windows system
service                  Manage and inspect the state of services

MODULEPATH:
C:/Users/glenn.sarti/.puppetlabs/bolt/modules:C:/Users/glenn.sarti/.puppetlabs/bolt/site-modules:C:/Users/glenn.sarti/.puppetlabs/bolt/site

Use `bolt task show <task-name>` to view details and parameters for a specific task.
C:\Source>
```

Note the `:` between `modules` and `C:/Users`

## Environment
 - Version 1.20.0
 - Platform Windows 10 - 1903

## Additional Context

The docs are contradictory.

https://puppet.com/docs/bolt/latest/bolt_command_reference.html  say you have to use a colon  for any use of modulepath

but https://puppet.com/docs/bolt/latest/bolt_configuration_options.html#global-configuration-options says modulepath is

> The module path for loading tasks and plan code. This is either an array of directories or a string containing a list of directories separated by the **OS-specific PATH separator**

Puppet Agent does emit the paths correctly.

e.g.
```
C:\Source> puppet config print modulepath
C:/ProgramData/PuppetLabs/code/environments/workstation_production/modules;C:/ProgramData/PuppetLabs/code/modules
```

**Comment by glennsarti** [comment]
Also noticed in modulepath it says `Directories are case-sensitive.`  This isn't the case on NTFS filesystems

**Comment by glennsarti** [comment]
@adreyer I noticed that the PR didn't address the "directories" are case sensitive comment above. Is there a separate docs ticket for this I'm not aware of?

**Comment by lucywyman** [comment]
I think the purpose of the comment is that if folks are having trouble loading the expected modulpath, they should make sure it matches the case of the actual modulepath. I don't think there's a risk here of people on non-case-sensitive systems using case-sensitive paths - the worst case scenario is that they can't find their module, they make the path match the case, and still can't find the module so try something else. Making the phrasing more nuanced seems cumbersome.

With that said I think we'd be happy to accept a PR modifying the language!
