### ISSUE TITLE
Add parameters to apply_prep function

### ISSUE THREAD

**Issue by krische** [puppetlabs/bolt#1184]
## Use Case
The `puppet_agent::install` task has several useful parameters on it, such as the version to install and alternate sources to download from. However, it is currently not possible to specify those parameters to the `apply_prep` function.

## Describe the Solution You Would Like
I would expect that the `apply_prep` function can accept the same parameters as the `puppet_agent::install` task and use those parameter values when calling the task.

## Describe Alternatives You've Considered
There is currently a workaround, and that is to call `puppet_agent::install` task with the `run_task` function; specifying the desired parameters. However, it appears that it is still necessary to run `apply_prep` afterwards, so that all the node's facts can be gathered.

## Additional Context
This was originally issue [BOLT-1524](https://tickets.puppetlabs.com/browse/BOLT-1524).

**Comment by lucywyman** [comment]
Hi @krische - we've actually got a PR up right now (https://github.com/puppetlabs/bolt/pull/1157) that allows you to configure how the puppet agent gets installed when `apply_prep` is called, including passing parameters to `puppet_agent::install` or writing your own task. #1123 is the related issue describing the solution. That PR is pretty close to done and should be released next week!

**Comment by lucywyman** [comment]
Hi @krische - we just released the work linked above! I'm going to close the issue since I think this is done now, but if the latest release (1.30.0) doesn't solve your problem let me know and we can reopen and investigate.
