### ISSUE TITLE
add --logfile flag to command run

### ISSUE THREAD

**Issue by actowery** [puppetlabs/bolt#1194]
## Use Case
As a PE user, I would like to have timestamped logs specific to each `puppet infra run` command I execute, similar to installer logs stored in `/var/log/puppetlabs`. These logs will be easier to sift through and search compared to the single monolithic bolt log we have currently operating for our infra commands. Inside the modules, the current attempt to do such a thing requires on-the-fly manipulation of our configfile which is admittedly hacky and is difficult to maintain in the case of an execution error or other form of early exit.

## Describe the Solution You Would Like
a `--logfile` flag added to the run command that could take one or more filepaths for one-off logging in addition to the bolt.yaml log settings that will either inherit the log level of the config file or is given its own level with another flag such as `--loglevel`

## Describe Alternatives You've Considered
An alternative that has been attempted is to on-the-fly edit the configfile using ruby's YAML module. Although this works, it just doesn't seem like the right way to do it. One issue is if a user ever runs multiple commands in parallel, multiple logs would be written to whatever log file(s) have been set in that moment before cleanup.

We have also considered cloning the bolt.yaml file itself, editing the new file and pointing to the new clone with `--configfile`. This helps eliminate the logging race conditions created, but is still a little strange to do in the middle of an invocation and leaves much to be cleaned up.

**Comment by adreyer** [comment]
@jpartlow @highb does this require changes to `puppet infra` too?

**Comment by highb** [comment]
We have a collection of options that we expose on `puppet infra` so if this flag was added, we'd need to add it to the list.
