### ISSUE TITLE
Allow all implementations of the bundled facts task to attempt to use facter

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1195]
## Describe the Bug
Currently, only the ruby implementation of the `facts` task will attempt to use `facter` to gather facts. This implementation requires the `puppet-agent` feature. The `bash` and `powershell` implementations do not attempt to find a facter executable to use. The non-ruby implementations used to try to shell out to facter, but that was removed with https://github.com/puppetlabs/puppetlabs-facts/commit/9b7fe391628074ebdc80e249cdd443ae0dbc0a7a#diff-9c2cc9c609fe4c1df5adf589017c18f5 to attempt to solve the problem where sometimes rich data was returned by facter, while others only the minimal facts gathered by the scripts was  returned. The idea was to *only* expect rich facter facts when `puppet-agent` was set. 

## Expected Behavior
The user interface for the `facts` task should not use the `puppet-agent` feature to gate what data is returned. Instead the non-ruby tasks should try to find a facter executable and use it to gather all the facts possible. 

## Additional Context
Could consider adding `source` "meta fact" to the facts that are returned.

**Comment by nicklewis** [comment]
https://github.com/puppetlabs/puppetlabs-facts/pull/36
