### ISSUE TITLE
Support communication via MCollective

### ISSUE THREAD

**Issue by cardil** [puppetlabs/bolt#120]
As said in title - support for MCollective will be nice feature.

**Comment by ripienaar** [comment]
In the Choria project I have a few plans here:

A way to run tasks via mco with files downloaded from a puppetserver and all the usual AAA and so forth https://github.com/choria-io/mcollective-choria/issues/347

A way to write playbooks in plans this is shipping this week preview docs here dev.choria.io/docs/playbooks/plans/

A way to ship tasks/functions/plans in agent modules shipping this week https://github.com/choria-io/puppet-mcollective/issues/138

A way to run tasks from playbooks shipped already 

And yeah I would probably like to add a choria transport to bolt but it seems to be a bit hard right now to plug new transports into bolt as a plugin delivered by other projects

**Comment by darkn3rd** [comment]
This would be great.  There are some big shops that are using MCollective, one of them a prominent e-commerce PaaS solution.

**Comment by ripienaar** [comment]
@darkn3rd worth checking out above mentioned choria project, capable of running tasks and plans (see its playbooks) now.

**Comment by lucywyman** [comment]
We've deprecated MCollective - @adreyer @MikaelSmith @donoghuc @nicklewis  are we comfortable closing this?
