### ISSUE TITLE
Task parameters with `type` in the name are filtered out with powershell v2

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1205]
## Describe the Bug
When running a powershell task against a target using a powershell 2 interpreter, parameters with the string `type` in the name were filtered out and not passed to the task. 

## Expected Behavior
Parameters, for example `footype` should be passed to powershell tasks. 

## Additional Context
This will also need to be fixed in pxp agent in addition to the winrm/local windows transports.

**Comment by Iristyle** [comment]
The equivalent pxp-agent fix is located at https://github.com/puppetlabs/pxp-agent/pull/772
