### ISSUE TITLE
Unable to call run_task() in noop mode from a plan

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1207]
## Describe the Bug
From a plan i'm trying to call a `run_task()` and have it execute in noop mode. No matter what value i pass to `run_task()` the task never seems to be receiving a value for the `_noop` parameter.

## Expected Behavior
When i pass in the `_noop` option into `run_task()` i would like the `_noop` parameter to be passed into the task.

## Steps to Reproduce
1. Create a task metadata file:
```json
{
  "description": "Tests noop",
  "supports_noop": true
}
```

2. Create a task shell script:
```sh
#!/bin/bash

echo "PT__noop = $PT__noop"
if [[ -n "$PT__noop" && "$PT__noop" == "true" ]]; then
  echo "noop mode"
else
  echo "regular mode"
fi
exit 0
```

3. Create a plan:
```puppet
plan patching::noop_test (
  TargetSpec $nodes,
) {
  return run_task('patching::noop_test', $nodes,
                  _noop => true)
}
```

4. Execute the plan and check the output: 
```sh
bolt plan run patching::noop_test --nodes xxx
.....
  PT__noop = true
  noop mode
  {
  }
```

## Environment

 - Version:
```sh
$ bolt --version
1.30.0
```

 - Platform
```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

## Additional Context
I think this is caused by the following line of code: https://github.com/puppetlabs/bolt/blob/master/bolt-modules/boltlib/lib/puppet/functions/run_task.rb#L68

It seems that this line is splitting all of the options passed into `run_task()` that start with a `_` into another hash. The `_noop` parameter is never added back into the `use_args[]` hash and therefore lost when executing the task.

**Comment by lucywyman** [comment]
Hi Nick!

I'm running into this too trying to use `_catch_errors`. I'll follow up with the team tomorrow - I'm not sure what the line is *intended* to do, but I don't think this behavior is desired.

**Comment by donoghuc** [comment]
This showed up in the stream but just wanted to comment on it here. https://github.com/puppetlabs/bolt/pull/1237#issuecomment-539137427 There is a code path in the CLI where `noop` *would* be passed to plan run. This ticket should maybe include addressing if we want to support that or not.
