### ISSUE TITLE
Ensure puppet agent version with apply_prep()

### ISSUE THREAD

**Issue by krische** [puppetlabs/bolt#1208]
## Use Case
From what I can tell, it looks like the `apply_prep()` function will only install puppet agent if it is not currently installed on the target. If it is not installed, it will installed the version specified (via plugin_hooks). However, it will not ensure the version specified is installed if there already is any version installed.

## Describe the Solution You Would Like
If an exact puppet agent version was specified for the `puppet_agent::install` task, I would like the `apply_prep()` function to ensure that version is installed on the targets.

## Describe Alternatives You've Considered
There is currently a workaround, and that is to call `puppet_agent::install` task with the `run_task` function; specifying the desired parameters. However, it appears that it is still necessary to run `apply_prep` afterwards, so that all the node's facts can be gathered.

## Solution
We should remove the puppet_agent version check from the `apply_prep` function and just use the install task.
* The behavior of the install task should be that if the agent is installed and version 'any' is passed.
* If the agent is installed and the version doesn't match then it should try to install the specified version.

**Comment by lucywyman** [comment]
@krische I believe that this only won't downgrade the puppet agent, but it should upgrade it. What version of the agent are you looking to install? Are you configuring this with the inventory plugin?

**Comment by lucywyman** [comment]
I'm going to close this since I don't think there's anything for us to do - let me know if it needs reopening.

**Comment by krische** [comment]
Sorry for the late reply, this is what I'm talking about specifically.

**Steps to Reproduce**
1. Assume we have a plan with the following:
    ```puppet
    plan some_module::some_plan (
      TargetSpec $nodes
    ) {
      apply_prep($nodes)
    }
    ```
2. Install a specific version of puppet agent by configuring the plugin hook in `bolt.yaml` configuration file. Here is an example `bolt.yaml` snippet to configure the version of puppet agent installed:
    ```yaml
    plugin_hooks:
      puppet_library:
        plugin: task
        task: puppet_agent::install
        parameters:
          version: '6.9.0'
    ```
3. Now, let's say we change the version of puppet that gets installed. So change the `bolt.yaml` snippet to the following:
    ```yaml
    plugin_hooks:
      puppet_library:
        plugin: task
        task: puppet_agent::install
        parameters:
          version: '6.10.0'
    ```
**Expected Behavior**
I would expect the version of puppet installed to be upgraded to the version specified.

**Actual Behavior**
Puppet is only installed to the specified version if puppet is not currently installed on the target node. If puppet is already installed on the target node, nothing happens, not even an upgrade.

It would appear that from [this line in the code](https://github.com/puppetlabs/bolt/blob/a0a8b1d68c95e6013ef95a16be028209c66c7278/bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb#L89) that the version of puppet currently installed is only used to determine whether or not puppet is installed. The installed version is not used to determine if an upgrade is necessary.

**Comment by krische** [comment]
I did look at the [documentation](https://puppet.com/docs/bolt/latest/plan_functions.html#apply-prep) and it does specifically mention the agent will only be installed if it isn't currently present.

So this issue would best be labeled as a feature request.

**Comment by lucywyman** [comment]
Ahh I see. I'll discuss with the team - I think always upgrading the agent could be an issue. Some folks may be using a specific version within their puppet infrastructure, but want to configure this to install a newer agent on any machines not in that infrastructure. In that case they wouldn't want it to be upgraded if the specified version is newer. We could potentially add an additional option to upgrade that's off by default?
