### ISSUE TITLE
Standardize JSON and Puppet language Result objects

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1245]
## Use Case
It can be confusing that the JSON representation of a Result or ResultSet do not behave the same way as the puppet objects. They should be harmonized as part of the 2.0 release of bolt.

## Describe the Solution You Would Like
* Add a new `status` attribute to a the Result object that is a string.
* Remove `node` from Result status_hash and attributes in favor of `target` (read: the JSON representation of the Result)
* Rename `result`  to `value` in the Result JSON representation

## Describe Alternatives You've Considered
These were decided to be the least breaking changes to harmonize these object.

## Additional Context
We should also add a key to the config `future` which will be in front of this feature (so when the flag is true, this is on). The config key should be globally accessible, so we can read it from anywhere without having to pass config around.

**Comment by donoghuc** [comment]
Closed with https://github.com/puppetlabs/bolt/pull/1281
