### ISSUE TITLE
Log file uploads

### ISSUE THREAD

**Issue by nicklewis** [puppetlabs/bolt#1256]
## Use Case
Currently, there's no good way to diagnose which files are uploaded by Bolt as part of running a task. They're uploaded to a random directory and deleted after Bolt runs, so you can't look at them on the filesystem. There are also not log messages associated with file uploads for every transport, so you can't check whether Bolt uploaded the right things. This can also lead users to the appearance that Bolt isn't doing the right thing, when it did in fact upload the correct files.

## Describe the Solution You Would Like
Each transport should issue  debug message for each file that is uploaded, just as it does for each command that is run.

## Describe Alternatives You've Considered
Another way to handle this uncertainty about what Bolt is doing would be to add an option to preserve the tempdir after Bolt runs, so that users can log in and inspect it. That would likely require a new CLI flag and would also cause trouble for cases where Bolt creates multiple tempdirs. It also would require Bolt have some clear way to tell users where the tempdir is.

**Comment by donoghuc** [comment]
Closed by https://github.com/puppetlabs/bolt/pull/1287
