### ISSUE TITLE
Support project level plans

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1267]
## Use Case
It's painful for new users to have to create three levels of directory before `site-modules/<module-name>/plans` before writing their first plan.

## Describe the Solution You Would Like
The project should implicitly be a module with it's own plans, tasks, manifests etc.  Users should think of projects as ready to use applications while modules are libraries meant to be called from a project. 

## Requirements
* For now users should opt into this experimental behavior by adding `project_name` to bolt.yaml.
   * `project_name` should not be merged from global config
   *  Project names must be valid module names. Existing core modules like `boltlib` and `out` should be considered reserved project names.
* When a project is named it should be loaded as a module that shadows any similarly named module on the module path.
* The boltdir directory name does not need to match the `project_name`. This is not a critical requirement for the first iteration.

**Comment by hlindberg** [comment]
I assume 4.x loader load plans like all other kinds of loadable things and it treats the "environment" directory like a module. It would thus support `modules/plan.yaml` for a non namespaced plan, and `modules/stuff/plan.yaml` for a one that is namespace "stuff". Also, if a plan is in a manifest file - it can define any plan. All this is just how functions work - there are details in the specifications repo here https://github.com/puppetlabs/puppet-specifications/blob/master/language/func-api.md#autoloading).

Thus if hacking on plans, I would expect to be able to tell bolt to load a .pp file and run one out of several plans in that file - kind of how "puppet apply" works.

**Comment by nmaludy** [comment]
+1
