### ISSUE TITLE
Standardize CLI flags

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1269]
## Use Case
having flags like `--password` that takes an optional argument limits how we can accept arguments and the quality of error messages we can give. Many of the flags may no longer make sense now that bolt supports an inventory file. 

## Describe the Solution You Would Like
* Replace flags with optional arguments like `--password` a `--password` flag that requires an argument. The `prompt` plugin should be used when password prompt is needed.
* Consider what CLI flags still make sense in light of inventory improvements. Any flag must either require a parameter or not accept one. 
* Send `prompts` to stderr instead of stdout to avoid breaking the JSON outputter (update the prompt plugin)
* Any breaking changes should have deprecation warnings in the 1.x series
* Note: Cannot gate this with `future` flag in a meaningful way, so instead we need to just provide deprecation warning for the things we intend to get rid of. 

* Add a `--password-prompt` and `--sudo-password-prompt` prompt for data on stderr.
* For now, warn and advise to use `--*-prompt` or prompt plugin, make password required in 2.0.

**Comment by donoghuc** [comment]
Closed by https://github.com/puppetlabs/bolt/pull/1355
