### ISSUE TITLE
Bolt Project Scaffolding/Init

### ISSUE THREAD

**Issue by highb** [puppetlabs/bolt#1285]
## Use Case
I'm a user trying to get started on adding Bolt to my project. Having used the pdk previously, I want to do something equivalent to `pdk new` in my project directory to add Bolt to it.

## Describe the Solution You Would Like
I type `bolt new_local_project` `bolt new_embedded_project` `bolt new_user_project` or something similar and get the directory structure described in the docs here https://puppet.com/docs/bolt/latest/bolt_project_directories.html#local-project-directory

## Describe Alternatives You've Considered
Making a bunch of directories myself and hopefully not making any typos.

## Solution
We should create a new command `bolt project init` which creates a `bolt.yaml`.

**Comment by adreyer** [comment]
In order to match the other commands `bolt project init <optional-path>` makes sense where path defaults to `./`

Since this is targetted at the new user it should not create a lot of extraneous files just the minimum that would be useful.

**Comment by highb** [comment]
Makes sense to me. 😄
