### ISSUE TITLE
bolt plan apply{} blocks fail when a user's homedir is on NFS with root squash enabled.

### ISSUE THREAD

**Issue by mlanghor** [puppetlabs/bolt#1319]
## Describe the Bug
I've created a relatively simple blan with an apply block to create a user & group on a server.  When I attempt to run bolt plan run <plan name> against a node I receive a permission denied on my home directory.
error snippet:

The task failed with exit code 1:
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/module_tool/tar/gnu.rb:8:in `chdir': Permission denied @ dir_chdir - /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/module_tool/tar/gnu.rb:8:in `chdir': Permission denied @ dir_chdir - /home/mlanghor (Errno::EACCES)
        from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/module_tool/tar/gnu.rb:8:in `unpack'
        from /tmp/a03a2d62-e790-4715-ac49-87a646bc809b/apply_catalog.rb:42:in `block in <main>'
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/tempfile.rb:295:in `open'
        from /tmp/a03a2d62-e790-4715-ac49-87a646bc809b/apply_catalog.rb:40:in `<main>'

On the remote server, my directory /home/mlanghor is an NFS mounted home directory, on which the NFS server has root squash enabled.  Therefore the root user cannot see or access files in my home directory.

I get similar issues with Puppet's exec resources if/when I run puppet agent when I'm in my home directory, though without exec resources it will run ok.

My full bolt command line I was attempting to run:  bolt plan run caiso_unix_utils::add_springboot_workspace nodes=server1 user=blah uid=20000 port_prefix=400 --modulepath=./ --run-as root --sudo-password

## Expected Behavior
when I run the bolt plan with --run-as root, it should not use my home directory and should execute successfully.

## Steps to Reproduce
Have a remote system using an NFS mount for user's home, with root squash enabled (so root cannot access your home directory).  Also homedir is set to 0750 permissions

## Environment
 - 1.33.0
 - CentOS 7.6 as a intiating client
 - RHEL 7.6 as the target node.

## Solution
* When running with a temporary directory over SSH or local transport (calling `with_tempdir`) we should cd into the specified `tmpdir` before executing.

**Comment by lucywyman** [comment]
This seems like it *might* be coming from https://github.com/puppetlabs/bolt/blob/master/libexec/apply_catalog.rb#L42

**Comment by nicklewis** [comment]
A workaround for this issue is to install minitar on the target systems. `/opt/puppetlabs/puppet/bin/gem install minitar`. That implementation doesn't involve this `Dir.chdir { ... }` pattern that requires it be able to `cd` back to its current working directory.
