### ISSUE TITLE
Make it easier to optionally set module based plugins either bolt config or inventory

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1322]
## Use Case
As a plugin consumer and author I want to be able to set parameters to be used in the plugin implementations either in `bolt.yaml` or `inventory.yaml`. Currently this requires handling merging the top level parameters passed to the task implementations with the keys nested under `_config`. This also prevents using metadata to require a parameter when it could be provided in either `bolt.yaml` or `inventory.yaml`. As a plugin author I do not want to have to handle munging that data and dealing with precedence. 

## Describe the Solution You Would Like

* If a bolt_plugin.json file has a config specification it should continue to behave as it does today for now. The config should be validated against it and passed as `_config`.
*  If the bolt_plugin.json file does not have a config specification should be the intersection of the task parameters for each hook. Each config value should be treated as optional since it could be passed as an option to the plugin instead
* If the bolt_plugin.json file does not have a config section when the plugin runs the options passed to the specific invocation of the hook should be merged into the config values. IE the config values are providing defaults for the task parameters. The `_config` hash should not be passed.

The expectation of this work is that `_config` and setting `config` in `bolt_plugin.yaml` will be deprecated.

**Comment by lucywyman** [comment]
If no config is defined in `bolt_plugin.json` then we accept any config that would work for all of the hook tasks.
