### ISSUE TITLE
Acceptance tests should use bolt's internal puppetfile

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1345]
It looks like the acceptance tests preempt bolt's bundled content by managing modules separately acceptance/setup/common/pre-suite/071_install_modules.rb. This is both unrealistic and requires us to maintain two sources of truth. Instead of installing these modules as a presuite each install method should manage these modules if needed from bolts internal Puppetfile.

**Comment by donoghuc** [comment]
Oh, oops I thought you wanted that as just a maint commit. https://github.com/puppetlabs/bolt/pull/1346 I raised that PR before I saw this. Can fix it up with ref to this issue.
