### ISSUE TITLE
Fedora 31 RPMs

### ISSUE THREAD

**Issue by buckaroogeek** [puppetlabs/bolt#1373]
## Use Case
the Fedora project has release version 31 to users. Could you please update the Puppet yum repository to support this new release.

## Describe the Solution You Would Like
Update the Puppet yum repository with support for Fedora 31

## Describe Alternatives You've Considered
Continue to use Fedora 30 rpms

thank you!

**Comment by lucywyman** [comment]
Hello! We're still waiting on Fedora 31 images to be available for building on - you can track that work at https://tickets.puppetlabs.com/browse/IMAGES-1153 . Once those are ready we'll add this asap!

**Comment by beechtom** [comment]
Closed by #1517
