### ISSUE TITLE
[Bolt 2.0 Feature Request] Use shell arguments for commands instead of a string

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1401]
## Use Case
Currently Bolt uses a single string to pass in arbitrary commands, for example:

``` powershell
C:\Source> bolt command run --targets localhost echo "Hello"
Unknown argument(s) Hello

C:\Source> bolt command run --targets localhost 'echo "Hello"'
Started on localhost...
Finished on localhost:
  STDOUT:
    "Hello"
Successful on 1 node: localhost
Ran on 1 node in 0.05 sec
C:\Source>
```

While this seems like a trivial UX piece, it would make much more sense that arbitrary commands should be passed in exactly as the come into the bolt process (i.e. in ruby terms as ARGV)

This has a significant number of benefits:

1. The calling shell process can use whatever escape characters it requires to craft the needed command.  Currently a level of double-escaping is required, particularly for Windows users.

- Bolt, the package, uses PowerShell
- Bolt the gem uses Bundler, which is cmd.exe
PowerShell and cmd.exe use vastly different shell semantics.

2. This reduces the double handling inside Bolt itself.

Currently Bolt receives the command as a string, and then has to use helper libraries to then split that string back out to an array (using ShellWords). Which is double handling, and at worst a guess on Windows (See point 3).

https://github.com/puppetlabs/bolt/blob/310a519873765103776b3d860a48098bc14eff15/lib/bolt/transport/docker.rb#L62

https://github.com/puppetlabs/bolt/blob/63b43369010a050bd5ae9da7668237ff0589ff98/lib/bolt/transport/local/shell.rb#L131

This test doesn't even make sense as ShellWords is not supported on Windows Shells (cmd.exe or PowerShell.exe)

https://github.com/puppetlabs/bolt/blob/abc30e30967398baed752dca2a4b70e0030a7404/spec/bolt/transport/winrm_spec.rb#L480

If Bolt internally kept all commands as arrays, and only rendered as a full string when needed, none of this double handling would be required. Which brings me to the next point

3. There is no ShellWords solution for Windows

> This module manipulates strings according to the word parsing rules of the UNIX Bourne shell.

Ref - https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html

The ShellWords gem used in Bolt supports POSIX based shells, which excludes the Windows Shells cmd.exe and PowerShell.exe (and probably Pwsh.exe too)

By using an array instead of a splitting a single string this avoids the entire cross-platform problem that ShellWords has.

As an example: How would would you split the command `echo 'Hello'`

In cmd.exe single apostrophes (`'`) are not a string terminator, but in PowerShell they are. Given a pure string, Bolt really has no hints as to what the best way to split it is. And really, that's not Bolt's domain.

The user should be able to show intent as to where parameters should be delimited, i.e.

`bolt command run --targets localhost "echo 'Hello'"` and `bolt command run --targets localhost echo 'Hello'` should result in different command being run.

## Describe the Solution You Would Like
`bolt command run` usage be like

`bolt command run <options> [command]`

Where `command` is the remaining command line arguments as an array of string

There may be some impliciations with the Bolt configuration file, in particular the interpreters section.  As that can set a command line to use.  IIRC, that can be an array or a string depending on the transport.  Ideally, this should be an array as well.

## Describe Alternatives You've Considered

This is a breaking change as far as UX and execution go. Currently I've only considered the `command run` Bolt option, but IIRC that is the only place an arbitrary command is used.

## Additional Context

This was a MAJOR headache adding docker support for Windows. See https://github.com/puppetlabs/bolt/pull/1069#issuecomment-532945808 and https://github.com/puppetlabs/bolt/pull/1069#issuecomment-535341489

So much so that I had to abandon using the Bolt CLI entirely and inject the command line using ruby. As a Windows developer on Bolt, this was a horrible experience.

**Comment by adreyer** [comment]
This would require a major refactor of option parsing and would prevent us from using "bare" arguments for anything else(see #495). If `bolt command run` was the primary use case we optimized bolts design for I think this would be a good improvement. However, I'm more interested in optimizing bolt for plan usage and don't think we should limit the ability to accept global bare options to improve only the command interface.

**Comment by bacongravy** [comment]
Would a wrapper script (say, `bolt-exec`) that handled the arguments as described in this ticket, and then Shelljoin'd them and invoked `bolt command run` with them as a single argument, be a workable compromise?

**Comment by glennsarti** [comment]
@adreyer 

> would prevent us from using "bare" arguments for anything else
True

> optimizing bolt for plan usage
So calling bolt (tasks really..) from within plans, or using the bolt command line to execute plans?

@bacongravy 
> be a workable compromise?

Yes and no. Yes it would work around the CLI part but then you're triple handling.

bolt-exec -> receives ARGV -> constructs a bolt command -> which converts it into a string -> Bolt transport then may or may not need to split it back out to an array again.

And Shell join, again, is a BASH compliant utility.  There are zero guarantees that the joined string will work in cmd or PowerShell shells.

To be honest, the title of this issue should probably focus more in the ShellWords problem than the CLI, but the CLI is more what the user will see.

**Comment by glennsarti** [comment]
Currently (I believe) the architecture looks like this

Where the Bolt CLI or Plan, will find the command to run and send that "to Bolt" and then the transports are responsible for executing it.  Currently (at least in the Bolt CLI land) that's a string but I've seen cases where it accepts a String or an Array

``` text
    UI Layer                                                         Various Transports
                                                                                          Doesn't have the context to be able to split
                                                                                          the string from the UI context, to the desired
                                                                                          platform
+---------------+                                                  +-------------------+
|               |                                                  |                   |
|  Bolt CLI     +--+                                            +--+  Local Transport  |
|               |  |                                            |  |                   |
+---------------+  |                                            |  +-------------------+
                   |                                            |
+---------------+  |                        +----------------+  |  +-------------------+
|               |  |                        |                |  |  |                   |
|  Puppet Plan  +--+-- String (or Array)--> | Bolt internals +--+--+  WinRM Transport  |
|               |  |                        |                |  |  |                   |
+---------------+  |                        +----------------+  |  +-------------------+
                   |                                            |
+---------------+  |                                            |  +-------------------+
|               |  |                                            |  |                   |
|      ????     +--+                                            +--+ Docker Transport  |
|               |                                                  |                   |
+---------------+                                                  +-------------------+
```

However the transports don't have the UI context to know how to split the command properly if it needs it (for example, open3.capture3 in Windows land)

Whereas, if Bolt internally treated **ALL** commands as strings then the transports don't need to concern themselves with context (also avoids using ShellWords internally, and pushes that out the UI layer), and then transports can construct their commands without needing context

So more like:

```
    UI Layer                                                         Various Transports
                                                                                          Commands are then joined according to where they will be executed
+---------------+                                                  +-------------------+
|               |                                                  |                   |
|  Bolt CLI     +--+                                            +--+  Local Transport  |   --> String of Bash or CreateProcessW
|               |  |                                            |  |                   |
+---------------+  |                                            |  +-------------------+
                   |                                            |
+---------------+  |                        +----------------+  |  +-------------------+
|               |  |                        |                |  |  |                   |
|  Puppet Plan  +--+-- Renders to array --> | Bolt internals +--+--+  WinRM Transport  |   ---> PowerShell
|               |  |                        |                |  |  |                   |
+---------------+  |                        +----------------+  |  +-------------------+
                   |                                            |
+---------------+  |                                            |  +-------------------+
|               |  |                                            |  |                   |
|      ????     +--+                                            +--+ Docker Transport  |   ---> Container Platform dependant (Bash or cmd.exe or PowerShell)
|               |                                                  |                   |
+---------------+                                                  +-------------------+
```

* Also avoids the need for double quoting when adding to command strings (important for Windows) and other annoyances within Bolt itself.   The transports will have the context needed to convert a command array of String into something that can be executed.

**Comment by adreyer** [comment]
I don't think we're going to support command arrays from the CLI it just just too much work and doesn't solve enough to the quoting issues to justify completely changing argument parsing including global contstraints to improve the command use case.

I don't think you're arch is correct either. The plan does not render the command string to an array the individual transports build arrays in certain cases themselves.

I'm not opposed to updating `run_command` in the plan language to accept commands as an array but I don't think that is what you want to see.
