### ISSUE TITLE
Cannot use PDK and Bolt in the same PowerShell session (Process)

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1402]
## Describe the Bug

If you run PDK, then Bolt and then PDK again, PDK will terminate with a ruby error

``` powershell
C:\Source> pdk --version
1.14.1
C:\Source> bolt --version
1.31.1
C:\Source> pdk --version
Traceback (most recent call last):
C:\PROGRA~1\PUPPET~1\Bolt\bin\ruby: No such file or directory -- C:/PROGRA~1/PUPPET~1/Bolt/bin/pdk (LoadError)
```

This also occurs in the reverse (bolt -> PDK -> Bolt)

``` powershell
C:\Source> bolt --version
1.31.1
C:\Source> pdk --version
1.14.1
C:\Source> bolt --version
C:\PROGRA~1\PUPPET~1\DEVELO~1\private\ruby\2.4.9\bin\ruby.exe: No such file or directory -- C:/PROGRA~1/PUPPET~1/DEVELO~1/private/ruby/2.4.9/bin/bolt (LoadError)
```

This is due to both PowerShell wrappers managing the same Environment Variables (RUBY_DIR, SSL_CERT_FILE and SSL_CERT_DIR)

https://github.com/puppetlabs/pdk-vanagon/blob/021c4382233a04a8e0a1536352fb9f27a300bf80/resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1#L6-L8

https://github.com/puppetlabs/bolt-vanagon/blob/c48d7c60b7ec51675eeb11d64e8bc6c802883f2e/resources/files/windows/PuppetBolt/PuppetBolt.psm1#L6-L9

Because these environment variables are only set at module import time, not at function invocation time, both wrappers are stomping over each other and causing errors.

Ideally environment variables should not be used at all and instead use command line invocations.

## Expected Behavior
Should be able to use PDK and Bolt seamlessly in the same PowerShell session

## Steps to Reproduce
``` powershell
PS> pdk --version
PS> bolt --version
PS> pdk --version
```

## Environment
Windows 10 - 1903
PDK 1.14.1
Bolt 1.13.1

## Additional Context
Cross post to PDK Project https://tickets.puppetlabs.com/browse/PDK-1547

**Comment by scotje** [comment]
We've made a fix for this in the PDK PowerShell module which should solve running PDK after Bolt, but I think a comparable change to the Bolt PS module will need to be made to support running Bolt after PDK.

See https://github.com/puppetlabs/pdk-vanagon/pull/247/files for applicable changes.
