### ISSUE TITLE
Support Hiera lookup() in plans outside of apply blocks

### ISSUE THREAD

**Issue by magnuslarsen** [puppetlabs/bolt#1403]
This is a duplication of a closed issue on the old ticket management:
https://tickets.puppetlabs.com/browse/BOLT-836

## Feature Request
It would be handy to support the hiera lookup() function within a plan.
## Open Question
What goes into the hierarchy for a plan? Without facter how are those values set? 
### Lookup different values to use the same plan in different environments or contexts

As a plan author i need to store data about how to execute the plan that may be environment or deployment specific. These settings would be looked up from the "perspective" of the bolt controller node. Example: may need different API keys, credentials, etc to use for API calls. Example 2: may be deploying in a different manner based on a setting in a config that is easy to switch.

### Use hiera to lookup task parameters for different targets

As a plan author i need to perform actions differently depending on certain facts and/or attributes of a node. These facts may be gather by the `facts` task. From these facts/attributes i then need to lookup() data to determine how the action should be run.  These facts would be looked up from the "perspective" of specific targets. Example: I'm deploying a software package against a variety of hosts, some may be 32-bit some 64-bit. I need to deploy different versions of software to the 32-bit systems. I would run a 'facts' task to determine architecture, then choose which software package to copy and install. The data hierarchy would be used to uniquely specify which software package to utilize.
## Learning from spike

* currently just exposing hiera allows backends to work without interpolation as long as all interpolation is based on $facts and $trusted. The fact that those are set during plan execution feels wrong and may be a bug.
* We probably need the ability for users to specify a separate hiearchy for the plan level so we don't limit interpolation options.
* There is value in exposing backends so that hiera-eyaml can be used but this problem may be solved by supporting eyaml in inventory.

# Questions for commentors
* What levels of hierarchy would you use at the plan level?
* Would there be any fact like interpolations in the hierarchy? What values would be used?
* Do you expect values from plan level data to be automatically set anywhere with data bindings like classes in manifests?

# The Plan
Users are interested in looking up hiera data outside of apply blocks in plans. There should be one context for the entirety of the plan, and it should always be empty. For now.
## Use Case
For now, this exists to give people the lookup function they seem to expect. Our goal is to learn more about how people want to use this functionality.
## Requirements
- [x] If the hierarchy references interpolations we should error
  **Note:** Requires changes in Puppet to remove `facts`, etc. from the `ScriptCompiler` scope. See https://github.com/beechtom/puppet/commit/6a8a7f5f0092e9f82c1669f2f2e54d5edb3c9439
- [x] We should use the config from the `hiera-config` option for now
- [x] You can use backends
- [x] We should collect analytics only when the plan-level function is called
  **Note:** Not sure if this is feasible currently. Wrapping the `lookup` function is difficult and there doesn't seem to be anything we can inject into Puppet.
- [ ] Document as experimental
  **Question:** Where is the best location for this documentation? 'Writing Plans'?

**Comment by magnuslarsen** [comment]
And a copied comment from Henrik Lindberg:


Some thoughts about implementation...

One thing to consider here is that switching "perpective" (bolt controller, each node) using a single hiera instance will lead to its cache being evicted on each switch. This would potentially be quite bad for performance if many such switches are required as a bolt run progresses. Imagine looping over a set of nodes and in each iteration some plan specific, and some node specific value needs to be obtained.

From a UX perspective everything could be hidden unless it should be possible to lookup node specific values in a plan. For that, it must be possible to use a different perspective. This could be another function for example (lookup_for_node()), or a method on a node/target.

When designing the "perpectives", a big question is if it should be possible to override a node perspective in the plan perspective. If not, it may be possible to have one hiera/lookup-context per node in memory if performance is bad using switching of the set of values used to determine the paths in the hierarchy. Maybe it is possible to make hiera switch between named (i.e. "perspective specific") caches in an effective way.

It seems like a design with one hierarchy for the plan perspective, and one for all node specific perspectives would be best, and if override of node perspective is needed in plan perspective, then that can be done manually in the plan's logic.

**Comment by adreyer** [comment]
Without interpolations I'm not sure there is much value in exposing hiera instead of just loading data from a specific source or accepting it as a plan parameter(to allow users to inject their own sources). The new `resolve_reference` method should allow you to load encrypted values directly in the plan without trying to fit them into inventory.

We explicitly removed `$facts` from the scope of a plan and I don't think supporting hierarchies based on the facts of the controller is particularly useful. 
How would you like to set values for interpolation in the plan hierarchy?

**Comment by magnuslarsen** [comment]
I use Bolt in conjunction with Puppet's [control-repo](https://github.com/puppetlabs/control-repo) - meaning, a lot of my options are stored in hiera.

I have a plan, with multiple tasks, that need access to an internal API, with a username and password, that is already stored in heira. 
I want heira to be the single source of truth--e.g. I don't want to specify it any other place, since it would leave maintenance overhead, that _should_ not be there.

In my plan, I basically want to have this:
```puppet
plan base::patch (
  TargetSpec $nodes,
  String     $api_username = lookup('profile::monitoring::api_username', String, 'first', 'admin'),
  String     $api_password = lookup('profile::monitoring::api_password', String, 'first', 'wrong_password'),
) {
  [...]
}
```

**Comment by stowill** [comment]
I'm looking for similar functionality but from within the inventory.yaml file so usernames/passwords for targets can extracted from hiera data in the control repo before a plan even starts.

**Comment by nmaludy** [comment]
+1

**Comment by pillarsdotnet** [comment]
I wanted to look up a password stored in a hiera `.eyaml` file, and had to resort to this monstrosity:
```
$puppet_master = puppetdb_query(
  'resources[certname] { type = "Class" and title = "Puppet_enterprise::Profile::Master" }'
).map |$r| {
  $r['certname']
}
$val = run_command("/opt/puppetlabs/bin/puppet lookup ${key}", $puppet_master).first.value['stdout']
```

**Comment by ripienaar** [comment]
This work - specifically https://tickets.puppetlabs.com/browse/PUP-10397 - causes this simple usage of the Puppet::Pal package to fail

```
Puppet::Pal.in_tmp_environment("test", :modulepath => ["/tmp/puppet/modules"], :facts => facts) do |env|
  env.with_script_compiler do |compiler|
    compiler.evaluate_string("notice $facts")
  end
end
```

The Pal documentation has no hints of this happening :

https://github.com/puppetlabs/puppet/blob/464591cfe58dd18a874590dd8e973f8ba6fbc555/lib/puppet/pal/pal_impl.rb#L201-L210

This seems to violate semver rules.
