### ISSUE TITLE
Convert plugins that generate targets to use ruby_plugin_helper

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1404]
## Use Case
With the addition of the [ruby_plugin_helper](https://github.com/puppetlabs/puppetlabs-ruby_plugin_helper/pull/1) we should convert plugins that generate targets with ruby tasks to use the helper.

## Additional Context
We should merge in the outstanding [pull request](https://github.com/puppetlabs/puppetlabs-ruby_plugin_helper/pull/1) and base the work of converting the plugin modules on the master branch (without cutting a release until everything has been converted).

**Comment by lucywyman** [comment]
I don't think we should close this until we've released the updated modules and updated the Puppetfile in Bolt to pull them in - maybe you meant to close #1408 ?
