### ISSUE TITLE
Convert Terraform plugin to use helper

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1405]
## Use Case
The Terraform plugin should use the ruby plugin helper library. We should wait to release this until other plugins are converted

## Additional Context
With the addition of the plans/tasks in GH-1360 https://github.com/puppetlabs/puppetlabs-terraform/pull/4 the plan/task parameters map to terraform CLI options. The resolve_reference task uses `statefile` for `state`, we should update it to match the CLI and roll that breaking change into the `target_mapping` breaking change.

**Comment by donoghuc** [comment]
$ terraform state show --help
Usage: terraform state show [options] ADDRESS

  Shows the attributes of a resource in the Terraform state.

  This command shows the attributes of a single resource in the Terraform
  state. The address argument must be used to specify a single resource.
  You can view the list of available resources with "terraform state list".

Options:

  -state=statefile    Path to a Terraform state file to use to look
                      up Terraform-managed resources. By default it will
                      use the state "terraform.tfstate" if it exists.

**Comment by beechtom** [comment]
PR: https://github.com/puppetlabs/puppetlabs-terraform/pull/6

**Comment by donoghuc** [comment]
Closed by https://github.com/puppetlabs/puppetlabs-terraform/pull/6
