### ISSUE TITLE
Convert azure inventory to use ruby plugin helper

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1406]
## Use Case
Convert the azure_inventory plugin to use the ruby plugin helper. Don't release until all plugins are converted.

**Comment by beechtom** [comment]
The Azure plugin does not currently allow for target mapping. Instead, it assigns the name/uri of a target from predetermined fields and does not allow for config to be set with dynamic values. Do we want to maintain this behavior or add the ability to map data similar to the other inventory plugins?

**Comment by lucywyman** [comment]
Given our analytics show no one is using the Azure plugin I think we should wait until we get feedback that this is wanted before doing the work.

**Comment by donoghuc** [comment]
I'm not arguing that we should update this, but we do have to take in to account that due to a bug we only started collecting analytics for azure starting with 1.32.0 (release oct 3). There appear to be roughly 2x more downloads of azure_inventory than terraform.
