### ISSUE TITLE
Create `remove_from_group` function

### ISSUE THREAD

**Issue by Serverislife** [puppetlabs/bolt#1418]
## Use Case
Example: I have a group that I define into a variable $hosts using the get_targets function. I want to be able to do something that could attempt to ping, nslookup, whatever on the members of $hosts, and remove the non-responsive hosts from that group.

## Describe the Solution You Would Like
It could be something such as:
```
run_command(
  'uptime',
  $unresponsives,
  '_remove_from_group' => true,
)
``` 
^ that would remove the hosts that fail the command from the group.

## Describe Alternatives You've Considered
I haven't considered many alternatives, maybe managing an array of hosts from the group within the plan.

## Additional Context
Will upload as I gather examples.

## Solution
* We should add a `remove_from_group` function that takes a single target and a group name and removes the target from the group
* If the target is not in the group it should succeed
* If the group is `'all'` it should fail
* If you try to remove a target from a group that does not exist it should fail
* The function should remove the target from all children of the group. It should not remove from the parent of the group. If you remove from a child group and the target is not independently defined in the parent group, then it should also not be available in the parent group (ie don't move a target into the parent group).

**Comment by adreyer** [comment]
I don't think `_remove_from_group` is feasible since the TargetSpec passed in may or may not be a group. I do think `_remove_from_inventory_on_failure` could work so that the failing targets can be ignored for the rest of the plan.

I think it's much easier to add a complement to `add_to_group` that could be used like
```
$result = run_command(uptime, my_group)
$result.error_set.targets.each |$t| { remove_from_group($t, my_group) }
run_command(next_command, my_group) # does not target the failing nodes.
```
