### ISSUE TITLE
Hardcoded default Windows paths should not be used.

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1427]
Windows can redirect folder/have a different system drive than `C:\ProgramData`

e.g.

https://github.com/puppetlabs/bolt/blob/871e92d52dca54eedb3d5f87900cc054dcb9f7fd/lib/bolt/puppetdb/config.rb#L13

https://github.com/puppetlabs/bolt/blob/871e92d52dca54eedb3d5f87900cc054dcb9f7fd/lib/bolt/puppetdb/config.rb#L18

Instead Bolt should be using either Environment Variables (e.g. `ALLUSERSPROFILE`) or API calls to get the known shell folders

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb776911(v%3Dvs.85)

https://docs.microsoft.com/en-au/windows/win32/shell/knownfolderid?redirectedfrom=MSDN

Also, Bolt should be using the standard Windows locations for user configuration. storing files in dot-folder (`~/.puppetlabs`) causes issues in (typically enterprise) situations which use folder redirection, roaming profiles, or Remote Desktop services.

e.g. https://github.com/puppetlabs/bolt/blob/871e92d52dca54eedb3d5f87900cc054dcb9f7fd/lib/bolt/puppetdb/config.rb#L10-L11

Application data should be stored in `%LOCALAPPDATA%` for settings that should not roam across computers, and `%APPDATA%` for settings that should

**Comment by lucywyman** [comment]
> Also, Bolt should be using the standard Windows locations for user configuration. storing files in dot-folder (~/.puppetlabs) causes issues in (typically enterprise) situations which use folder redirection, roaming profiles, or Remote Desktop services.

I think it's totally fine to do this for puppetdb config, but changing the default Bolt project directory (`~/.puppetlabs`) would be a breaking change. Just wanted it noted that we're only making this change for puppetdb config.
