### ISSUE TITLE
CLI help text should be more consistent with other Puppet tools

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1441]
## Use Case
The CLI help text for Bolt should be updated to be more consistent with the formatting and content of other Puppet CLI tools like `r10k` and `pdk`. Currently, the way Bolt displays available subcommands and actions is inconsistent with these other tools, and also has some inconsistency in how it displays information for its own commands.

Updated CLI help text would help improve the readability of the help text and make it clearer what different subcommands and actions are available and what they do.

## Describe the Solution You Would Like
Update the help text to be more consistent with other Puppet tools like `r10k` and `pdk`. Help text should have the *name* of the command, *usage* of the command, any available *subcommands or actions*, an *example* of how to use the command, and any available *options*.

**r10k help text**
```
NAME
    r10k - Killer robot powered Puppet environment deployment

USAGE
    r10k <subcommand> [options]

DESCRIPTION
    r10k is a suite of commands to help deploy and manage puppet code for
    complex environments.

COMMANDS
    deploy         Puppet dynamic environment deployment
    help           show help
    puppetfile     Perform operations on a Puppetfile
    version        Print the version of r10k

OPTIONS
    ...
```

**Proposed Bolt help text**
```
NAME
    bolt

USAGE
    bolt <subcommand> [action] [options]

DESCRIPTION
    Bolt is an orchestration tool that automates the manual work it takes to maintain
    your infrastructure.

SUBCOMMANDS
    apply                  Apply Puppet manifest code
    command                Run a command remotely
    file                   Upload a local file or directory
    group                  Show the list of groups in the inventory
    inventory              Show the list of targets an action would run on
    plan                   Convert, show, and run Bolt plans
    project                Create and migrate Bolt projects
    puppetfile             Install and list modules
    script                 Upload a local script and run it remotely
    secret                 Create encryption keys and encrypt and decrypt values
    task                   Show and run Bolt tasks

GLOBAL OPTIONS
    ...
```

**Comment by lucywyman** [comment]
It is consistent with `puppet` help text though. I don't strongly care, but I don't think this is an important thing for us to work on.
