### ISSUE TITLE
Add 'Transports' reference page

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1462]
## Describe the Change You Would Like
Currently, transport configuration options are listed on the [Bolt configuration options](https://puppet.com/docs/bolt/latest/bolt_configuration_options.html) page with non-transport configuration options. This can make it difficult to know where to look in the docs for transport configuration options.

We should separate out these options into a separate reference page called 'Transports'. It should include options for each of the transports available:
- [ ] SSH / OpenSSH
- [ ] WinRM
- [ ] local
- [ ] remote
- [ ] docker
- [ ] pcp

## Questions

* Should each transport have its own dedicated reference page under a 'Transports' heading, or should they all be on a single page with their own sections?

**Comment by lucywyman** [comment]
I think we can close this?
