### ISSUE TITLE
Add `Task metadata` reference page

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1463]
## Describe the Change You Would Like
Currently, the available options for task metadata files are buried deep in the [Writing tasks](https://puppet.com/docs/bolt/latest/writing_tasks.html) page. This information should be pulled out into its own reference page.

The reference page should have the following:
- [x] A list of options for the metadata file
- [x] A list of data types available to the metadata file
- [x] Examples of a metadata file

**Comment by hestonhoffman** [comment]
@beechtom Is this something that can be generated?

**Comment by lucywyman** [comment]
Hm, I think https://puppet.com/docs/bolt/latest/writing_tasks.html#task-metadata-fields has been improved since this was created - does this still need a separate page, or can we close this?
