### ISSUE TITLE
Add 'Glossary' page

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1465]
## Describe the Change You Would Like

Bolt should have a glossary of terms used in the Bolt documentation (e.g. target, plan, task, etc).

## Questions

* Should terms have links to relevant pages? For example, an entry for `task` might link to documentation for writing and using tasks.
* What are the terms we want to list?

**Comment by hestonhoffman** [comment]
Example of one of our other glossaries: https://puppet.com/docs/puppet/latest/glossary.html

**Comment by hestonhoffman** [comment]
Some terms (in no particular order):
- Bolt controller
- Target
- module
- modulepath
- project
- inventory.yaml / inventory file
- bolt-project.yaml / bolt project file
- plan
- task
- apply
- transport
- TargetSpec
