### ISSUE TITLE
Upgrading Bolt on MacOS causes thread sleep error

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1478]
## Describe the Bug
When installing Bolt on MacOS it doesn't reliably cleanup old files from old version of bolt that are on the system. This has recently been causing errors such as `5 threads, 5 sleeps current:0x00007f96d2ef5210 main thread:0x00007f96cd705890
* #<Thread:0x00007f96ce869c98 sleep_forever>`. We should find a way to cleanup old Bolt version before installing new ones.

## Expected Behavior
Installling a new version of Bolt should work.

## Solution
* This should include a post-install script to remove versions of Bolt older than the one that was just installed. This may or may not solve the actual issue, depending on whether the issue is with old versions of Bolt or Bolt dependencies.

**Comment by nicklewis** [comment]
It does not appear that simply upgrading from one version of Bolt to another will cause this issue. So I'm not sure whether the fix we've described is appropriate/necessary. We may need more information about the scenarios in which this happens.

**Comment by npwalker** [comment]
I upgrade bolt all the time via brew and don't have any issues.  Does this issue apply to brew?  

Has anyone seen it since it was reported?

**Comment by nicklewis** [comment]
We haven't managed to reproduce it but it's come up a couple of times. Not for a while though. I think this issue mainly serves to have a landing spot for anyone who runs into in the future and can give us more information. It should be able to serve that purpose equally well closed though.

**Comment by hestonhoffman** [comment]
This came up yesterday. User had upgraded to 2.18 using brew.

**Comment by lucywyman** [comment]
A user ran into this on Windows 10 with Bolt 3.4.0 https://github.com/puppetlabs/bolt/issues/2739
