### ISSUE TITLE
Running scripts which require parameters starting with hyphen(s)

### ISSUE THREAD

**Issue by dkseschneider** [puppetlabs/bolt#1485]
When using the `script run` command, I can't find a way to pass parameters to the script which begin with one or more hyphens. It seems to be ambiguous as to whether the parameters are meant for bolt or the script. Here is an example:

```
root@machine:/# bolt script run awesome.py --script-param value --targets mynode
Unknown argument '--script-param'
```

Docker avoids this ambiguity by putting the Docker options ahead of the ordered parameters. Re-written this way, the same command would be structured as `bolt script run [options] <script> [arguments]`. Here is an example:

```
root@machine:/# bolt script run --targets mynode awesome.py --script-param value
```

**Comment by lucywyman** [comment]
This is the behavior of the [OptParse permute method](https://ruby-doc.org/stdlib-2.6.3/libdoc/optparse/rdoc/OptionParser.html#method-i-permute), and I'm not sure there's a great workaround for it. We don't know the name of the script ahead of time, so splitting on the script name and only permuting Bolt arguments is theoretically possible but seems like it could have weird edge cases. I think our best bet would be to have an explicit "param divider" to split the command on and parse the right side as arguments to the script:
```
bolt script run awesome.py special-sigil --script-param value
```
[Relevant stackoverflow](https://stackoverflow.com/questions/3642331/can-optionparser-skip-unknown-options-to-be-processed-later-in-a-ruby-program/40434335)

**Comment by dkseschneider** [comment]
My only idea is likely a terrible one. You could denote per-argument with a special character to denote that it's not a bolt argument. Bolt would need to remove the character before it's passed downstream to the node. Example where I'm assuming caret is the special character:

```
bolt script run awesome.py ^--script-argument value --targets mynode
```

This of course creates the issue of needing to handle for when the caret is intended to be the first value. You would need to include it twice, the second instance being part of the argument. This is probably a messier solution than the one @lucywyman proposed. Ultimately I think Docker's solution is the best, but would require breaking changes to bolt to implement.

**Comment by lucywyman** [comment]
Update: OptParse already supports this with `--` as the sigil, so:
```
bolt script run -t targets awesome.py -- --script-args
```
Should work. You just have to make sure that Bolt arguments (like `-t`) come *before* the script name, then the script name, then `--` and any args you want to pass to the script; order matters there.

Let me know if that doesn't work for any reason! If it does feel free to close this issue :)

**Comment by dkseschneider** [comment]
You are correct! Thank you for looking into this. It's greatly appreciated.

@lucywyman Should this be documented before the issue is closed? Or do you feel that this common enough knowledge?

**Comment by lucywyman** [comment]
Good idea! https://github.com/puppetlabs/bolt/pull/1489
