### ISSUE TITLE
Support run-as for WinRM nodes

### ISSUE THREAD

**Issue by jfunnell** [puppetlabs/bolt#1488]
## Use Case
At my work, we need to run certain commands as a particular user -- this includes things like installers using DPAPI, and MSSQL queries. Due to WinRM limitations none of this works unless you elevate the shell using runas.
More details here: https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#limitations

## Describe the Solution You Would Like
Invoke runas after connecting to a machine with winrm.
Ansible does (and they explain why): https://docs.ansible.com/ansible/latest/user_guide/become.html#become-and-windows
I guess it might be possible to use the runas 'verb': https://github.com/lukesampson/psutils/blob/master/sudo.ps1

## Describe Alternatives You've Considered
Ansible :/
Or maybe trying to run runas from my modules could work? Seems like quite a minefield though.

**Comment by lucywyman** [comment]
While we don't plan to support a `run-as` option for the WinRM transport, we explain why and document workarounds here https://puppet.com/docs/bolt/latest/privilege_escalation.html#escalating-privilege-over-winrm

Thanks for raising this! Hope the doc at least illuminates why we don't have `run-as` for WinRM, and maybe helps with your case if it's still relevant.
