### ISSUE TITLE
no environment variable instead of "null" string value for an unset variable in a shell task

### ISSUE THREAD

**Issue by dionysius** [puppetlabs/bolt#1498]
## Use Case

A) The use of (optional) parameters combined with shell scripts are not intuitive and unexpected in their behaviour *if you haven't read the documentation* and you go with *what is usually the guideline in my interpreter*. The current behaviour ***is explicitly documented***, so this can't be a bug, but can still be a design flaw, and a change here ***would thus be an api change***. The big plus for bolt is it's typed interface for use with plans and tasks which improves the stability and expectation of behaviour of the scripts since you want to rely on that.

B) Someone wants to use the string "null" and differentiate that from not providing the variable or unset

C) Not an actual case, but a warning: Changes might affect other interpreters - is a change still correct/useful/expectable for those interpreters? Again, this might lead to an api change to consider when the right time would be for that change.

With an optional parameter, there are 4 possibilities to consider (actually 3, but I'd like to include a provided *typed null* value as well)
1. parameter is not provided
2. parameter is provided but unset/null/nil
3. parameter is typed and *zeroed* (set *zero*, e.g. "" for string, 0 for int, false for bool, etc.)
4. parameter is typed and *valued* (set *non-zero*, e.g. "foo" for string, 5 for int, true for bool, etc.)

In shell, we have only 2 "possibilities":
a. variable does not exist
b. variable exists, is typed string and has a value
  - typed string is implicit because of the environment variable interface, someone could force a type within the script, but from outside, that's all we got.

There is also the possibility to include that case but it is implementation biased:
c. variable exists, is typed string and has explicitly the zero-value of the actual expected type
  - again, typed string is implicit because of the environment variable interface

## Describe the Solution You Would Like

Given the options we have:

- I would expect 1. and 2. to be the same and resulting to a.
- I would expect 3. and 4. to be the same and resulting to b.

## Describe Alternatives You've Considered

You can now combine any combination you want, the question is only where and how you allow discrepancies or differentiations.

The current implementation actually provides 3 distinctive possibilities (where 2. resulting to "null" string which conflicts with case B), but that is the reason for this request: It's not worth (imo, open for discussion) and not intuitive (think converting shell scripts to bolt tasks).

## Additional Context

I think this has not a lot of priority by its own, except the community and the users stumble on that often (give this issue a thumbs-up).

The part where "null" is documented: https://github.com/puppetlabs/bolt/pull/888/files#diff-446c800711bc10fdc0e4d69fbe4d69cbR523

Initial discussion on slack: https://puppetcommunity.slack.com/archives/C7GP57T50/p1576593079064800

## Example

`tasks/test.sh`
```bash
#!/bin/bash

echo -n 'variable $PT_test '

if [[ -v PT_test ]]; then
    echo -n "exists "
else
    echo -n "does not exist "
fi

echo "and has the value: $PT_test"
```

`tasks/test.json`
```json
{
  "parameters": {
    "test": {
      "type": "Optional[Integer]"
    }
  }
}
```

`plans/test.pp`
```puppet
plan xyz::test() {
  run_task('xyz::test', 'localhost')
  run_task('xyz::test', 'localhost', {"test"=>42})
  run_task('xyz::test', 'localhost', {"test"=>undef})
  run_task('xyz::test', 'localhost', {"test"=>"xy"})
}
```

output:
```cmd
# Starting: plan and task and such are ommited...
variable $PT_test does not exist and has the value:
variable $PT_test exists and has the value: 42
variable $PT_test exists and has the value: null
{ ... bolt/pal-error ... Task xyz::test: parameter 'test' expects a value of type Undef or Integer, got String ... }
```

**Comment by adreyer** [comment]
We're not planning to make breaking changes to the task spec anytime soon. I think this is a reasonable idea but will have to wait until we're ready to release version 2 of the task spec.
