### ISSUE TITLE
Support Win32-OpenSSH ssh-agent

### ISSUE THREAD

**Issue by jfastnacht** [puppetlabs/bolt#1534]
## Use Case

When I tried to get Bolt running with an SSH agent I realized that PuTTY Pageant is hardcoded as the ssh-agent solution for Windows OS and I couldn't figure out how to change that.

## Describe the Solution You Would Like

I want to use the Win32-OpenSSH ssh-agent instead of PuTTY Pageant on Windows 10.

## Describe Alternatives You've Considered

Using the key directly, but that fails with: `Failed to connect to 185.170.115.174: the given identity is known, but the private key could not be loaded: OpenSSL::PKey::PKeyError (Could not parse PKey: no start line)` (see https://www.reddit.com/r/Puppet/comments/ccsiag/puppet_bolt_on_windows_to_control_linux_host/)

I will use Pageant until it's possible to use Win32-OpenSSH ssh-agent, so it's rather an annoyance to have Pageant running just for Bolt.

## Additional Context

* Win32-OpenSSH https://github.com/PowerShell/Win32-OpenSSH

**Comment by adreyer** [comment]
This should be implemented in net::ssh if it's done. I don't think we'll prioritize adding that in the near future but if net::ssh implements it we'll bump our versions.
