### ISSUE TITLE
Crystal implementation

### ISSUE THREAD

**Issue by renich** [puppetlabs/bolt#1545]
## Use Case
The slowness is unbearrable! Especially when there are languages like crystal around: https://crystal-lang.org/

You're just starting this project and you could easily try and implement it in crystal. 

## Describe the Solution You Would Like
If you did the crystal port, the binary would be super fast. Also, parallelism wouldn't be an issue. 

## Additional Context
You have c-bindings and all. In fact, there's a libssh shards already: https://github.com/spider-gazelle/ssh2.cr

**Comment by MikaelSmith** [comment]
While the idea's interesting, Bolt makes extensive use of http://github.com/puppetlabs/puppet. Reimplementing Puppet in Crystal doesn't seem likely.

**Comment by renich** [comment]
Too bad. Just consider this sideckiq implementation: https://github.com/mperham/sidekiq.cr
Seems pretty impressive if you ask me. 

Not bothering you with this anymore. Just wanted to present that to you.
