### ISSUE TITLE
Spike: Ability to hide "private" plans from UI

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1549]
## Use Case
I want to hide some plans when listing plans for `bolt plan show`.

## Describe the Solution You Would Like
Tasks can be hidden from `bolt task show` with a `private` key in the task metadata. A similar setting should be configurable for plans. Perhaps as a Yard tag in puppet strings documentation similar to documenting plan parameters:

```
# @summary
#   This plan will be hidden from UI
# 
# @private true
#
# @param targets 
#   The target to run on.
#
# @example Run private plan
#   run_plan(private, $targets)
#
plan private(TargetSpec $targets) { }
```

## Additional Context
This would be useful for hiding packaged module content in PE.

**Comment by adreyer** [comment]
With the addition of `bolt-project.yaml` we have a workaround for some of the use cases around this. If a project author wants to limit which plans appear in the UI they can add a `bolt-project.yaml` file and whitelist public plans for the project under the `plans` key.
