### ISSUE TITLE
Allow usage of .yml file extension for config files

### ISSUE THREAD

**Issue by tspeigner** [puppetlabs/bolt#1553]
## Use Case
Currently the bolt configuration file and inventory files require the extension of yaml. The .yml extension is a valid YAML file extension. 

## Describe the Solution You Would Like
To have bolt look for both .yaml and .yml files.

**Comment by npwalker** [comment]
@tspeigner supporting both introduces edge cases about what to do if a file with both extensions exist.  Since this has been open for a few months and other users aren't indicating this is a priority I'm going to consider this closed/won't fix for now.
