### ISSUE TITLE
Get started fast with using any existing module

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/bolt#1574]
## Use Case

As a content consumer, I want a one-line command to run that lets me quickly and easily get started with using ANY module.

Today, using a module of any sophistication commonly requires pulling in other dependent modules. This means that to get started with using these kinds of modules, it is necessary to create a Bolt project, enumerate the target module AND its dependencies in a Puppetfile, then run `bolt puppetfile install`. You can't get started using your original target module until after you've done all of this preparatory work.

## Describe the Solution You Would Like

A project init command which allows you to specify a seed module to create a new project directory around.

```
bolt project init [--module=my-forgemodule] <project-name>
```

The command should create a new Bolt project directory <project-name>. For each `--module` specified, the new project should list that module in the Puppetfile along with a point-in-time evaluated set of other module dependencies, and perform work equivalent to `bolt puppetfile install`. When `bolt project init` completes, the project directory should be immediately usable. Subject to additional user-specified `bolt.yaml` or `inventory.yaml` configuration.

This command should leave an empty `bolt.yaml` in the directory so that bolt will detect it as a project.

#### What should the command do if a Puppetfile already exists? 
It should error and do nothing

#### What should the behavior be if a `bolt.yaml` exists? 
We should create a Puppetfile, and not interact with the `bolt.yaml`.

The command should not change existing artifacts, and if it is about to it should error.

**Comment by adreyer** [comment]
bikeshed: I lean towards initilizing the current directory as a project instead of creating a new subdirectory.

**Comment by reidmv** [comment]
Probably matters what the command actually is, wrt this. E.g. `git init` uses cwd, so `bolt project init` is subject to that language association. If we called it instead `bolt new project`, then I think it'd be more aligned with `pdk new module` which creates a new directory.

**Comment by adreyer** [comment]
We should try to use the puppetfile-resolver library for this.

https://github.com/lingua-pupuli/puppetfile-resolver
