### ISSUE TITLE
CI System Badges point to wrong location

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/bolt#1581]
The coloured badges on the README display the status of the latest build, which is normally the last PR to be run. This should really be master branch instead.  Otherwise it looks like the project can be completely broken, when it's not.

e.g. Even though master is green.

![image](https://user-images.githubusercontent.com/5819622/73709160-4dac4700-473b-11ea-847f-a220185c8561.png)

**Comment by beechtom** [comment]
Thanks for pointing out this issue @glennsarti !
