### ISSUE TITLE
The task puppet_agent::install doesn't configure apt to run in unattended mode

### ISSUE THREAD

**Issue by gfa** [puppetlabs/bolt#1593]
## Describe the Bug
the task puppet_agent::install doesn't configure apt to run in unattended mode

## Expected Behavior
puppet should set DEBIAN_FRONTEND=noninteractive so dpkg doesn't stop while installing files
This happens to me on systems that had 

## Steps to Reproduce
I manually manage /etc/apt/sources.list.d/puppet.list, the package `puppet-release` provides that file too so dpkg asks what to do when puppet_agent::install runs

this is bolt output at debug loglevel

```
Executing: PT_stop_service=true PT__boltdir=/builds/gfa/puppet-bolt PT__task=puppet_agent::install PT__installdir=/tmp/b794348f-9fb6-494a-9835-ff3d56bee756 /tmp/b794348f-9fb6-494a-9835-ff3d56bee756/puppet_agent/tasks/install_shell.sh
stdout: 18:39:38 +0100 INFO: Version parameter not defined, assuming latest
stdout: 18:39:38 +0100 INFO: Downloading Puppet latest for Debian...
stdout: 18:39:38 +0100 INFO: Debian platform! Lets get you a DEB...
stdout: 18:39:38 +0100 INFO: Downloading http://apt.puppet.com/puppet-release-buster.deb
stdout: 18:39:38 +0100 INFO:   to file /tmp/install.sh.804.51035/puppet-release-buster.deb
stdout: 18:39:38 +0100 INFO: Trying wget...
stdout: 18:39:39 +0100 INFO: installing puppetlabs apt repo with dpkg...
stdout: 18:39:39 +0100 INFO: Version 6.12.0 detected...
stdout: 18:39:39 +0100 INFO: Collection upgrade detected, replacing puppet6-release
stderr: dpkg: warning: ignoring request to remove puppet6-release which isn't installed
stdout: (Reading database ... 84782 files and directories currently installed.)
stdout: Preparing to unpack .../puppet-release-buster.deb ...
stdout: Unpacking puppet-release (1.0.0-7buster) over (1.0.0-7buster) ...
stdout: Setting up puppet-release (1.0.0-7buster) ...
stderr: 
stderr: Configuration file '/etc/apt/sources.list.d/puppet.list'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** puppet.list (Y/I/N/O/D/Z) [default=N] ?
```

## Environment
 - 1.48.0 installed from gem
 - Debian 10

## Workaround
`bolt  command run 'rm -f /etc/apt/sources.list.d/puppet.list' --targets all` 

thanks!

## Solution

Look into how Puppet handles non-interactive installation. Consider using `DEBIAN_FRONTEND=noninteractive`.

**Comment by beechtom** [comment]
@gfa Can you clarify what your situation is? We have a patch in the works but want to make sure it's addressing the correct issue.

1. You have previously installed the `puppet-release` package and edited the `puppet.list` config file
1. You manually created the `puppet.list` config file and later tried installing the `puppet-release` package for the first time

https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/472 has a fix for the first scenario but would not apply to the second.

**Comment by gfa** [comment]
Hi @beechtom 

I (bolt did for me long ago) installed `puppet-release` and later edited (again, puppet bolt as part of my provisioning process) `puppet.list` config file

so 1
