### ISSUE TITLE
it would be 'nice to have' ability to filter plans or tasks from the bolt show command

### ISSUE THREAD

**Issue by abuxton** [puppetlabs/bolt#1596]
## Use Case
When you start to develop larger projects with more active module dependencies the number of tasks exposed by `bolt task show` becomes rather verbose. 

## Describe the Solution You Would Like
Provide a `--filter` option followed by a string and use substring matching. Tasks should only be filtered by name.

Bolt should raise a helpful error if the string contains invalid task name characters.

## Describe Alternatives You've Considered
currently parse through Grep, but that means documenting Grep example and Get-ent for Powershell users unified approach from the CLI would be prefered.

## Additional Context
same functionality for `bolt plan show` would be an obvious consideration

**Comment by beechtom** [comment]
Closed by #1603
