### ISSUE TITLE
Ability to pass puppetfile

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/bolt#1612]
## Use Case
We our automating our system using Bolt and Terraform and have a need to pass the Puppetfile directly in a container and install into a particular directory. 

## Describe the Solution You Would Like
An additional flag to allow for path to Puppetfile during the `bolt puppetfile install` command

## Describe Alternatives You've Considered
We have considered moving the file to the `.bolt` directory but also run outside of containers and do not want to have a race condition where more than one job is trying to do that with different dependencies.

## Solution
Add a `--puppetfile` flag to the `bolt puppetfile install` command which accepts a path (relative or absolute) to a Puppetfile. The modules will be intsalled to whatever the current Boltdir is.

**Comment by beechtom** [comment]
Hi @cyberious, thanks for the suggestion!

Since Bolt runs in the context of a project directory, or a `boltdir`, a Puppetfile and installed modules are typically found within the `boltdir` as well.
