### ISSUE TITLE
BoltSpec::Run modifies the inventory.

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1614]
## Describe the Bug
When a user passes an inventory hash to BoltSpec::Run functions the version number is deleted from the original hash. This means that a version 2 inventory hash cannot be used to run two consecutive actions.  

## Expected Behavior
No objects passed to the `run_*` functions should be modified.

## Workaround

deep copy the hash before passing it to a run function or add the `version` key back in before each call.

**Comment by glennsarti** [comment]
Hit this today in puppet-strings testing 😢

**Comment by glennsarti** [comment]
Also affects `upload_file` too  😢😢😢😢😢
