### ISSUE TITLE
Sudo password prompt

### ISSUE THREAD

**Issue by zyronix** [puppetlabs/bolt#163]
Hi there,

I just tried out the latest version of bolt and really great to see the sudo support! Currently it only works if you supply the sudo password through the commandline interface. I prefer to also have a password prompt for the sudo password (the same as it is now for the ssh password). I guess it would only require a couple of extra lines of code.

Current lines of code for password
```
        opts.on('-p', '--password [PASSWORD]',
                'Password to authenticate with (Optional).',
                'Omit the value to prompt for the password.') do |password|
          if password.nil?
            STDOUT.print "Please enter your password: "
            results[:password] = STDIN.noecho(&:gets).chomp
            STDOUT.puts
          else
            results[:password] = password
          end
end
```
But this is not there at the sudo_password field:

```
        opts.on('--sudo-password [PASSWORD]',
                'Password for privilege escalation') do |password|
          options[:sudo_password] = password
end
```

This would really be great if this can also be implemented :)

**Comment by MikaelSmith** [comment]
That seems pretty straight-forward. I'll take a look at adding it.

**Comment by MikaelSmith** [comment]
And hit the wrong button.

**Comment by MikaelSmith** [comment]
Reproduced this, it just hangs if I pass `--sudo-password` without an argument and one is required.

**Comment by MikaelSmith** [comment]
It also seems to behave poorly if your user doesn't have sudoer access. Just hangs after the successful password. I'll see if I can do anything about that.

**Comment by zyronix** [comment]
Awesome, thanks and confirmed it to be working :D

**Comment by nicklewis** [comment]
Sounds like this is fixed! Please reopen if I'm mistaken.
