### ISSUE TITLE
Redirect broken doc links to current doc url pattern

### ISSUE THREAD

**Issue by pirtleshell** [puppetlabs/bolt#1654]
I am working through Puppet's Basic Learning Path course and noticed a broken docs link. It looks like the url pattern it links to is no longer used.

The link in question was to the "Writing Tasks" section of Bolt's documentation.

**Broken link**: `https://puppet.com/docs/bolt/0.x/writing_tasks.html`
**Fixed link**: `https://puppet.com/docs/bolt/latest/writing_tasks.html`

## Proposed fix
Redirect the `puppet.com/docs/bolt/0.x/` endpoint to `puppet.com/docs/bolt/latest/`.

**Comment by hestonhoffman** [comment]
Thanks @pirtleshell, this should be fixed now :)
