### ISSUE TITLE
wait_until_available function is failing on PCP/Orchestrator environment with Timed out error

### ISSUE THREAD

**Issue by sheenaajay** [puppetlabs/bolt#1666]
## Describe the Bug
wait_until_available function is failing on PCP/Orchestrator environment with Timed out error

## Expected Behavior
wait_until_available function should work on PCP/Orchestrator environment and keep retrying till the machine is back online.

## Steps to Reproduce
Written a simple plan which only contains the wait_until_available function
`
plan reboot::wait(
  TargetSpec $targets,
  Optional[String] $message = undef,
  Integer[1] $reboot_delay = 1,
  Integer[0] $disconnect_wait = 10,
  Integer[0] $reconnect_timeout = 180,
  Integer[0] $retry_interval = 1,
  Boolean    $fail_plan_on_errors = true,
) {
  $target_objects = get_targets($targets)
  ctrl::do_until() || {
  wait_until_available($target_objects, wait_time => $reconnect_timeout, retry_interval => $retry_interval)
  }
  }`

Called the plan on the PE master
puppet plan run reboot::wait --params '{"targets":["irate-expunging.delivery.puppetlabs.net"]}'

On the Agent issued the reboot command to make the node offline for sometime. (Agent is back online after some time)

But the plan throws the following error
`
Started on irate-expunging.delivery.puppetlabs.net ...
Failed on irate-expunging.delivery.puppetlabs.net
  Error: Timed out waiting for target: irate-expunging.delivery.puppetlabs.net

Job failed. 1 node failed, 0 nodes skipped, 0 nodes succeeded.
Duration: 3 min, 0 sec

|
{
    "msg": "Plan aborted: wait_until_available failed on 1 target",
    "kind": "bolt/plan-failure",
    "details": {
        "class": "Bolt::RunFailure"
    }
}
[root@frank-lunation ~]#
`

## Environment
PE master agent setup
PE master -centos-7-x86_64 (frank-lunation.delivery.puppetlabs.net)
Agents centos-7-,win-2016-x86_64 (irate-expunging.delivery.puppetlabs.net, fugual-marking.delivery.puppetlabs.net)
Code Manager is configured
bolt-1.45.0

Please let us know if you need any other information

This function is used in the reboot module and its failing
https://github.com/puppetlabs/puppetlabs-reboot/blob/master/plans/init.pp#L83

Any help will be greatly appreciated.

**Comment by lucywyman** [comment]
Hi @sheenaajay - this isn't a bug, it means that the agent you're trying to reboot isn't back online after the default timeout for the plan, which is exactly 3 minutes (180 seconds). You can set the `reconnect_timeout` parameter to more than 180 if you want the plan to wait longer for the target to be back online. See https://forge.puppet.com/puppetlabs/reboot/plans#plan_reboot for more info. I'm going to close this as I don't think it's a Bolt issue, but let us know if you still have trouble.

**Comment by sheenaajay** [comment]
@lucywyman Thank you Lucy for the quick response. Yeah tried different times but it throws the same error.`Started on irate-expunging.delivery.puppetlabs.net ...
Failed on irate-expunging.delivery.puppetlabs.net
  Error: Timed out waiting for target: irate-expunging.delivery.puppetlabs.net

Job failed. 1 node failed, 0 nodes skipped, 0 nodes succeeded.
Duration: 4 min, 10 sec

|
{
    "msg": "Plan aborted: wait_until_available failed on 1 target",
    "kind": "bolt/plan-failure",
    "details": {
        "class": "Bolt::RunFailure"
    }
}
[root@frank-lunation ~]#`

If I give sleep time of 40 seconds prior to calling wait_until_available (in this case the time for node to come back online)

wait_until_available function executed successfully.

`[root@frank-lunation ~]# puppet plan run reboot::wait --params '{"targets":["irate-expunging.delivery.puppetlabs.net"]}'
Starting plan job ...
New Plan Job ID: 41

Started wait_until_available
New job ID: 81
Nodes: 1

Started on irate-expunging.delivery.puppetlabs.net ...
Finished on node irate-expunging.delivery.puppetlabs.net

Job completed. 1/1 nodes succeeded.
Duration: 0 sec


{}`

Looks like within the functions its not able to connect to the node and check its availability status.
