### ISSUE TITLE
Cannot connect to NAS from Windows Server 2019 

### ISSUE THREAD

**Issue by nasu67** [puppetlabs/bolt#1667]
## Describe the Bug
I am using Bolt to run a Powershell script on some Windows Server 2012/2019 machines in another Windows domain. The script successfully finds backups on the machine that I would like to copy to a NAS share which is accessible from Windows Explorer on each machine. However, I am not able to copy files from the Windows Server 2019 machines due to some kind of access issue. 

## Expected Behavior
Should be able to use copy or robocopy to copy files from the Windows machines to the NAS share. 

## Steps to Reproduce
1. Run a Powershell script (or batch file) on a Windows Server 2019 target machine containing a command like `Test-Path -Path \\XX.XXX.XX.X\sd`
2. This returns False on the Windows Server 2019 machines but not on the 2012 ones.

## Environment
 - Bolt 2.1.0
 - Windows Server 2012/2109

## Additional Context
I have tried running a batch file instead of a Powershell script on the target machines and copying fails there as well.

**Comment by adreyer** [comment]
Can you run the command directly over winrm using the same credentials you're passing to bolt?

**Comment by adreyer** [comment]
closing due to lack of response
