### ISSUE TITLE
Access tags by name in aws_inventory plugin target_mapping

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1668]
## Use Case
Users expect to be able to access the values of EC2 instance tags - in particular the `Name` tag - when using the `aws_inventory` plugin. 

## Describe the Solution You Would Like
Munge the data for each EC2 instance so tags are structured as key value pairs in a Hash. Currently, the `tags` field is an array of maps, making it impossible to access the value for a specific tag unless you know which element in the array it is: `tags.0.value`. By munging the `tags` array into a hash, users can access tags by name: `tags.Name`.

## Describe Alternatives You've Considered
Indexing tags by order.

## Questions

What should the map of tags be called?

**Comment by adreyer** [comment]
https://github.com/puppetlabs/puppetlabs-aws_inventory/issues/8
