### ISSUE TITLE
Don't assume users have a homedir

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1671]
There are a number of paths in Bolt that assume the user running Bolt has a homedir, which isn't always the case when service accounts or other automation is running Bolt. This is especially problematic for directories that can't be configured by the user, such as the user-level config file `Pathname.new(File.expand_path(File.join('~', '.puppetlabs', 'etc', 'bolt', 'bolt.yaml')))`.

Additional info:
On Windows, Ruby tries HOME, HOMEDRIVE, and USERPROFILE from the environment in that order, before then trying to query the system for something home-y from the SHGetSpecialFolderLocation API (CSIDL_PROFILE or CSIDL_PERSONAL.) 

Questions:
* Should we validate that `~` is valid before trying to load and fall back to something else? Or should we just catch the `expand_path` error and not load that config?

**Comment by beechtom** [comment]
Here's a similar issue in `sensu-puppet`: https://github.com/sensu/sensu-puppet/pull/1226/files
It might be worth exploring something similar as a fix.

**Comment by adreyer** [comment]
For now we should just catch errors trying to read config files and not read that config. 

Should we print an error, warning message or just debug?
