### ISSUE TITLE
bolt puppetfile install doesn't update git branch

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/bolt#1680]
Checked with bolt version 2.2.0
If a module is defined using git, working directory is not getting updated using `bolt puppetfile install`:

```
mod 'peadm',
  :git    => 'https://github.com/puppetlabs/puppetlabs-peadm.git',
  :branch => 'master'

$ git status
HEAD detached at deea897
```

**Comment by donoghuc** [comment]
Does it work if the URL is `https://github.com/puppetlabs/puppetlabs-peadm` (drop the `.git`)?

**Comment by vchepkov** [comment]
No, I don't think there is a difference. But what I noticed, maybe it's just a 'cosmetic' issue.
bolt creates a detached head, even though it does point to the same commit as master:
```
$ git branch -avv|grep deea897
* (HEAD detached at deea897)  deea897 Merge pull request #75 from puppetlabs/GH-71
  master                      deea897 [origin/master] Merge pull request #75 from puppetlabs/GH-71
  remotes/cache/master        deea897 Merge pull request #75 from puppetlabs/GH-71
  remotes/origin/master       deea897 Merge pull request #75 from puppetlabs/GH-71
$ git --version
git version 2.25.2
```

**Comment by lucywyman** [comment]
Yeah, I think in R10K all git refs have to be resolved to a commit https://github.com/puppetlabs/r10k/blob/master/lib/r10k/git/shellgit/base_repository.rb#L17 I imagine that's so it can be cached and updated when necessary, instead of getting pulled down every time?

**Comment by adreyer** [comment]
Yeah you're not intended to modify these checkouts. For the time being I think this is not a bug but a possible new feature to leave the modules in a more flexible state to modify and push back up.
