### ISSUE TITLE
Warn user when input_method is missing in task metadata.

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/bolt#1694]
## Use Case

Spent hours trying to figure out why my task(s) wasn't working.

This has happened more than once.

At least warn the user that the input_method is missing.

## Describe the Solution You Would Like

Warn the user if the input_method is not defined.

## Describe Alternatives You've Considered

None.

**Comment by adreyer** [comment]
How did your task fail? The default is to use both environment variables and stdin when nothing is specified.
