### ISSUE TITLE
Error when applying on local.

### ISSUE THREAD

**Issue by jaklaassen** [puppetlabs/bolt#1713]
## Expected Behavior
On a non-trivial Puppet setup, my bolt apply runs are failing on localhost, with the following error:

[bolt_stacktrace.txt](https://github.com/puppetlabs/bolt/files/4434889/bolt_stacktrace.txt)

## Steps to Reproduce
1. Run `bolt apply`

## Environment
 - Version: 2.3.1
 - Platform: Ubuntu 18.04

## Additional Context
I believe I've tracked this down to incorrectly passing stdin to the local subshell. 

This fixed it for me, but I'm pretty new to Bolt so not sure if this is right: https://github.com/puppetlabs/bolt/pull/1714

**Comment by lucywyman** [comment]
Closed by #1702
