### ISSUE TITLE
Leave Temporary files on targets for debugging

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1729]
## Use Case
Debugging why a task won't work on a certain target is difficult if the task uses multiple files. In these cases it would be useful to have bolt leave the tmp directory it creates behind.

## Describe the Solution You Would Like
A `--no-cleanup` flag and `cleanup: false` transport config option that tells the bolt transport to not clean up temporary directories on the target. Bolt should log the path to the left behind directory at "warn" level.

## Additional Context
We may want to save environment variables or stdin but this is out of scope for this ticket.
The standard option parser behavior around cleanup/nocleanup should be fine

**Comment by beechtom** [comment]
Closed by #1762
