### ISSUE TITLE
Unable to install sql-server puppet module using bolt command

### ISSUE THREAD

**Issue by John12x** [puppetlabs/bolt#1731]
I'm new to bolt. I' trying to install sql-server module using `mod 'puppetlabs-sqlserver', '2.6.2'` in puppetfile. 

I have created `Puppetfile`  folder in path `C:\Users\User1\.puppetlabs\bolt` and created new text file puppetfile.txt with below command in it.

`mod 'puppetlabs-sqlserver', '2.6.2'`

when I run below command in powershell, 

`bolt puppetfile install`

I'm getting error as below

```
ruby.exe : [31mIs a directory @ rb_sysopen - C:/Users/user1/.puppetlabs/bolt/Puppetfile[0m
At C:\Program Files\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psm1:13 char:5
+     &$script:RUBY_DIR\bin\ruby -S -- $script:RUBY_DIR\bin\bolt ($args ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([31mIs a direc.../Puppetfile[0m:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
[0m
Failed to sync modules from C:/Users/user1/.puppetlabs/bolt/Puppetfile to C:/Users/user1/.puppetlabs/bolt/modules

```
How to resolve above issue

My requirement is I want to install SQL SERVER  and run any SQL SCRIPTS through bolt .

**Comment by beechtom** [comment]
Hi @John12x !

The Puppetfile is just a file with the name `Puppetfile` - no extension. It should not be a `Puppetfile` directory with a `puppetfile.txt` file in it.

The `puppetlabs-sqlserver` module also has two dependencies [listed here](https://forge.puppet.com/puppetlabs/sqlserver/dependencies). You'll need to include those in your Puppetfile as well.

Bolt has a command that should make this pretty simple. Assuming you don't have a Puppetfile in your project directory `C:/Users/user1/.puppetlabs/bolt`, you can run the following command to create the Puppetfile with the module and its dependencies and automatically install them:

```
bolt project init C:/Users/user1/.puppetlabs/bolt --modules puppetlabs-sqlserver
```

Let me know if that helps!

**Comment by John12x** [comment]
@beechtom Thanks for your reply. The solution you provided worked perfectly. I have one more query.

Actually, I'm following below article for SQL SERVER installation through bolt.

https://forge.puppet.com/puppetlabs/sqlserver/readme

```
sqlserver_instance{ 'MSSQLSERVER':
  source                  => 'E:/',
  features                => ['SQL'],
  security_mode           => 'SQL',
  sa_pwd                  => 'p@ssw0rd!!',
  sql_sysadmin_accounts   => ['myuser'],
  install_switches        => {
    'TCPENABLED'          => 1,
    'SQLBACKUPDIR'        => 'C:\\MSSQLSERVER\\backupdir',
    'SQLTEMPDBDIR'        => 'C:\\MSSQLSERVER\\tempdbdir',
    'INSTALLSQLDATADIR'   => 'C:\\MSSQLSERVER\\datadir',
    'INSTANCEDIR'         => 'C:\\Program Files\\Microsoft SQL Server',
    'INSTALLSHAREDDIR'    => 'C:\\Program Files\\Microsoft SQL Server',
    'INSTALLSHAREDWOWDIR' => 'C:\\Program Files (x86)\\Microsoft SQL Server',
  }
}

```
I'm trying to run above script in powershell but I'm getting errors as below

![image](https://user-images.githubusercontent.com/31477143/78980171-59293f00-7aeb-11ea-99ad-6bf286881960.png)

How to run them. Could you please suggest.

**Comment by beechtom** [comment]
@John12x Puppet has a [community Slack channel here](https://slack.puppet.com/) that would be better for troubleshooting things like this. Some channels to check out there would be #forge-modules and #bolt .
