### ISSUE TITLE
protect existing secret keys

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/bolt#1738]
## Use Case
Currently, `bolt secret createkeys` command overrides existing secret keys unconditionally and can lead to data loss if ran from wrong project directory.

## Describe the Solution You Would Like
command should fail if configured keys already exist. To provide existing option to override existing keys `--force`  should be used explicitly. This should turn into a `force` task parameter that gets passed to the createkeys plugin task. 

Tasks should return a standard error kind for this and the CLI should generate a helpful message telling the user to rerun with `--force` if they want to overwrite the existing keys.
The writing plugins docs should be updated to describe how to handle the force.

**Comment by adreyer** [comment]
The implementation of this should be a standard flag passed to the createkeys tasks that tells it whether to overwrite existing keys or error if they are present.
