### ISSUE TITLE
Recognize external contributions in CHANGELOG

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1749]
## Use Case
We should include a small note (Thank you Name!) to release notes in our Changelog that are contributed by external folks. We should use the users configured git name unless it isn't available, in which case we can fall back to the GitHub username. This should be part of the generate_changelog script, which will require getting the author for each commit, sending a request through Octokit for the associated username, checking if the user is on the Puppet org, and inserting the username.

**Comment by nmaludy** [comment]
This would be awesome!
