### ISSUE TITLE
I want to limit which parts of my project are displayed to users.

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1756]
## Use Case
When building a project especially one that consumes modules from the forge `bolt task show` and `bolt plan show` can get cluttered with content that is not important to the projects users. In cases where the author of a project is different from the user of a project, there may be content that isn't relevant to users that shouldn't be listed.

## Describe the Solution You Would Like
A `project.yaml` file that allows the project author to whitelist public content that should be displayed with `bolt * show`. 

## Describe Alternatives You've Considered
Using public and private at a module level. These methods are about the public API of a library rather than an application that will be handed to users.

## Questions
* Should the presence of `project.yaml` be enough to make a directory a project? Not yet
* Should `project_name` move to just `name` in `project.yaml`? Yes
* Bikeshed schema:
```
---
name: myproject
tasks:
  - facts
  - service::mytask
plans:
  - myplan::foo
```
* Do we need to provide options to expose all content? If there isn't a tasks key, show all available tasks. If there isn't a plans key, show all available plans.
* Should this just whitelist individual tasks/plans, or whole modules? For now, we should do individual content, eventually may be able to add `module::*` or something
* Does the whitelist inherently include builtin bolt content? No, that should also be listed.

This should be labelled as experimental.

**Comment by beechtom** [comment]
Another question that came up in channel that might be worth discussing: should `Bolt::Boltdir` be changed to `Bolt::Project`?
