### ISSUE TITLE
Support `bolt apply` pointed at a directory of manifests

### ISSUE THREAD

**Issue by leiocalyx** [puppetlabs/bolt#1765]
## Describe the Bug
Running ` bolt apply manifests/nodes/bastion1.pp <the rest of necessary arguments>` does not actually apply anything.

## Expected Behavior
I was under the assumption that you could reuse existing puppet manifests using bolt. 

bastion1.pp looks like this
```
node 'bastion1' {
    class { 'node_templates::bastion':
        avd                => 1,
        password_hash      => '[REDACTED]',
        ssh_listen_address => '[REDACTED]',
    }
}
```
bastion.pp looks something like
```
class node_templates::bastion(
    Integer[1, 2] $avd,
    String[98] $password_hash,
    Stdlib::IP::Address::V4::Nosubnet $ssh_listen_address
) {
    include stdlib
    include drive::disks
    include drive::logrotate
    include tuning
    include drive::authority::pam_alert
    include apt_auto

    user { 'admin':
        password   => $password_hash,
        home       => '/home/admin',
        managehome => true,
        shell      => '/bin/bash',
        groups     => [
            'adm',
            'sudo',
        ],
    }

<the rest of the manifest>
```

Since it worked fine when applying with puppet agent, I thought that bolt would be able to do the same, but agentless. 

## Steps to Reproduce
Not sure about this, but running a manifest that is not converted to a plan should probably reproduce it. 

## Environment
 - Version e.g. 1.23.0
 - Platform Ubuntu 18.04

## Additional Context
I couldn't find any documentation about the `bolt apply` command, just that it was added and tried it under the assumption that it just works. 
And it kind of does work, it just doesn't apply anything from the manifest and doesn't throw any errors.  
```
Starting: install puppet and gather facts on [REDACTED]
Finished: install puppet and gather facts with 0 failures in 5.09 sec
Starting: apply catalog on [REDACTED]
Started on [REDACTED]...
Finished on [REDACTED]:
  changed: 0, failed: 0, unchanged: 0 skipped: 0, noop: 0
Finished: apply catalog with 0 failures in 10.15 sec
Successful on 1 node: [REDACTED]
Ran on 1 node in 15.84 seconds
```
Am I missing something? Perhaps bolt needs some additional configuration?

**Comment by leiocalyx** [comment]
I've updated bolt to 2.6.0

Now I get an error, but It's rather cryptic:
```
Starting: apply catalog on <target ip>
Failed on <target ip>:
  Apply failed to compile for <target ip>: Could not find node statement with name 'default' or '<target ip>' on node <target ip>
Finished: apply catalog with 1 failure in 7.19 sec
Failed on 1 target: <target ip>
```

**Comment by nicklewis** [comment]
It looks like Bolt thinks the target's name is its IP, so it's not matching the `node` definition for its hostname. How have you defined the target in the Bolt inventory (if you have)?

**Comment by leiocalyx** [comment]
Okay, I've added `<target ip> bastion1` to my hosts file.
And with 
```
targets:
  - uri: bastion1
    config:
      transport: ssh
```
I can get `bolt apply manifests/nodes/bastion1.pp --targets bastion1 <the rest of necessary arguments>` to produce another error message:
```
Starting: apply catalog on bastion1
Failed on bastion1:
  Apply failed to compile for bastion1: Could not find declared class node_templates::bastion (file: manifests/nodes/bastion1.pp, line: 2, column: 5)
Finished: apply catalog with 1 failure in 8.29 sec
Failed on 1 target: bastion1
```
The class `node_templates::bastion` is defined in bastion.pp

The file structure looks like this and puppet has no problem with it:
manifests/
├── node_templates
│   ├── bastion.pp
├── nodes
│   ├── bastion1.pp
│   ├── bastion2.pp

Why doesn't bolt know where to look?

**Comment by nicklewis** [comment]
This directory corresponds to the `$manifest` setting in Puppet, which can either be a single file or a directory. Bolt currently only knows how to use a single main manifest, not a directory of manifests, and relies on the rest of the content being defined in modules. If your `node_templates` directory were a module called `node_templates` instead, then it would be able to find it.

Ideally, you would be able to run `bolt apply manifests --targets bastion1` and it would work, without having to specify the specific file that contains the node definition for that target. That would mirror how Puppet and specifically `puppet apply` work. But that's a feature that doesn't exist for Bolt yet...

**Comment by gucki** [comment]
I'm quite new to bold and just stumbled upon the same issue, and it'd definitely be great to have it!

My current workaround is to have a "deploy" plan, which takes care of choosing the nodes (actually they have to be classes now) to deploy:

    plan deploy(TargetSpec $targets) {
      $targets.apply_prep

      $apply_result = apply($targets) {
        case $trusted["certname"] {
          /^lb01(-\d+)?/: {
            $groups = ["lb01"]
            include nodes::lb01
          }
          /^bastion/: {
            $groups = ["some-group"]
            include nodes::bastion
          }
          /^dmz/: {
            $groups = ["secure", "dc01"]
            include nodes::dmz
          }
          default: {
            include Class["nodes::${node}"]
          }
        }
      }

      return $apply_result
    }

This way you can simply deploy with "bold run deploy -t ...".
