### ISSUE TITLE
Too Many Open Files Error

### ISSUE THREAD

**Issue by dshauver** [puppetlabs/bolt#1789]
## Describe the Bug
Executed `bolt command run 'hostname'` against a set of 75 windows servers.  This failed on some, but not all, of the servers with the large message attached, followed by a series of

Failed on hostname.removed:
  Too many open files

and one error of 

Failed on hostname.removed
  Failed to connect to <hostname>: Too many open files @ rb_sysopen - /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/winrm-2.3.4/lib/winrm/psrp/create_pipeline.xml.erb

Subsequent runs showed only the simple "Too many open files" failure on 2-3 targets - different ones each time - per run.
[too_many_files_error.txt](https://github.com/puppetlabs/bolt/files/4584799/too_many_files_error.txt)

## Expected Behavior
bolt executes the "hostname" command successfully on 75 or more remote windows servers without this error.

## Steps to Reproduce
1. create an inventory file with 75 windows hosts
2. execute bolt command run 'hostname' -t windows

## Environment
 Mac OS X Catalina 10.15.4
 ulimit -n = 256
 bolt 2.7.0

## Additional Context
Problem was resolved by adding ulimit -n 1024 to .bash_profile and launching a new terminal window.  I expect it wasn't actually resolved, but rather pushed out - I think it could be triggered again under the right condition.  Nick L/Lucy W suggested this fix.

Additional commentary from the discussion thread :

> Well, I at least understand what's raising the message, but not why. The WinRM gem seems to use 'Powershell Remoting Protocol' to encode messages to send over WinRM, and it does so by using a template that it reads into memory and populates. It's trying to do that when it fails saying too many files are open. It also sounds like "too many" is usually 1024, and that the fact the error is Errno::EMFILE indicates that it's too many files in the ruby process itself and not on the system.

> That problem could have been made worse by the recent addition of a lot more internal pipes.

> We might be using 5+ fds for each target

**Comment by lucywyman** [comment]
- [] We should catch the EMFILE error and have a message linking to the doc to instruct people on how to increase their file limit.
- [] We should document the issue in our 'known issues' page with more information about why you need to set the limit, how to do it on various platforms, universal vs. user limits, and any other information that's relevant.
- [] We should also spike on whether there are alternatives we can use to have fewer fds open.

**Comment by nicklewis** [comment]
We have some info about tuning ulimit for PE: 
https://puppet.com/docs/pe/latest/config_ulimit.html
