### ISSUE TITLE
Add a way for a Plan parameter to hint that it should be treated securely by GUIs

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/bolt#1790]
## Use Case
When consuming Bolt Plan content from a GUI (e.g. CD4PE custom deployment policies), it's difficult to have Bolt plan parameters treated securely, since you can't work with the `Sensitive` type as a parameter. Instead, you'll have to use a standard `String` type parameter, in order to be able to pass the parameter to Bolt at execution time. But a higher level GUI that exposes the parameter set of a plan, like CD4PE, is then unable to differentiate between parameter values than it can display in clear text, and parameter values that it should obfuscate to the user.

## Describe the Solution You Would Like
Some way of hinting to the GUI that is consuming Plan content, that certain Plan parameters should be treated securely within the calling application's GUI and logging system. A possible example is to introduce an extra Puppet Strings hint:
```
# @ param param1
# @ sensitive param1
# @ param param2
#
plan test_plan (
  String $param1
) {
  $_param1 = Sensitive($param1)
  out::message("Redacted content: ${_param1}")
}
```
As you can see, it's still up to the Plan author to convert the input to a natively secure variable (so that it can be redacted from Bolt's output going forward). The hint provides just enough info to a calling application that the value of `$param1` should be displayed as `*******` in the GUI.

## Describe Alternatives You've Considered
I've tried using the Sensitive type directly:
```
plan test_plan (
  Sensitive $param1
) {
  out::message("Redacted content: ${param1}")
}
```
but found that I have no way of passing the desired value for param1 to the plan, as the incoming value will be of type `String` and Bolt will then error on the type mismatch. A solution to this problem would be the most efficient & most clean way of supporting sensitive parameters though.

## Additional Context
Example of how CD4PE provides a GUI for Bolt plans:
![cd4pe_plan_ui](https://user-images.githubusercontent.com/26876487/81195720-84099480-8fbe-11ea-91cc-8e0bebea8746.png)
You can see how it would be desirable to natively support the handling of sensitive parameters.

**Comment by lucywyman** [comment]
TODO: 
- [ ] See what makes sense with puppet-strings, and come up with an example (or multiple) to present at standup

**Comment by reidmv** [comment]
A better solution than puppet-strings would be to directly permit Bolt to automatically convert String value parameters received on plan run startup to Sensitive, if the target parameter is typed to be Sensitive. This is the general approach Puppet uses for class parameter lookups which are type Sensitive, though the implementation through Hiera is a little awkward. https://puppet.com/docs/puppet/5.5/hiera_merging.html#concept-2997
