### ISSUE TITLE
ERROR Facter::ClassDiscoverer - There is no module named Ol

### ISSUE THREAD

**Issue by ajshastri** [puppetlabs/bolt#1813]
On Oracle linux, running puppet bolt gives the error 
`ERROR Facter::ClassDiscoverer - There is no module named Ol`
This is similar to https://tickets.puppetlabs.com/browse/BOLT-1545

## Expected Behavior
There would be no error of this sort

## Steps to Reproduce
`$ bolt command run "hostname" --target localhost`
This will produce
`[date time] ERROR Facter::ClassDiscoverer - There is no module named Ol`

## Environment
 - Bolt Version - 2.8.0
 - Platform - Oracle Linux 6/7

## Additional Context
It appears to be from os_detector.rb
In def create_hierarchy, addition of the following fixes it
`    when :ol`
`      %w[EL]`

**Comment by ajshastri** [comment]
This appears to be a facter issue in version 4.0.14. Perhaps this is not the place for this bug?

**Comment by nicklewis** [comment]
This seems to be due to Bolt bumping to use Facter 4 (facter-ng) which doesn't support oracle 
linux. I'm not sure whether that functionality is planned or not (I can't find a ticket for it).

This code is probably being called when the analytics client is setup (we use Facter to determine the host OS). The workaround would therefore be to disable Bolt analytics.

We also should be catching errors that happen while setting up the analytics client, so that it can't prevent Bolt from functioning.

**Comment by nicklewis** [comment]
Ah none of those points are as dire as I thought. This _doesn't_ apparently cause Bolt to fail to run and it seems to be fixed in 4.0.19. So in that case, we can just bump the version in Bolt.

**Comment by ajshastri** [comment]
I noticed 2.9.0 is out so perhaps 2.9.1 or 2.10.0?

**Comment by nicklewis** [comment]
Yeah, we should be able to get this in for next week's release.

In the meantime, you may be able to use `/opt/puppetlabs/bolt/bin/gem install facter` to upgrade facter in your install. I'm not 100% sure what will happen when you try to upgrade the package 
 later though...

**Comment by ajshastri** [comment]
@nicklewis  Can you point me to the file that has the facter version? I am unable to locate it.

**Comment by nicklewis** [comment]
It's a little roundabout.

`puppet-bolt` packages are built from [the `bolt-vanagon` repo](https://github.com/puppetlabs/bolt-vanagon). That pulls in an artifact called `bolt-runtime` that contains most of its dependencies and comes from [the `puppet-runtime` repo](https://github.com/puppetlabs/puppet-runtime). The version of facter can be found in the file for the [`rubygem-facter` component](https://github.com/puppetlabs/puppet-runtime/blob/master/configs/components/rubygem-facter.rb) in that repo.

**Comment by ajshastri** [comment]
Oh! I'll leave it in your capable hands :) 

Thank you very much for your help resolving this.
