### ISSUE TITLE
bolt --target localhost munges puppet's non-zero exit codes

### ISSUE THREAD

**Issue by sheenaajay** [puppetlabs/bolt#1846]
## Describe the Bug
`bolt command run --targets localhost 'puppet ...'` does not correctly report exit codes that are not 0 or 1:

![2020-05-27_11MS+0100_1140x327](https://user-images.githubusercontent.com/27712/83011492-d95f2180-a011-11ea-8795-a0db0df6b6c2.png)

## Expected Behavior

Notably the command in the screenshot above is returning exit code 2 and bolt should have correctly reported this.

## Steps to Reproduce

* get a win-2012r2-x86_64 machine from vmpooler
* Install latest bolt package 2.10.0
* Execute the following command: 
```
bolt command run --targets localhost 'puppet apply --trace --detailed-exitcodes "notify { foo: }"'
```
and it throws the following error

![2020-05-27_12MS+0100_1237x390](https://user-images.githubusercontent.com/27712/83011931-9cdff580-a012-11ea-87a4-2ab24194933e.png)

Note how bolt reports exitcode 1, but the same command executed through the powershell has the expected `$LASTEXITCODE` of 2 ("something changed").

## Environment
 - Appveyor (win32) and its failing only on win32
 - Platform [windows]
 - bolt version 2.10.0

## Additional Context
In our testing we could not reproduce the behaviour with bolt 2.6.0. This is currently impacting our testing and we're rolling temporarily back to that version to unblock our pipelines.

Please let us know if you need more information. Thanks a lot for all the help.

**Comment by DavidS** [comment]
Updated initial description with easier repro without extra module and additional screenshots.

**Comment by lucywyman** [comment]
> `bolt command run --targets localhost 'puppet apply --trace --detailed-exitcodes "notify { foo: }"'`

**Comment by lucywyman** [comment]
Sorry fatfinger :sweat_smile:
