### ISSUE TITLE
Add option to enable deprecated algorithms in net-ssh

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1862]
## Use Case
With the release of net-ssh 6.0, support for several weaker algorithms was deprecated and disabled by default. This can cause an issue for users who are attempting to connect to targets that are configured to only use deprecated algorithms, as it makes it impossible for Bolt to connect to them, even to update the SSH configuration to use stronger algorithms.

Users should be able to connect to targets using deprecated algorithms so they can continue to use Bolt, including using Bolt to update the target's SSH configuration.

## Describe the Solution You Would Like
Add a configuration option to the SSH transport that accepts a list of algorithms to enable in net-ssh. This option should also be configurable in PE.

## Questions
- Should Bolt display a warning when enabling a deprecated algorithm, or just have a warning in the documentation? net-ssh plans to remove support entirely for deprecated algorithms in 7.0, so it might be helpful to explicitly tell users this.

**Comment by adreyer** [comment]
This is three settings which should override ssh config options.
ciphers
host-key algorithm
kex algorithm


Is there a case where net::ssh won't honor insecure but supported algorithms from ssh config? Discuss how to handle this if so.

**Comment by adreyer** [comment]
add special string for `default-ciphers`.

**Comment by beechtom** [comment]
net-ssh has a constant defining all supported algorithms: https://github.com/net-ssh/net-ssh/blob/92669095ab1689a140f7fcc46b16480f9b5c93ea/lib/net/ssh/transport/algorithms.rb#L66
