### ISSUE TITLE
modulepath argument in bolt.yaml for multi-platform host

### ISSUE THREAD

**Issue by jasy125** [puppetlabs/bolt#1864]
This request refers to running a bolt command on a Linux/Mac host laptop versus a Windows 10 host machine.

bolt.yaml Doc page: https://puppet.com/docs/bolt/latest/bolt_configuration_options.html#sample-bolt-configuration-file

We need to document the following about the modulepath argument in bolt.yaml:

modulepath: "./modules":"./site-modules" # the ':' (colon) separator works only on Linux/Mac host machine

modulepath: "./modules";"./site-modules" # the ':' (semi-colon) separator works only on Windows 10 host machine

modulepath: ["./modules","./site-modules"] # the array syntax '[]' and ',' (comma) separator works on both Linux/Mac & Windows 10 host machine

**Comment by adreyer** [comment]
We should always show the array in examples and mention the string format only in describing why it's limiting.

**Comment by beechtom** [comment]
Closed by #1885
