### ISSUE TITLE
Clean up bolt configuration reference

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1888]
## Describe the Change You Would Like
We should have a separate configuration reference page for the different configuration files. 

- [x] bolt.yaml(soon to be deprecated)
- [x] bolt-project.yaml
- [x] inventory.yaml
- [x] bolt-defaults.yaml(soon)
- [x] Transport configuration options

* Options should be meaningfully groups as opposed to purely alphabetical. For example transport options together.
* We should try to change the phrasing of specific options to be more prescriptive
for example. connection-timeout. increase this above NNN if you see errors like ...
* These descriptions should be available from the json schema

**Comment by hestonhoffman** [comment]
I'm going to jot down some thoughts here. I've been struggling with how to document experimental documentation in general, especially features like this, which replace existing functionality, and are so fundamental to the way people use Bolt.

I've been thinking a lot about where these pages (and docs on experimental features in general) should go. Regardless of what we choose, I think we need to add some kind of deprecation warning (or just a note that we're working on changing things) to the older doc/s, as well as a link to the experimental doc that describes the changes we're making. Similarly, any docs for experimental features outside of the experimental features page/section should also start with a brief explanation and a link to the experimental doc that explains the feature. 

Here are the options I see:
1. Put these alongside the existing configuration reference doc/s. This could potentially be quite confusing for users. If we do go this route, adding very clear introductions + links to the conceptual doc is very important. 
2. Add these docs as children to the experimental docs page - essentially turning it into an experimental section. I think this could work. I like the idea of keeping everything that's experimental in one place. I guess the argument for not doing this is that you'll have users who simply don't know to look there for reference docs.
