### ISSUE TITLE
Rename 'master' branch

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1901]
We should rename the 'master' branch of Bolt to something more neutral like 'main'. 'Main' is what most folks at Puppet seem to lean towards, but it's open for discussion.

- [x] Update ci-job-configs to reference new branch name
- [x] Update bolt-vanagon as well
- [x] Ensure github actions run on new default branch
- [x] Update README links
- [x] Set default branch on affected repos
- [x] Send email to let people know the master branch is going away
- [x] Delete the master branch

## Additional Context
[Github is planning to remove 'master' from it's platform](https://www.vice.com/en_us/article/k7qbyv/github-to-remove-masterslave-terminology-from-its-platform), but doesn't have a timeline for that or definition of what renaming will look like.

**Comment by nicklewis** [comment]
Perhaps we ought to expedite the removal of the GH pages site, as building from a directory currently only supports the `master` branch. And I can't think of anything worse than having two 
branches named `main` *and* `master` if we needed to keep the latter around for GH pages. We could make a `gh-pages` branch and move the `docs/` content to the root, but if we can just remove it that would be easier.

**Comment by npwalker** [comment]
This looks like the issue around moving the /docs directory.  https://github.com/puppetlabs/bolt/issues/1793
