### ISSUE TITLE
Tasks: Add more examples in common scripting languages

### ISSUE THREAD

**Issue by hestonhoffman** [puppetlabs/bolt#1906]
Transferred from Jira (BOLT-1541)

## Describe the Change You Would Like
Any time there is an example of code for a given bolt workflow, feature, function, or best practice there should be an example in each common scripting language.  Currently there is often only a ruby example. Most operations teams that would attempt to on-board bolt would not typically write administrative scripts in ruby but already have them in bash, powershell, or python.  Given each of these options it will be make the on-boarding and first experience with Bolt more user friendly. 

Current pain point is with error handling for bash. The docs give ruby examples for error handling https://puppet.com/docs/bolt/latest/writing_tasks.html#returning-errors-in-tasks however I would need now look up error handling in bash to modify my code, then guess how to wrap that for a Bolt task specifically.

## Comments from ticket: 
Bash and Powershell are everywhere. This is the universal default for scripts for nearly every organization. Python steps up to the plate once we start talking about arrays and hashes (because Bash is particularly bad at this). Python is also super sharable thanks to strict syntax. The huge library of available code also pushes people here occasionally. Generally a few talented people at an organization write Python and the other ops folks act as consumers of their scripts. Rubyists at orgs write more Python than Ruby. Non-Rubyists won't dive any further than a basic fact (and that takes them nearly a year of writing Puppet to attempt on their own). 

I'd rather see bash and powershell treated as first class citizens in our documentation, and Ruby and Python treated as the heavy-lifting scripting language, rather than the default. With Python as the default language (like our customers use).

**Comment by beechtom** [comment]
- Task features are usually more complex than bash can handle, we usually don't offer bash examples anyways
- Reasonable to do Ruby, Python, Powershell examples
- Start with examples in a single language
   - Documenting how to use noop, already have this in Python and seems reasonable to expand to Ruby and Powershell
