### ISSUE TITLE
Bolt does not ignore editor backup files.

### ISSUE THREAD

**Issue by KedneckInc** [puppetlabs/bolt#191]
When an editor, like Emacs, leaves a backup file in the directory, Bolt should ignore it.

**Comment by KedneckInc** [comment]
**CORRECTION:** The real problem is that bolt does not ignore editor backup files.  When Emacs edits a file, it makes a backup copy with a tilde appended to the end of the name.  Bolt should ignore such files.

**Comment by MikaelSmith** [comment]
In what sense does it not ignore them? When looking for task implementations? i.e. you have `module/tasks/foo.sh` and `module/tasks/foo.sh~`?

**Comment by KedneckInc** [comment]
Exactly.

The .sh~ version of the file is the one that gets executed, so the changes
you keep making to the .sh version are never run.  It is very frustrating
until you finally notice that the file being executed has a tilde appended
to the name.

Bolt really should ignore standard editor backup files, and it doesn't.

**Comment by adreyer** [comment]
For reference this is tracked in jira as [BOLT-246](https://tickets.puppetlabs.com/browse/BOLT-246)

**Comment by lucywyman** [comment]
@KedneckInc - are you still having this issue? We seem to have resolved the Jira issue, so I'm going to close this github issue, but let us know if problems persist!
