### ISSUE TITLE
Bolt Apply log output

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/bolt#1920]
When I run Bolt Apply with a notice statement, the only way to view that notice statement is with `--debug`. For example
```test.pp
notice("This is a test: $::fqdn")
```
```
$ bolt apply test.pp -t target
```

That includes *a lot* of output.

I'd expect to see notice statements either by default, or at least when I run with `--verbose`.

**Comment by nicklewis** [comment]
Can you use `out::message` instead?

**Comment by MikaelSmith** [comment]
It's `bolt apply`, so I'm running a manifest not a plan. I might be able to use `out::message`, but I'm not going to change that in all modules I use.

**Comment by lucywyman** [comment]
## Solution
As part of this we should add a `--log-level` CLI flag that matches the `log: level` configuration option that accepts `notice`, `info`, `warn`, `error`, `debug`. `--verbose` should behave how it currently does. This should allow our logger to handle other log-levels and surface logs from Puppet.
- We should 'convert' `--debug` to `--log-level debug` and warn that we did that conversion
