### ISSUE TITLE
Allow selective sync of plugins to target nodes

### ISSUE THREAD

**Issue by hajee** [puppetlabs/bolt#1934]
## Use Case

When using a puppet apply block in a plan, bolt sync's all of the plugin files in all of the modules over to the target node. When the Bolt projects where small and the execution time of the puppet code was long, this was no issue. Since the integration with Puppet Enterprise, it is recommended that the Bolt dir is integrated with the control repo. In general control repo's for larger environments are quite large.

If we would like a plan to contain a very small fragment of puppet code, currently all plugins from all modules are synced to the targets. This is very time and resource consuming.

## Describe the Solution You Would Like

It would be great if the plan author can specify what modules need to be synced, and thereby controlling the amount of plugin data to be synced to the target.

**Comment by lucywyman** [comment]
@hajee Are you wanting to use this with PE? Or just with Bolt?

**Comment by hajee** [comment]
I think this can be useful for both. Right now we use bolt we might switch to the more integrated variant in PE.  Seeing the use case it is more beneficial for PE, but I can imagine the same issues happening using just bolt and having a large set of modules.

**Comment by lucywyman** [comment]
Closed by #1935
