### ISSUE TITLE
Support ed25519 on Windows

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/bolt#1941]
See https://tickets.puppetlabs.com/browse/BOLT-1296, https://tickets.puppetlabs.com/browse/IAC-896, https://tickets.puppetlabs.com/browse/PA-2274 and, most recently, https://puppetcommunity.slack.com/archives/C0W1Z7213/p1593030060470000

**Comment by lucywyman** [comment]
@DavidS This is documented in our [known issues page](https://puppet.com/docs/bolt/latest/bolt_known_issues.html#unable-to-authenticate-with-ed25519-keys-over-ssh-transport-on-windows) - I don't know that this team has the bandwidth to investigate and make upstream changes required to get this working.

**Comment by lucywyman** [comment]
I think this is a duplicate of #1987 . Let me know if I have it wrong and I can reopen.
