### ISSUE TITLE
Bolt extremely slow on macOS

### ISSUE THREAD

**Issue by atika** [puppetlabs/bolt#1951]
## Describe the Bug
I just started trying to understand and configure Bolt and I found it very slow to respond. I tried on a Ubuntu vhost with multipass, even if the response time is not as fast as I think, there is a huge difference.

```shell
# macOS: 1,175s / Ubuntu: 0.501s
time /opt/puppetlabs/bin/bolt --version
```

```shell
# macOS: 3,556s CPU 98%  / Ubuntu: 1.867s
time /opt/puppetlabs/bin/bolt plan show reboot
```

```shell
# macOS 4,019s / Ubuntu: 1.662s / ssh command: 0,126s
time /opt/puppetlabs/bin/bolt command run 'whoami' -t localhost
```

```shell
# macOS: 3,318s / Ubuntu: 1.686s
time /opt/puppetlabs/bin/bolt task show
```

By using an executable alias like this I have theses timings:
```shell
# normal: 3,306s / alias: 2,528s / Ubuntu: 1.351s
/opt/puppetlabs/bolt/bin/ruby /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.15.0/exe/bolt task show
```

For puppet:
```shell
# macOS: 2,007s / Ubuntu: 1.045s
time /opt/puppetlabs/bolt/bin/puppet --version
```

Sometimes I wait like 6 seconds to have a response and this makes developing Bolt tasks and plans pretty difficult for a basic user like me. I don't know if I could do something to speed it up.

## Expected Behavior
Bolt responds quickly to commands.

## Steps to Reproduce
1. Enter any bolt command
2. Wait for the reply

## Environment
 - Version 2.15.0
 - Platform macOS 10.14.6

## Additional Context
Installed with Homebrew.

**Comment by nicklewis** [comment]
I see the same slowness you do between macOS and Linux and I also see that invoking Ruby with `exe/bolt` directly improves the load time. It seems to have a similar effect on Linux as well, but the base time is already much faster. This matches with some investigation we've done that found using `bundler` would speed up the load time. I expect that it's taking a while for it to resolve and activate the `bolt` gem, perhaps because it has so many gem dependencies. This may be a good reason for us to move forward with running Bolt via bundler.

**Comment by atika** [comment]
I understand that there is a lot of things to load, even just to get the version. What I found strange is that in the same machine, and with the same version of Bolt, on macOS it takes twice the times of Ubuntu (whose resources must be limited because it's a VM) to executes the command.

When I run a command like this:

```shell
time /opt/puppetlabs/bolt/bin/ruby -v /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.16.0/exe/bolt task show
```

It's hangs on some part like this:

```shell
# executed multiples times
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.16.0/lib/puppet/settings/base_setting.rb:180: warning: instance variable @deprecated not initialized 
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.16.0/lib/puppet/pops/model/factory.rb:1187: warning: instance variable @current not initialized
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.16.0/lib/puppet/pops/types/p_object_type.rb:1100: warning: instance variable @self_recursion not initialized
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.16.0/lib/puppet/pops/model/factory.rb:1187: warning: instance variable @current not initialized
/opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59: warning: loading in progress, circular require considered harmful - /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.16.0/lib/puppet/pops.rb
```

But I have no idea if this could be the problem.

**Comment by nicklewis** [comment]
This seems to have gotten worse in 10.15, at least on my machine. I'm seeing 8 seconds to run `bolt command run`. Using bundler, which I had hoped would be the solution, gets it down to 2.8 seconds which is still not really acceptable.

It looks like this is some combination of recent security sandboxing features as well as potential issues with Ruby itself. [This thread](https://discuss.rubyonrails.org/t/why-is-rails-boot-so-slow-on-macos/74021) has some more detail.

I'm still investigating possible solutions, but this is definitely a discouraging finding...

**Comment by nicklewis** [comment]
I gathered [some data about performance](https://docs.google.com/spreadsheets/d/1FILyzYRiwI9UBoh9mxdQejbTzujCob-6NQCSHE946to/edit#gid=0) for a set of commands on Linux, macOS and Windows as well as the impact of several potential improvements. We're still investigating the feasibility of each of the options, but this is something we're actively focused on.

**Comment by nnul** [comment]
Are there any updates on the status of this issue?

I recently migrated one of our projects over to Bolt and encountered this same disparity between Linux and MacOS.

**Comment by johnmetta** [comment]
This is even worse in Windows:

`Measure-Command { bolt --version }` takes 12.5 seconds. `Measure-Command {bolt plan show}` takes 43.5 seconds. The introductory videos on Bolt talk about it being the only config mgmt system that makes Windows a full class citizen. Waiting a full minute for a simple Bolt command makes me question this.
