### ISSUE TITLE
Ability to pass env-vars for run_command and run_script from the CLI

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1980]
## Use Case
Now that `run_command()` and `run_script()` support the new `_env_vars` option in #1899 it would be great if we could set these from the CLI.

Similar to use cases in #1899 , want to pass in secrets / credentials to commands and scripts. In order to use that feature, we would currently have to wrap the `run_script` and `run_task` functions in a plan which is not ideal for integrations that use the CLI, such as https://github.com/StackStorm-Exchange/stackstorm-bolt

## Describe the Solution You Would Like

Three solutions come to mind:

#### 1. Provide a `--env-vars ENV_VARS` CLI option

`--env-vars` would be a new CLI option and take a JSON string of environment variables.

```
bolt command run --targets localhost --env-vars '{"NICKS_VAR": "Hello Word"}' 'echo $NICKS_VAR'
```

Downside here is that the environment variables would be exposed and visible when the CLI command. Since we're trying to hide secrets/creds, i'm not a huge fan of this option.

#### 2. Read environment variables from "special" environment variables when Bolt is run

We could designate some special environment variable prefix, in this example i'm going to use `BOLT_ENV_VAR_`. This prefix will be stripped and the rest of the variable name will become the name of the variable when executing the command/script.

Example
```
export BOLT_ENV_VAR_NICKS_VAR="Hello World"
bolt command run --targets localhost 'echo $NICKS_VAR'
```

#### 3. Pass JSON to a new BOLT_ENV_VARS environment variable

We could read BOLT_ENV_VARS and expect this to be a JSON hash. This hash would then set the environment variables in the context when running the command/script.

Example
```
export BOLT_ENV_VARS='{"NICKS_VAR": "Hello World"}'
bolt command run --targets localhost 'echo $NICKS_VAR'
```

**Comment by adreyer** [comment]
After some discussion we think using a repeated flag for this is probably easier

`bolt command run --targets localhost --env-var NICKS_VAR=Hello --env-var VAR2=world 'echo $NICKS_VAR $VAR2'`

**Comment by nmaludy** [comment]
@adreyer see my comments on #1 above. If we implement it as a CLI option, those secrets are exposes on the command line and available for reading if you do a `ps`. This is fine for non-secret options, though.

Thoughts?

**Comment by lucywyman** [comment]
@nmaludy You can still use environment variables and pass them on the CLI:
```
export SECRET=sauce
bolt command run --env-var NICKS_VAR=$SECRET
```
I think the toughest part is then you have to set every environment variable instead of just passing in a hash. Are you manually running commands, or building them programmatically? I think building the command programmatically would still be just as easy (iterate options and set `--env-var`), but running manually that may be a pita...
