### ISSUE TITLE
Write an example/prototype of how to run a directory of external executable facts and return output that looks something like what facter would produce

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/bolt#1981]
## Use Case
I've spoken with customers that have scripts they want to run with bolt and make sense of the information the script produces.  The scripts do only reading of system information and can produce nested structures.  

This makes the information produced by the scripts much more like puppet facts than just an arbitrary script that performs an action on the node.  

## Describe the Solution You Would Like
Given a directory of [external executable facts](https://puppet.com/docs/puppet/latest/external_facts.html#executable-facts-on-unix) run each one and collate the information produced to look something like what facter would produce.  

This provides a clearer piece of guidance on how to structure information gathering "scripts" instead of one big script break each one down into an external executable fact and we'll output it in a nicer format for you  

This should be a plan similar to the facts plan that takes a path to a directory and sets facts based on running scripts in that directory.

## Describe Alternatives You've Considered
An alternative would be to make these external executable facts and get them submitted by the agent every run.  But for many facts that don't influence the behavior of a puppet run storing those in PuppetDB may be detrimental to your health ( or at least the perf of PuppetDB) 

If facter provided a way to run a group of facts separately from those that are submitted every agent run that would help but also requires facter.  The solution here is more advantageous in that it doesn't require facter.

**Comment by beechtom** [comment]
Closed by https://github.com/puppetlabs/puppetlabs-facts/pull/41
