### ISSUE TITLE
`bolt project init` should create a `bolt-project.yaml`

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/bolt#2003]
## Describe the Solution You Would Like
`bolt project init` should create a `bolt-project.yaml` with the `name` key filled out to the name of the current working directory.  

It should also no longer create a bolt.yaml which is deprecated.  

## Solution
- [x] This should change `bolt project init` to create `bolt-project.yaml` with `name: <current directory>`. If the current directory is not a valid project name, we should error and tell the user to change the dir name or specify a name.
- [x] This should change `bolt project init <name>` to create bolt-project.yaml with the specified name.
- [x] If bolt-project.yaml already exists we should not remove the existing file.
- [x] --modules should behave the same
- [x] If bolt.yaml exists we should error.

**Comment by lucywyman** [comment]
Relies on #1999
