### ISSUE TITLE
bolt should have commands for generating task and plan skeletons 

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/bolt#2004]
## Use Case
Whenever, I go to make a new task I have to find a module that already has a task, copy the task and metadata file out and then start modifying.  I cannot remember what I need to make a task or a plan.  

## Describe the Solution You Would Like
`bolt task new` and `bolt plan new` or similar commands that lay down a skeleton task/plan in the right location.   

## Describe Alternatives You've Considered
I considered pdk but pdk requires a valid metadata.json because it expects to work with puppet modules.  It also creates a lot of extra baggage in the form of files and laying down tests, etc... 

pdk should also have a way to do this as well but it should be additional to whatever the commands in bolt do.  Bolt has the commands that provide the minimum to allow you to just make a simple task or plan and pdk should add things on top that help an advanced author test, lint, etc... the tasks / plans.  Ideally pdk would literally use bolt to lay down the same skeletons or they could share skeletons centrally somehow?

**Comment by lucywyman** [comment]
Plans are easier than tasks, we should start with 'bolt new plan' as it's simpler to implement.
