### ISSUE TITLE
Add docs on how to use out::message for debugging

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/bolt#2007]
## Describe the Change You Would Like

I’m currently doing
```
   $show_databases = run_task('mysql::sql', $targets, "Show the new database is there", {'sql' => "SHOW DATABASES"})
-  return $show_databases
+  out::message($show_databases.first.message)
```

which results in

```
MacBook-Pro:automations nw$ bolt plan run automations::apache_plus_mysql_converted --targets="agent-no-pe-centos" --no-host-key-check --user=centos --run-as=root
CLI arguments ["user", "host-key-check", "run-as"] may be overridden by Inventory: /Users/nw/git_repos/automations/inventory.yaml
Starting: plan automations::apache_plus_mysql_converted
Starting: Show the new database is there on agent-no-pe-centos
Finished: Show the new database is there with 0 failures in 4.44 sec
Finished: plan automations::apache_plus_mysql_converted in 4.46 sec
{
  "kind": "bolt/pal-error",
  "msg": "'out::message' parameter 'message' expects a String value, got Undef",
  "details": {
    "file": "/Users/nw/git_repos/automations/plans/apache_plus_mysql_converted.pp",
    "line": 13,
    "column": 3
  }
}
```

but I think I also tried results.message as well which is a different problem

Cas recommends 

Remember run_* returns a ResultSet. For debugging with out::message I would encourage you to try to explicity wrap stuff in String (or just do interpolation).

```
$result_set = run_task(my_task, $targets)
out::message(String($result_set[0].value))
```

This makes sense but I couldn't find any reference on how to use out::message to output things for debugging purposes.  Having a few examples of outputting different useful parts of a result_set would probably allowed me to figure this out on my own.

**Comment by adreyer** [comment]
Is there a reason to document `out::message` for debugging over the log functions?

**Comment by npwalker** [comment]
Maybe debugging is the wrong word for what I was doing... I was actually trying to output in the plan what the output of the command I ran on the system was.

**Comment by donoghuc** [comment]
Not that you would be necessarily debugging plans in PE console, but out::message is the way you can see that there.

**Comment by lucywyman** [comment]
We should have a 'debugging plans' section on the writing plans pages (on both the yaml and puppet plan pages).
In the section we should document using `out::message()` to print strings (emphasizing that out::message can only print strings).
