### ISSUE TITLE
Document wrapping a script in a yaml plan

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2016]
## Describe the Change You Would Like
In many cases, users with simple scripts they want to automate are better served by wrapping the script in a yaml plan rather than attempting to convert it to a task. We should document this workflow.

And indicate why they may prefer a task or a plan. It may be useful to do this for parameterizing input to the script, logging messages, showing up in `bolt plan show`.

**Comment by beechtom** [comment]
This may be superseded by https://github.com/puppetlabs/bolt/issues/2098 .
