### ISSUE TITLE
Specify valid exitcodes

### ISSUE THREAD

**Issue by scbjans** [puppetlabs/bolt#2022]
## Use Case
When for instance performing a Puppet run from Bolt (in this case using `bolt command run 'puppet agent -t' --targets target`), an exitcode of 2 is returned when the run was successful but changed some resources. This marks the Bolt job as 'failed'.

## Describe the Solution You Would Like
It would be awesome if valid exitcodes can be specified, such that in above example the Bolt job is marked as succeeded.

## Solution
We should write a task in the puppet_agent module that run puppet against the specified targets. We should specify in the documentation that this may cause problems when run in PE

**Comment by beechtom** [comment]
https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/503

I'd like to get tests written, but still trying to figure out the best way to do that (rspec unit tests vs. beaker tests).
