### ISSUE TITLE
Add plan and parameter descriptions to plan documentation when converting YAML plans

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2039]
## Use Case

YAML plans accept a top-level `description` key and parameter-level `description` keys that are used by `bolt plan show` to show plan documentation. Puppet plans use puppet-strings to pull similar documentation from comments at the top of the plan file. The `bolt plan convert` command should add plan and parameter descriptions from a YAML plan to the comments in the converted Puppet plan to preserve documentation.

To test: `bolt plan show` is the same for the YAML plan as the converted puppet plan.

**Comment by donoghuc** [comment]
+1 i've wanted this before for demos. Having the plan descriptions show up in the console for PE is helpful.

**Comment by kops-vn** [comment]
Yes, it is good if we have plan description in the console.
