### ISSUE TITLE
Support Fedora 32

### ISSUE THREAD

**Issue by heylix** [puppetlabs/bolt#2042]
Fedora 32 is [out since end of April 2020](https://fedoramagazine.org/announcing-fedora-32/), which was 3 months ago.

Would be nice if you could support it / create a repo for it.

The F31 package installed fine and seems to work, too, so I doubt there are many changes needed.

**Comment by nicklewis** [comment]
https://github.com/puppetlabs/bolt-vanagon/pull/144
https://github.com/puppetlabs/ci-job-configs/pull/7216
