### ISSUE TITLE
Support input prompt for bolt command run

### ISSUE THREAD

**Issue by m0un10** [puppetlabs/bolt#2069]
## Use Case
I'm using Bolt to run tasks concurrently but the tool it is calling has an input prompt

## Describe the Solution You Would Like
If there is an input prompt, it would be nice if it could be passed back to the calling user to respond to in the same way it work if calling from the host directly.

## Describe Alternatives You've Considered
I considered whether there is a way that I could provide the inputs via an env var or argument. For my use case, this wasn't possible due to limitations of the tool being called.

## Additional Context
Currently, if there is an input prompt, it will just hang. An alternative (if there is no desire to support this) it would be nice to show a helpful message that says the command was blocked due to an input required.

**Comment by nicklewis** [comment]
I don't think it's possible to detect that a command is waiting for input. The command will print something that a human user can understand as a request for input, but from Bolt's point of view it's just some arbitrary output.

Even if we could detect it, handling the case where multiple targets need input at the same time is extremely difficult. Unfortunately, I'm not sure there's much we can do to help this use case.

You could maybe write a task with `#!/usr/bin/expect`, depending on what exactly it needs to do.

**Comment by lucywyman** [comment]
Closing as won't do
