### ISSUE TITLE
Improve documentation for writing plugins

### ISSUE THREAD

**Issue by hestonhoffman** [puppetlabs/bolt#2076]
The current doc for writing plugins is really sparse.

## Feedback on what needs to be improved

Include examples for how to format groups output:
```
{
  "value": [
    {
      "name": "standard",
      "targets": [
        {
          "uri": "bb8531de599e"
        }
      ]
    }
  ]
}
```

**Comment by logicminds** [comment]
basically, what is the expected output with examples when a grouped response is returned.  Also, can the returned group response also have other config data? 

```
{
  "value": [
    {
      "name": "standard",
       "transport": "ssh",
       "ssh": {
          "tmpdir": "/root/tmp"
       },
      "targets": [
        {
          "uri": "bb8531de599e"
        }
      ]
    }
  ]
}
```

Are there other types of responses that can be returned?
