### ISSUE TITLE
Add `bolt modules install`

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2082]
## Use Case
- [x] Users should be able to configure a list of modules their project depends on under a `modules` key in `bolt-project.yaml` (and not `bolt-default.yaml`), and install those modules with `bolt module[s]/project install`.
  - If no Puppetfile is present the command will generate a Puppetfile based on modules defined in bolt-project.yaml then install that puppetfile.
  - If a Puppetfile is present and it contains all the modules in modules.yaml bolt will install that Puppetfile.
  - If a Puppetfile is present and it is missing declared modules, or it can not be simply parsed the user will be instructed to rerun after deleting or moving it or with the `--no-resolve/--force` flag. The dependencies will not be validated every run since the puppetfile is expected to pin each module explicitly.
  - Modules should be installed to `.modules/`. `.modules/` shouldn't be added to the modulepath, though users can add it manually to their modulepath.
  - Users should be able to copy-paste module definitions from module dependency definitions in metadata.json into this file and Puppetfile will be considered a machine-only file for most users.

To ticket:
- [x] `bolt puppetfile show-modules` -> `bolt module[s]/project show` . Deprecation can happen later.
- [x] `bolt generate-types` -> `bolt module[s]/project generate-types`
- [x] Add PowerShell cmdlet `Install-BoltModule` / `Install-BoltProject`
- [ ] Update docs. This should happen last so docs don't go live for a feature that is flagged.
 
## Questions:
- [x] `bolt module install` or `bolt modules install` or `bolt project install`? Do a user test
- `--no-resolve` or `--force`? **--force makes more sense**

**Comment by beechtom** [comment]
Closed by #2106
