### ISSUE TITLE
We should add a 'What's Happening' page to the Bolt docs

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2084]
## Describe the Change You Would Like
"As a user, it's hard to tell how half-baked features like the new Bolt projects are eventually expected to work, and how I should use them".

We should include a short "developer update" of sorts for various new features. The page should be limited to 10 'features', and updates can be casual and should emphasize that everything in them is subject to change.

**Comment by beechtom** [comment]
Closed by https://github.com/puppetlabs/bolt/pull/2232
