### ISSUE TITLE
Hacktoberfest Prep

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2092]
## Use Case
To prep for [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) we should:
- [x] Ensure the CONTRIBUTING doc is up to date and works on *nix and Windows platforms
- [x] Create and [publish](https://docs.google.com/document/d/1B4CMhUIl-klD3t6hWxrFtEHEESb9mbIyEJ6TqvQwQrM/edit#) a list of plugins / tasks / plans ideas
- ~~Host an event? They're all online this year, could be fun!~~ [Register for the Americas hackathon here](https://organize.mlh.io/participants/events/4634-puppet-hackathon), EMEA event coming soon!

**Comment by nmaludy** [comment]
+1 would love some labels so i know what to work on!

+1 for an event!
