### ISSUE TITLE
Warn when project shadows a module with the same name

### ISSUE THREAD

**Issue by nicklewis** [puppetlabs/bolt#2108]
## Use Case

A simple pattern for running tasks/plans from some module with an inventory is to create a project that simply references the module and includes an `inventory.yaml`. It's intuitive to give this project the same name as the module it's wrapping. However, this actually causes the (non-existent) project-level content to shadow the module with the same name, requiring the project to actually have a _different_ name.

This shadowing is a natural consequence of projects having their own content and is not a bug, but it _is_ surprising behavior that can cause confusion when tasks/plans don't show up as expected.

## Describe the Solution You Would Like

We should warn at some point during Bolt's lifecycle, either every time a command is run or only when using tasks/plans or only when installing modules, that the project name will conflict with a module of the same name on the modulepath.

We should raise this warning when we call PAL#in_bolt_compiler when loading modules.

**Comment by beechtom** [comment]
Closed by #2143
