### ISSUE TITLE
Allow log files to be disabled

### ISSUE THREAD

**Issue by nicklewis** [puppetlabs/bolt#2120]
## Use Case
There's presently no way for a project to remove/disable a log file that is defined in `bolt-defaults.yaml`. This happens simply because we define hashes of log files and merge them and have no mechanism to remove a key from the hash.

This is particularly important now that we always define a default log file.

This feature was initially defined as part of #2068 but was missed in the implementation of that ticket.

## Describe the Solution You Would Like

We should look for `<file>: disable` in the `log` section and remove the key after merging.

**Comment by beechtom** [comment]
Closes by #2121
