### ISSUE TITLE
Copy bolt puppetfile to bolt module

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2131]
## Use Case
- Rename `bolt puppetfile show-modules` to `bolt module show`.
- Rename `bolt puppetfile generate-types` to `bolt module generate-types`
We should not deprecate `bolt puppetfile *` yet, we can do so closer to Bolt 3.0.

This should still show modules from the Puppetfile, not from the `modules` data in bolt-project.yaml.
Behavior should be the same as `bolt puppetfile`.

**Comment by jpogran** [comment]
These were hardcoded in the pwsh generation rake file here https://github.com/puppetlabs/bolt/blob/main/rakelib/pwsh.rake#L27-L40, so we'll have to adjust that as part of this work. It might be possible to remove the hardcoding and rely on the detection logic.
