### ISSUE TITLE
Run-as administrator windows won't work.

### ISSUE THREAD

**Issue by creativefre** [puppetlabs/bolt#2140]
Hi,

Since I can't find any documentation on this.
I'm currenly using bolt version 2.25.0

In my usecase I want to winrm to a windows node and run a script as administrator. But I login as a normal user who has administrator rights and not as Admin itself.

Here is my command: 

```
bolt script run windows_puppet_agent_6_17.ps1 --password-prompt --targets winrm://by1ack --no-ssl --user mjbjf@adpa3.local --run-as Administrator
```

When I run this command it executes it without admin priviliges. Is there a way like run-as to become admin when logging in as a normal user?
Or is it for this moment only possible by directly logging in as the adminstrator user.

Kind Regards

**Comment by jpogran** [comment]
Hi @creativefre thanks for the question. The way WinRM works is by connecting with the user that has permissions to perform the actions, not by elevating/changing to another user after connection. Put another way, WinRM operates with a session level token and has no functionality to change to another user after authentication. You can connect with one user, then provide credentials to a program that accepts them to perform another action, but that is not part of WinRm.

For example, I use `bolt script run` to connect to a remote computer using `UserA`, and inside the script is `Restart-Computer -Credential` with `UserB`'s credentials to restart the target. This is not the same as `sudo` which `run-as` is meant to enable, but it's the closest you will get currently with WinRM.

**Comment by lucywyman** [comment]
- Document using the inventory, remote tasks, basic task parameters, and hiera to get sensitive task parameters into a task to escalate as.
- Using hiera may be the most general method
- Provide a Powershell example
