### ISSUE TITLE
Allow module authors to indicate Bolt version requirements

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/bolt#2209]
## Use Case

My team maintains a Bolt plans module (peadm) which is frequently updated to take advantage of new Bolt features. This means that often times, to use the module successfully users must have a known minimum version of Bolt. However, for users of older Bolt versions this is often not evident until one of the plans encounters an error halfway through.

## Describe the Solution You Would Like

It should be possible to provide in a module's metadata.json file a Bolt version requirement. This version requirement should at a minimum produce a warning when tasks or plans are used with a version of Bolt which does not match the given requirement.

The version requirement should permit optimistic (`>= 2.26.0`) or pessimistic (`>= 2.26.0 < 3.0.0`) specifications. The module author should be able to choose which to use.

## Alternatives

Provide a function to return the in-use version of Bolt so that users can write plan code to validate expectations. This is less ideal than a metadata.json solution because it requires work on the part of the user to operate, and it only applies to plans, not tasks.

**Comment by lucywyman** [comment]
@reidmv Not against doing this, but in the meantime could you check the Bolt version at the top of whichever plans or tasks users typically call into? `bolt --version` outputs  a bare string that should be easy to consume, minimal munging required.

**Comment by reidmv** [comment]
Yep, we could totally could implement a one-off workaround for a single module that way today. The ticket exists more because I think this is a problem worth having a product solution for and a "right" way of addressing; less to solve the problem for me, personally, today.

**Comment by reidmv** [comment]
After several incidents of customers using the peadm module with a Bolt version too old and being presented with unhelpful error messages, we have implemented a module-specific workaround as follows. https://github.com/puppetlabs/puppetlabs-peadm/pull/141.

This work-around demonstrates the UX that we'd like to have generally available to all authors, to prevent confusion from using a too-old version of Bolt with new content.
