### ISSUE TITLE
Add 'apply' function to function reference

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2260]
## Describe the Change You Would Like
The `apply` function should be listed on the [function reference page](https://puppet.com/docs/bolt/latest/plan_functions.html). We should either duplicate the information [here](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html#applying-manifest-blocks-from-a-puppet-plan) or link to that page from the function reference page.

**Comment by lucywyman** [comment]
Closed by #2285
