### ISSUE TITLE
Support for Raspbian

### ISSUE THREAD

**Issue by EwertonJordao** [puppetlabs/bolt#2283]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]
Made a Raspbian able to orchestrate tasks
## Describe the Solution You Would Like
I want to install puppet-bolt on my Raspbian and orchestrate my tasks from that system
## Describe Alternatives You've Considered
N/A
## Additional Context
N/A

**Comment by lucywyman** [comment]
We don't have plans to support Raspbian formally, but I know @Sharpie might be able to help you build a package on your own, or #pi in our [community slack](https://puppetcommunity.slack.com/) may also be useful!

**Comment by EwertonJordao** [comment]
@lucywyman I try to enter the community but is necessary had an email in  domain puppetlabs.com or puppet.com.



![image](https://user-images.githubusercontent.com/12378570/98068589-38d02180-1e3b-11eb-9bba-cda62c515cb9.png)

**Comment by lucywyman** [comment]
Hmmmm https://slack.puppet.com/ might be a better link? That will send you an invite to the community slack. Let me know if that doesn't work and we can figure something out!
