### ISSUE TITLE
Don't mention "Boltlib::<type>" in the function reference

### ISSUE THREAD

**Issue by nicklewis** [puppetlabs/bolt#2293]
## Describe the Change You Would Like

Functions that use the type aliases `TargetSpec` and `PlanResult` appear in the docs as `Boltlib::TargetSpec` and `Boltlib::PlanResult`, as that is the proper name of those types. However, we make additional aliases when running plan code to remove the need for the `Boltlib::` prefix as it's entirely an implementation detail of the way that Bolt uses Puppet. We should similarly strip `Boltlib::` from the docs. From the user's point of view, those types are called `TargetSpec` and `PlanResult` and we should universally refer to them as such.

**Comment by beechtom** [comment]
Updated #2285 to include this change.

**Comment by lucywyman** [comment]
Closed by #2285
