### ISSUE TITLE
Support alternate Forge for 'bolt module' workflow

### ISSUE THREAD

**Issue by nossralf** [puppetlabs/bolt#2303]
## Use Case
There is currently no way of specifying an alternate Forge URL when using the new `bolt module` workflow for managing module dependencies. This is [supported](https://puppet.com/docs/bolt/latest/bolt_project_reference.html#forge) in the older `bolt puppetfile` workflow, and something that is almost a necessity in a corporate environment where Bolt plans may rely on internal modules that cannot be published to the Puppet Forge.

We should make a new setting with the exact same structure and keys as `puppetfile` config option. It's called `module-install`.

We should also update bolt project migrate to update this setting to update `puppetfile` to `module-install`.

If you have the (`modules` or `module-install`) key and the `puppetfile` key you will get a warning to update the `puppetfile` key to `module-install` with `bolt project migrate`. It will not honor the puppetfile key. `module-install` should not be honored by `puppetfile` subcommands.

**Comment by op-ct** [comment]
> "In a corporate environment where Bolt plans may rely on internal modules that cannot be published to the Puppet Forge" 

It would be even more valuable to support git repos (and refs) for individual modules in these environments (as the older `bolt puppetfile` does)—it is much more common for corporate environments to serve modules from internal git repos than from private Puppet Forges.
