### ISSUE TITLE
Cache plugin for dynamic inventory.yaml

### ISSUE THREAD

**Issue by mcoenen** [puppetlabs/bolt#2313]
## Use Case
We're using a inventory.yaml which is fully dynamic (based on PuppetDB queries) and creates based on the dynamic output Bolt groups. As we have 3 external connection types (LDAP, IPA and external IPA) we have 3 PuppetDB queries to encapsulate our system landscape. As the PuppetDB is used we're always complete with our inventory.yaml, the current downside of this setup is that we have a huge delay before the Bolt command runs, as it needs to query and compile the data.

## Describe the Solution You Would Like
To minimize the wait time it would be greate to have a cache plugin with a TTL on it, so reducing the need at each Bolt command to run the queries and the delay which it causes. In the Bolt slack channel the following example was suggested:
```yaml
- targets:
    _plugin: cache
    ttl: 600m
    cache: cache/inventory.yaml
    source: source/puppetdb.yaml
```

## Describe Alternatives You've Considered
As alternative I was thinking about to have an option to export the dynamic output to a static inventory.yaml to be used. This static file would be used for execution by Bolt and on the background run a task to update the static file when necessary. But this is a complicated method of creating a cache.

## Additional Context
n/a

**Comment by nmaludy** [comment]
+1
