### ISSUE TITLE
Print plugin task output to debug, and ensure BoltSpec inventories with plugins work

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2336]
## Describe the Bug
We recently [removed logging plugin task output](https://github.com/puppetlabs/bolt/pull/2329) at info level because plugin output is often sensitive, however users still need to be able to develop and debug their plugins particularly with complicated inventories with nested plugins. We should log plugin task output at the trace level.

We should also verify that no changes are needed to BoltSpec - I suspect that if you use an inventory with plugins with BoltSpec and are running plans the mock executor will fail. We just need to add `run_task_with_minimal_logging` to the MockExecutor and write a test verifying this does fail in the current codebase, and does not fail with the function defined.
We should define this method on the Mock Executor just to avoid weird errors, and probably have it just call mock execs run_Task assuming it's not logging anything.

**Comment by adreyer** [comment]
I think this needs to be trace level so these don't land in the debug log.
