### ISSUE TITLE
Ruby stacktrace on bad Kerberos WinRM connection

### ISSUE THREAD

**Issue by bodgit** [puppetlabs/bolt#2378]
## Describe the Bug
I've just set up Bolt to run on all of our Windows estate using a query against PuppetDB to build the list of hosts. I'm using WinRM and relying on Kerberos for authentication. This works for most hosts but on a few hosts I get this error (reproduced against just one host):
```
$ bolt command run whoami --targets winrm://p-slo-vw011.aspectcapital.com:5985 --no-ssl 2>error.txt
Started on winrm://p-slo-vw011.aspectcapital.com:5985...
Failed on winrm://p-slo-vw011.aspectcapital.com:5985:
  Failed to connect to http://p-slo-vw011.aspectcapital.com:5985/wsman: gss_init_sec_context did not return GSS_S_COMPLETE: Unspecified GSS failure.  Minor code may provide more information
  Message stream modified
Failed on 1 target: winrm://p-slo-vw011.aspectcapital.com:5985
Ran on 1 target in 0.16 sec
```
It also generates a huge Ruby stacktrace which I'll attach separately and causes Bolt to abort. The reason for the error seems to be incorrect DNS entries where the DNS and hostname don't match up, but ideally Bolt shouldn't be abortinglike that.

## Expected Behavior
Just report the error and carry on.

## Steps to Reproduce
1. Connect to a Windows host using Kerberos WinRM where the hostname doesn't match DNS

## Environment
 - Version: 2.34.0
 - Platform: RHEL 7

## Additional Context
[error.txt](https://github.com/puppetlabs/bolt/files/5567893/error.txt)

**Comment by lucywyman** [comment]
Relevant line for posterity:
```
[0m/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/gssapi-1.3.0/lib/gssapi/lib_gssapi.rb:182: [BUG] Segmentation fault at 0x00007f2b00000000
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
```

Hm, it looks like this is a bug in the [gssapi gem](https://github.com/zenchild/gssapi) that's been reported [here to the Ruby lang](https://bugs.ruby-lang.org/issues/17005), [in this closed issue to lib_gssapi](https://github.com/zenchild/gssapi/issues/12), and re-raised as a new issue [on March 2, 2020](https://github.com/zenchild/gssapi/issues/30). I'm inclined to leave this issue open so anyone else who runs into it can comment. We can add this as a known issue to our issues page as well.

What transport were you using to connect out of curiosity?

**Comment by bodgit** [comment]
I'm using WinRM without any SSL currently. With any luck I'll work out what is causing the "message modified" error and then I shouldn't experience this stacktrace, I've managed to fix a few of the problem hosts already by ensuring DNS is sane.

**Comment by zenchild** [comment]
I updated [Issue 12](https://github.com/zenchild/gssapi/issues/12) in the gssapi code. There is a [branch](https://github.com/zenchild/gssapi/tree/bugfix/issue-12_segfault-on-gss_delete_sec_context) I was hoping someone could test to make sure that it solves the issue. I was able to validate the fix in two of my own environments.

**Comment by bodgit** [comment]
I can try this branch out tomorrow and see if it helps.

**Comment by bodgit** [comment]
That seems to have fixed it. I still get the message modified error, but it doesn't cause a segfault now.

**Comment by lucywyman** [comment]
Awesome, thanks so much @zenchild ! I'm going to close this issue, but happy to reopen if y'all need.

**Comment by zenchild** [comment]
I just cut version 1.3.1 and it should be out on rubygems now.
