### ISSUE TITLE
New local Transport configuration option: "use-localhost-magic"

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#2400]
## Use Case

From inventory, I want to be able to dynamically configure additional `local` Transport Targets with the same "magical" settings as the built-in `localhost` Target get.

## Describe the Solution You Would Like

A new local [Transport configuration](https://puppet.com/docs/bolt/latest/bolt_transports_reference.html) option: **`use-localhost-magic`**

* This suggestion came from @adreyer [over in the #bolt Slack](https://puppetcommunity.slack.com/archives/C7GP57T50/p1606237744029800) (:sparkles:thanks!:sparkles:). 
*  Setting this option would configure a `local` Transport with the same options & features as the `localhost` Target magically gets.  That includes:
   * Dynamically taking care of any platform-dependent settings
   * Setting interpreters to use the Bolt package's built-in executables, when available.

## Describe Alternatives You've Considered

* Currently, the only way to do something like this is from inside a Plan's logic, where you can get_target('localhost') and copy its config directly into new Target objects.
  * But it would be much nicer (and more portable) to take care of that within the inventory so everything can use it.

* I initially considered a Ruby API bolt plugin (like the built-in [RUBY_PLUGINS](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/plugin.rb#L134) such as [env_var](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/plugin/env_var.rb), [prompt](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/plugin/prompt.rb), etc.,) to return the `localhost` Target's configuration.  
   * However, there isn't a mechanism for integrating third-party Ruby API bolt plugins.
   * Even if implemented, the actual `_plugin` usage would probably be quite cumbersome.

## Additional Context

Slack discussion at https://puppetcommunity.slack.com/archives/C7GP57T50/p1606237461023300

**Comment by adreyer** [comment]
I'm not exactly sure what to call this

 `use-bolt-environment`

**Comment by lucywyman** [comment]
I think we want to make the magic default in Bolt 3.0 for the local transport, and add a transport option to turn off the magic. The magic, specifically, is the following config:
```
'local' => { 'interpreters' => { '.rb' => RbConfig.ruby } } 
'features' => ['puppet-agent']
```
We can add a transport option for the local transport `bundled-ruby`. That can be configured now, and just won't be made default until Bolt 3.0.

We should warn_once users using the local transport with a name other than 'localhost' that this default will get added. If users have the option added and set to false we should not issue the warning.

**Comment by op-ct** [comment]
> I think we want to make the magic default in Bolt 3.0 for the local transport, and add a transport option to turn off the magic. The magic, specifically, is the following config:
> 
> ```
> 'local' => { 'interpreters' => { '.rb' => RbConfig.ruby } } 
> 'features' => ['puppet-agent']
> ```
> 
> We can add a transport option for the local transport `bundled-ruby`. That can be configured now, and just won't be made default until Bolt 3.0.
> 
> We should warn_once users using the local transport with a name other than 'localhost' that this default will get added. If users have the option added and set to false we should not issue the warning.

Thanks, @lucywyman.  Regarding features: Besides `puppet-agent`, isn't there also some magic that also determines and adds the appropriate `shell` or `powershell` features for `localhost`?

**Comment by lucywyman** [comment]
There shouldn't be - that's all tied to the local transport itself, not localhost as a target by name. So if you have a target using the local transport, Bolt should see if it's a Windows host and print the correct configuration flags and use the right shell commands, etc. But that applies to all targets using the `local` transport.

`localhost` *is* the only target that automatically uses the `local` transport, and that'll still be true with these changes. Other targets need to have the `local` transport set, and then will pick up magic config.

Hope that clarifies? Is there any behavior you're seeing that doesn't align with that?
