### ISSUE TITLE
Clarify how Bolt runs locally vs remotely

### ISSUE THREAD

**Issue by hestonhoffman** [puppetlabs/bolt#2412]
We should clarify how Bolt runs locally vs remotely:
- Add a section/page for local execution: Bolt has a local transport that executed directly from the Bolt process. It can be set with the `local` protocol in the URL or by setting the transport explicitly.
- The target `localhost` has special defaults that cause it to use the local transport and Bolt's Ruby environment. In some cases, it may be necessary to ignore these options. For example, if trying to interact with a Ruby application installed locally outside of Bolt. In this case, a different target can be created that uses the local transport. For example: `local://myhost`.
- We refer to "remote targets" a lot when we mean "targets". We should only use "remote targets" if we're trying to distinguish that the target is remote in context (probably rarely).
- We use "localhost" often in commands where we're explaining remote operations. Unless we're documenting local operation, we should use generic target names like `linux.example.com`.
- I think linking to this from the inventory page works, maybe a note?

**Comment by op-ct** [comment]
In addition to targets, there are also [remote _tasks_](https://puppet.com/docs/bolt/latest/writing_tasks.html#writing-remote-tasks), which are special tasks that don't execute directly on their targets.  It might be worth noting the difference when discussing the local vs "remote" targets.
