### ISSUE TITLE
site-modules folder should be renamed to modules in Getting Started

### ISSUE THREAD

**Issue by constantdupuis** [puppetlabs/bolt#2417]
Hi,

I'm following the Getting Started guide for puppet bolt. 

I have installed it under WSL 2 with Ubuntu 20.04. Ad I had to export the **BOLT_PROJECT** environment variable to make it work.
Because my folder is world writable.

When I try to run the command to install apache.

`> bolt plan run apache::install -t containers`

I get the following error message, telling me that the 'apache::install plan doesn't exists.

`Could not find a plan named 'apache::install'. For a list of available plans, run 'bolt plan show'.`

Doing a `> bolt plan show` the end of the command output show where it look's for modules, and sites-modules is not in it.

`/mnt/c/Users/cdupuis/Dev/docker/docker-services/puppet-bolt/getting-started/my_project/modules:/mnt/c/Users/cdupuis/Dev/docker/docker-services/puppet-bolt/getting-started/my_project/.modules`

Once I rename the **site-modules** folder to **modules**, everything went well.

So, documentation should be updated to create a **modules** folder and not a **site-modules** folder.

Regards and have a good day,

Constant

**Comment by lucywyman** [comment]
Oh gosh, thanks for raising this! PR incoming.
