### ISSUE TITLE
Ship bolt puppet7 chocolatey packages

### ISSUE THREAD

**Issue by jpogran** [puppetlabs/bolt#2443]
## Use Case

When Bolt moves to using puppet 7 release streams, the download urls will change.

## Describe the Solution You Would Like

The urls in https://github.com/puppetlabs/puppet-chocolatey-packages/blob/2d6670fe4e63be7b3a36d4a5287e51a4f5c897e2/automatic/puppet-bolt/update.ps1#L5-L6 will need to be updated to include puppet7 release streams.

## Describe Alternatives You've Considered

n/a

## Additional Context

n/a

**Comment by lucywyman** [comment]
Closed by https://github.com/puppetlabs/puppet-chocolatey-packages/pull/27
