### ISSUE TITLE
Bolt Install on MacOS inconsistency 

### ISSUE THREAD

**Issue by conormurraypuppet** [puppetlabs/bolt#2459]
## Describe the Change You Would Like
The install bolt on MacOS section https://puppet.com/docs/bolt/latest/bolt_installing.html#installing-bolt-on-macos lists two options, homebrew or macOS installer.
The homebrew method pulled bolt version 2.0.0 
The macOS installer version pulled bolt version 2.37.0

Theres nothing to make clear that homebrew install is not kept up to date like the dmg version is. I was trying to follow the instructions to setup a bolt project at the time and because the bolt version homebrew installed wasn't up to date the commands were failing and it wasn't clear to me why.

**Comment by lucywyman** [comment]
What OSX platform are you on? We dropped support for OSX 10.11, 10.12, and 10.13 when we released Bolt 2.0 - with Homebrew it pulls in the latest supported version, but if you installed the 10.14 or 10.15 DMGs on an earlier platform it may still work and will pull in the latest, or 2.37.0. We list MacOS versions supported by the latest Bolt here: https://puppet.com/docs/bolt/latest/bolt_installing.html#installing-bolt-on-macos - would adding a note that installing with Homebrew on 10.11, 10.12, or 10.13 be helpful?

**Comment by lucywyman** [comment]
@conormurraypuppet This might have got dropped over the holidays, and I wanted to check in on it.

**Comment by conormurraypuppet** [comment]
Mac version: MacOS High Sierra v10.13.4, the outdated version must be my issue then. I did see that mention of 10.4 and 10.5 but thought it was only relevant if you were using the "Install Bolt with macOS installer" option rather than the "Install Bolt with Homebrew" option I went for.

**Comment by lucywyman** [comment]
Ah, ok. We can definitely update https://puppet.com/docs/bolt/latest/bolt_installing.html#installing-bolt-on-macos to clarify that.

**Comment by beechtom** [comment]
Closed by #2617
