### ISSUE TITLE
Add CONTRIBUTING docs to bundled modules

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2472]
## Describe the Change You Would Like
Several of Bolt's bundled modules, such as terraform and http_request, do not including documentation on contributing changes to the modules. This can make working on the module tricky for users, particularly if the user expects to be able to run spec tests through pdk and the module isn't set up to support that workflow. We should add a CONTRIBUTING doc to our modules that describe how to make changes, including how to run spec tests locally. The document can be the same for each module as long as the information is still correct for that module. THis should include a link to the puppet code of conduct, instructions on testing changes, how to submit issues and prs, mostly the same information that's in Bolt's CONTRIB doc.

**Comment by lucywyman** [comment]
List of repos:
- [ ] puppetlabs/bolt-getting-started
- [ ] puppetlabs/puppetlabs-aws_inventory
- [ ] puppetlabs/puppetlabs-azure_inventory
- [ ] puppetlabs/puppetlabs-facts
- [ ] puppetlabs/puppetlabs-gcloud_inventory
- [ ] puppetlabs/puppetlabs-http_request
- [ ] puppetlabs/puppetlabs-pkcs7
- [ ] puppetlabs/puppetlabs-puppet_agent
- [ ] puppetlabs/puppetlabs-python_task_helper
- [ ] puppetlabs/puppetlabs-ruby_task_helper
- [ ] puppetlabs/puppetlabs-secure_env_vars
- [ ] puppetlabs/puppetlabs-terraform
- [ ] puppetlabs/puppetlabs-vault
- [ ] puppetlabs/puppetlabs-yaml

**Comment by lucywyman** [comment]
I think this is safe to close - we can talk with Night's Watch separately if they have an issue with the code of conduct.
