### ISSUE TITLE
Bolt does not work in Windows 2008 R2

### ISSUE THREAD

**Issue by joshidiv04** [puppetlabs/bolt#2485]
## Describe the Bug
Importing bolt modules reports error

## Steps to Reproduce
1. Install bolt in Windows 2008 R2 machine
2. Update powershell profile using command 
'Import-Module -Name ${Env:ProgramFiles}\WindowsPowerShell\Modules\PuppetBolt' | Out-File -Append $PROFILE

## Environment
 - Version [2.38.0]
 - Platform [Windows 2008 R2]

**Comment by joshidiv04** [comment]
Error Message: 
"You must provide a value expression on the right-hand side of the '-' operator.
At C:\Program Files\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psm1:54 char:19
+     if ($kvp.Key - <<<< in $common) {
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression

Import-Module : The module to process 'PuppetBolt.psm1', listed in field 'ModuleToProcess' of module manifest 'C:\Progr
am Files\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psd1' was not processed because no valid module was found in a
ny module directory.
At C:\Users\installer\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1 char:14
+ Import-Module <<<<  -Name ${Env:ProgramFiles}\WindowsPowerShell\Modules\PuppetBolt
    + CategoryInfo          : ResourceUnavailable: (PuppetBolt:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand"

**Comment by jpogran** [comment]
Windows 2008R2 comes with PowerShell V2 pre-installed, which does not support the `-in` keyword. You can upgrade to PowerShell 3.0 or greater on the machine you're running Bolt on and that will fix this issue.

As a general FYI, Microsoft has set the EOL for Windows 2008R2 to [Jan 2020](https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2) and Puppet will be removing explicit support from its products in Jan 2020. This means while Puppet products may still work on Windows 2008, we are not actively testing against that platform. 

In addition, Microsoft has officially [deprecated PowerShell v2.0](https://devblogs.microsoft.com/powershell/windows-powershell-2-0-deprecation/) and advised all customers to move to PowerShell 5.1.

**Comment by jpogran** [comment]
I'm going to close this out, but if any further problem arises please feel free to open an issue
