### ISSUE TITLE
Run sudo with -i/--login so profiles are loaded.

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2486]
## Use Case
Currently when using Bolt to run commands/scripts and specifying `run-as` option to elevate the privileges `sudo` is used. By default, `sudo` doesn't run a login shell causing things placed into `/etc/profile.d/*` to not be loaded. This causes problems for things like `puppet`, `rvm`, etc (we have other examples of similar internally). 

With the current implementation we need to do things like the following on Linux:
```shell
bolt command run '/opt/puppetlabs/bin/puppet xxx' --targets xxx
````

On Windows the PATH is setup and global so doing the following works out of the box:
```shell
bolt command run 'puppet xxx' --targets xxx
````

## Describe the Solution You Would Like
Login shells can be invoked with sudo by passing in the `-i/--login` option, most likely right here: https://github.com/puppetlabs/bolt/blob/main/lib/bolt/shell/bash.rb#L343

## Describe Alternatives You've Considered
We could also customize this by doing our own `run-as-command`, but i think this would be useful for others.

I wanted to put this up for discussion before creating a PR in case there was some reason we didn't want to start passing in `-i/--login`?

**Comment by lucywyman** [comment]
Hm, this would have at least a few side effects I can think of that might not be desirable:
1. It would cd to the sudo users home dir for the local transport, which currently executes in the directory you ran Bolt from.
2. This is very edge case, but "As a special case, if sudo's -i option (initial login) is specified, sudoers will initialize the environment regardless of the value of env_reset. The DISPLAY, PATH and TERM variables remain unchanged; HOME, MAIL, SHELL, USER, and LOGNAME are set based on the target user. On AIX (and Linux systems without PAM), the contents of /etc/environment are also included. On BSD systems, if the use_loginclass flag is enabled, the path and setenv variables in /etc/login.conf are also applied. All other environment variables are removed." ([source](https://www.sudo.ws/man/1.8.17/sudoers.man.html)). This is less compelling, but seems hard to debug if anything goes wrong.

I'm still open to it if other folks in the community want this by default, but I'm kind of leaning towards just documenting the `run-as-command` case on our troubleshooting page?

Another (I think worse...) option might be to have a `preserve_path` config setting that would append `env 'PATH=$PATH` to the sudo command, to address just the pathing issue. That seems useful for solving this without the side effects and providing a way to opt-in, but I'm not too keen to add even more configuration options...
