### ISSUE TITLE
Command to lookup value with Hiera

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2499]
## Use Case

Bolt supports the `lookup()` Puppet function in plans, both inside and outside of apply blocks. However, checking which value Hiera will return for a given key can be difficult with Bolt, as there is no command available to perform a lookup. Being able to do a lookup with Hiera with a Bolt command would make it easier for users to know which values are returned given specific inputs. It would be especially helpful if a user could also use the Bolt command to check what value a lookup using the `hierarchy` config would return vs. the `plan_hierarchy` config, as they can return different values.

## Describe the Solution You Would Like

Similar to the `puppet lookup` command, Bolt should have a `bolt lookup` command. This command should accept a positional argument that is the `key` to lookup.

```shell
bolt lookup foo
```

### Lookups using `plan_hierarchy`

**Should this command support lookups using `plan_hierarchy`?**
Most likely. Looking up values for plan_hierarchy seems like the most common use case for this command, as the `puppet lookup` command is not a substitute.

**Lookups using `plan_hierarchy` currently support interpolation. How should Bolt handle specifying variables for interpolation?**
Similar to specifying parameters to a plan. These can then be passed along to the compiler and set in scope. Variables could be passed using `var=value` syntax or as a JSON file.

```shell
bolt lookup foo foo=value1 bar=value2
```

```shell
bolt lookup foo --vars vars.json
```

### Lookups using `hierarchy`

**Should this command support lookups using `hierarchy`?**
Possibly. `puppet lookup --confdir <project>` may be a suitable substitute. However, this does require users who only use Bolt to use Puppet, which isn't great if we want Bolt to have a 'complete' experience.

**Lookups using `hierarchy` support interpolation using facts. How should Bolt handle specifying facts for interpolation?**
A few ways to do this. If using real facts, Bolt will need to fetch facts for the targets first. This is easy enough to do by running the facts task and setting them on the targets before performing the lookups. We could also support specifying facts, which would be helpful for users to test return values for specific facts.

To pass facts we could potentially pass them similar to passing parameters to a plan. We could also support passing facts as a JSON file, which is a pattern already used by `puppet lookup`.

```shell
bolt lookup foo --targets all os.version=1 os.name=linux
```

```shell
bolt lookup foo --targets all --facts facts.json
```

If retrieving real facts for targets, should Bolt install the puppet-agent package beforehand, or just run the facts task (this may result in the shell or powershell implementation being used, which returns a small subset of facts)? Is retrieving real facts the default, or optional? If optional, we could have an option:

```shell
bolt lookup foo --targets all --real-facts
```

### Command syntax

The syntax of the command is dependent on what this command supports. Assuming the command supports both hierarchies, we might want the following options:

- `--hierarchy`*
  Accepts either `hierarchy` or `plan_hierarchy`. Defaults to one of these.
- `--targets`
  Accepts a list of targets. Used for `hierarchy` lookups.
- `--vars`
  Accepts a path to a JSON file specifying variables to use in interpolation. Used for `plan_hierarchy` lookups.
- `--facts`
  Accepts a path to a JSON file specifying facts to use in interpolation. Used for `hierarchy` lookups.
- `--real-facts`
  Tells Bolt to retrieve a targets real facts. Used for `hierarchy` lookups.

## Example command usage

Following is what use of this command might look like and what the output would be:

```shell
$ bolt lookup foo --targets all --hierarchy hierarchy
Finished on localhost:
  Hello from data/Darwin.yaml!
Finished on nix:
  Hello from data/Ubuntu.yaml!
Finished on win:
  Hello from data/windows.yaml!
Successful on 3 targets: localhost,nix,win
Ran on 3 targets in 3.94 sec
```

```shell
$ bolt lookup bar --targets all --hierarchy hierarchy
Failed on localhost:
  Function lookup() did not find a value for the name 'bar'
Failed on nix:
  Function lookup() did not find a value for the name 'bar'
Failed on win:
  Function lookup() did not find a value for the name 'bar'
Failed on 3 targets: localhost,nix,win
Ran on 3 targets in 3.99 sec
```

## Solution
- For now, we'll just focus on the targets use case (so, not `plan_hierarchy) because `plan_hierarchy` requires a context to run in, plus only incidentally supports interpolations so for just flat data this seems less useful than lookups from the `hierarchy`.
- This command should do an entire apply_prep for targets and then do a lookup
- We could have another libexec `bolt_lookup` that sets up Hiera and does the lookup.
- Don't have to serialize the scope, just facts.
- Experiment with interpolating target variables and trusted data and demo at standup

**Comment by trevor-vaughan** [comment]
I too would like to know what the thing is if I can't figure out what the thing might be
