### ISSUE TITLE
Only output colors/spinners if running in a TTY environment

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2500]
## Use Case
We often run Bolt in our CI/CD pipelines so that our workflows are portable across platforms and on to our laptops (amazing for that by the way!). However, currently when run inside of a CI/CD platform (in this case Jenkins) we see some crazy output when spinners are active, printing out each character in sequence along with the literal ANSI escape colors.

Example:
```
[0m/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-  → Generating type references
```
In this output you can see the ANSI escape sequence along with the spinner characters printed.

## Describe the Solution You Would Like
Potentially auto-detect if the process is running in a TTY and disable spinners and colors if so?

## Describe Alternatives You've Considered
We could turn them off manually in the config

**Comment by nmaludy** [comment]
@beechtom i saw @lucywyman 's PR fixes spinners, but didn't see anything about colors... thoughts there? should i make a separate issue for colors?

**Comment by nmaludy** [comment]
Yeah, here is an example from the Jenkins console:
```
[33mCommand line option '--boltdir' is deprecated, use '--project' instead.[0m
```
![image](https://user-images.githubusercontent.com/3693851/102654276-48cb6880-413e-11eb-87d1-ad72cd59fde8.png)

**Comment by lucywyman** [comment]
Oh I see what's happening - that message is actually coming from our logger, not the outputter (which is where the spinner and most messaging goes though). The Outputter checks that the stream is a TTY before printing with color (and that color is configured to true), but the Logger *only* uses the configured color and doesn't check that console is a TTY. You should be able to use `--no-color` on the CLI in CI and have it be respected at least - I'm a little surprised the Ruby logging library doesn't just handle this. We can spike on if it's something we can fix, but I'm not sure we'll prioritize it :slightly_frowning_face:

**Comment by beechtom** [comment]
We can probably wrap this line https://github.com/puppetlabs/bolt/blob/main/lib/bolt/logger.rb#L27-L36 with `if $stdout.tty?`

**Comment by beechtom** [comment]
I think updating this line https://github.com/puppetlabs/bolt/blob/main/lib/bolt/logger.rb#L44 might work:

```ruby
layout: console_layout(color && $stdout.tty?)
```
