### ISSUE TITLE
Permission denied errors

### ISSUE THREAD

**Issue by blackknight36** [puppetlabs/bolt#2508]
## Describe the Bug
When running bolt as a non-root user warning messages are shown on the console as follows.

```
10:36 $ bolt task show
Command /usr/sbin/dmidecode --type 1,2,3 resulted with the following stderr message: /sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Command /usr/bin/ipmitool lan print resulted with the following stderr message: Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
```

## Environment
 - CentOS 7.9 x86_64
 - bolt version 2.40.2

**Comment by lucywyman** [comment]
Interesting! This is particularly interesting that it's happening for `bolt task show`, which shouldn't be executing much code. I'm not seeing anywhere that we call dmidecode in Bolt or Puppet, but when we load tasks it looks like we do load and evaluate custom datatypes and facts. I tentatively suspect there's a datatype or fact in one of the modules being loaded that's trying to call dmidecode and erroring, but it could be something else. It looks like [vmware-tools](https://github.com/craigwatson/puppet-vmwaretools/blob/2b341fb7b3223b4aa7e7c8844864613e64e329a7/lib/facter/esx_version.rb) is a popular module that calls dmidecode, but it could be something else.

Would you mind posting your Puppetfile contents or a list of modules that are on your modulepath?

**Comment by beechtom** [comment]
This _might_ be a Facter bug that is surfaced when using Facter to compute the controller's OS: https://github.com/puppetlabs/bolt/blob/main/lib/bolt/analytics.rb#L213

**Comment by blackknight36** [comment]
I checked our modules and the only one that uses dmidecode is puppetlabs-postgresql.  Here is what I could find using grep.

https://gist.github.com/blackknight36/d3873779e27bed465bfe34d6545f16b1

**Comment by lucywyman** [comment]
Ah, the gist is very telling! I'm not sure how or why, but it seems like that module is using facter 2.5.5....I'm still not quite sure how that would impact loading for `bolt task show`, but I'd try to just remove `puppetlabs-postgresql/.bundle/` altogether (it shouldn't be needed, or if it is I just checked and the latest of that module pulls in Facter 4.0.47 which is latest) and see if that solves it.

**Comment by blackknight36** [comment]
> Ah, the gist is very telling! I'm not sure how or why, but it seems like that module is using facter 2.5.5....I'm still not quite sure how that would impact loading for `bolt task show`, but I'd try to just remove `puppetlabs-postgresql/.bundle/` altogether (it shouldn't be needed, or if it is I just checked and the latest of that module pulls in Facter 4.0.47 which is latest) and see if that solves it.

Sorry, the gist is a bit misleading since it comes from a copy of the postgresql module which is not used by bolt.  Here are the modules shown by the bolt puppetfile command.

```
Packaged Modules
  aggregate                       (built-in)
  puppetlabs/augeas_core          1.1.1
  puppetlabs/aws_inventory        0.5.2
  puppetlabs/azure_inventory      0.4.1
  canary                          (built-in)
  puppetlabs/cron_core            1.0.5
  puppetlabs/facts                1.2.0
  puppetlabs/gcloud_inventory     0.1.3
  puppetlabs/host_core            1.0.3
  puppetlabs/http_request         0.2.1
  puppetlabs/mount_core           1.0.4
  puppetlabs/package              1.3.0
  puppetlabs/pkcs7                0.1.1
  puppetlabs/puppet_agent         4.2.0
  puppetlabs/puppet_conf          0.6.0
  puppetdb_fact                   (built-in)
  puppetlabs/python_task_helper   0.4.3
  puppetlabs/reboot               3.0.0
  puppetlabs/ruby_plugin_helper   0.1.0
  puppetlabs/ruby_task_helper     0.5.1
  puppetlabs/scheduled_task       2.2.1
  puppetlabs/secure_env_vars      0.1.0
  puppetlabs/selinux_core         1.0.4
  puppetlabs/service              1.3.0
  puppetlabs/sshkeys_core         2.2.0
  puppetlabs/stdlib               6.5.0
  puppetlabs/terraform            0.5.0
  puppetlabs/vault                0.3.0
  puppetlabs/yaml                 0.2.0
  puppetlabs/yumrepo_core         1.0.7
  puppetlabs/zfs_core             1.2.0
  puppetlabs/zone_core            1.0.3
```

**Comment by blackknight36** [comment]
It appears that this is no longer an issue.  Running the same command does not produce any errors.  Here is the version info from my system.

19:29 $ puppet --version
6.21.1

19:29 $ facter --version
3.14.16 (commit d3b0a04d6722084993ab2dd3ee4180718ad71942)

19:29 $ bolt --version
3.7.0
