### ISSUE TITLE
Improve error messages for Powershell-based tasks

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/bolt#2509]
## Use Case
Due to the way the builtin `shell_init` block is [concatenated](https://github.com/puppetlabs/bolt/blob/main/lib/bolt/shell/powershell.rb#L278) with the actual Powershell script for .ps1 tasks, the error message from a syntax error in the .ps1 script can be very confusing:

```
Error: The task failed with exit code 1 and no stdout, but stderr contained:
$installRegKey = Get-ItemProperty -Path "HKLM:\Software\Puppet Labs\Puppet" -ErrorAction 0
 : System.Management.Automation.RuntimeException: Unable to find type [Integer].
```

Here, the error message from the script syntax error is `Unable to find type [Integer]`, however this gets associated to the script line `$installRegKey = Get-ItemProperty -Path "HKLM:\Software\Puppet Labs\Puppet" -ErrorAction 0` which is from the builtin `shell_init` block.

This is a worse case scenario as the error was in the `Param()` section at the start of the .ps1 task, so no other error output is provided in this case that could help point to the script as the culprit, instead of something in Bolt.

## Describe the Solution You Would Like
In the error output, please make a clear divide as to where script execution started, vs any builtin initialisation work. If an error occurs, it should be clear whether that's coming from built-in code or the actual task itself.

## Additional Context
@jpogran has some ideas on possible ways to improve the situation

## Solution (for now)
- We want to clarify that this is an error with the original PowerShell task, we should use PowerShell's error type to get the file and line to print a better error.

**Comment by jpogran** [comment]
@kreeuwijk I worked on this today, and was able to reduce the error to the following:

```
❯ be bolt task run exceptiontest::foo -t localhost
Started on localhost...
Failed on localhost:
  The task failed with exit code 1 and no stdout, but stderr contained:
  Unable to find type [Integer]. at At
  C:\Users\james\AppData\Local\Temp\cnyz2mjz.ezi\foo.ps1:2 char:3
  +   [Integer]$foo
  +   ~~~~~~~~~
  At line:210 char:3
  +   throw "$($_.Exception.Message) at $($_.InvocationInfo.PositionMessa ...
  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OperationStopped: (Unable to find ...
  +   ~~~~~~~~~:String) [], RuntimeException
      + FullyQualifiedErrorId : Unable to find type [Integer]. at At C:\Users\james\AppD

     ata\Local\Temp\cnyz2mjz.ezi\foo.ps1:2 char:3
  +   [Integer]$foo
  +   ~~~~~~~~~

Failed on 1 target: localhost
Ran on 1 target in 1.61 sec
```

The first part is the formatted exception I added, the second part is PowerShell handling the error sent to sterr. I haven't figured out how to remove that part yet, not sure I will be able to, but I wanted to get early feedback on this from you.

**Comment by kreeuwijk** [comment]
@jpogran this looks a lot better, great work James!

It would indeed be great to get rid of the stuff from `At line:210 char:3`, but that could be tricky to accomplish. At least this new message format will point directly to the erroneous task script itself to start with, which is a big improvement.
