### ISSUE TITLE
Allow apply-settings to specify any Puppet setting 

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2516]
## Use Case
I'm writing some Puppet code and the returned error message why applying my catalog via bolt was:
```shell
Failed on matrixchat:
  Resources failed to apply for matrixchat
    Synapse_user[nick]: bad URI(is not URI?): nil
  changed: 0, failed: 1, unchanged: 79 skipped: 0, noop: 0
```

I wanted to turn on `--debug` and `--trace` and maybe even `--evaltrace` for the `apply()` so i could see what was going wrong and where (i had already added `Puppet.debug()` statements into my code).

Trying to set the following in `bolt-project.yaml` didn't work:
```yaml
apply-settings:
  log_level: 'debug'
  trace: true
  evaltrace: true
```

I was presented with the following warning by Bolt:
```shell
Unknown option 'log_level' at 'apply-settings' at /home/nmaludy/xxx/bolt-project.yaml.
Unknown option 'trace' at 'apply-settings' at /home/nmaludy/xxx/bolt-project.yaml.
Unknown option 'evaltrace' at 'apply-settings' at /home/nmaludy/xxx/bolt-project.yaml.
```

## Describe the Solution You Would Like
It would be great if `apply-settings` could apply any Puppet settings that are possible!

## Describe Alternatives You've Considered
Maybe some additional options on the `apply` function that could automatically turn on debug and trace output for me, then print it in a "pretty" way.

## Additional Context
I was able to hack `apply_catalog.rb` and was able to modify it like so to get the output i needed:
```
args['apply_settings'].each do |setting, value|
  Puppet[setting.to_sym] = value
end

Puppet[:trace] = true
Puppet[:evaltrace] = true
Puppet[:log_level] = 'debug'
```

**Comment by adreyer** [comment]
Have a defined list of options decreases the support and deprecation burden enough that we'd like people to keep submitting tickets or PRs to expand the options for apply_settings.

**Comment by nmaludy** [comment]
That's good with me!
