### ISSUE TITLE
Tasks and plans link is a 404

### ISSUE THREAD

**Issue by zymergen-vdc** [puppetlabs/bolt#2539]
on [Connecting Bolt to Puppet Enterprise](https://puppet.com/docs/bolt/latest/bolt_configure_orchestrator.html) the link for [Tasks and plans](https://puppet.com/docs/pe/latest/running_tasks_and_plans_pe.html) is dead

**Comment by lucywyman** [comment]
Thanks! Looks like that should probably be https://puppet.com/docs/pe/2019.8/bolt_to_pe_overview.html
