### ISSUE TITLE
file download scp - use wildcard/glob in source file

### ISSUE THREAD

**Issue by marcelfischer** [puppetlabs/bolt#2540]
## Describe the Bug
I try to download a file via ssh transport like this:
bolt file download /tmp/\*.tgz foo/ -t servername --transport ssh
Started on servername...
Failed on servername:
  SCP did not finish successfully (1): scp: /tmp/\*.tgz: No such file or directory
Failed on 1 target: servername
Ran on 1 target in 0.4 sec

## Expected Behavior
bolt should support glob pattern like normal scp command

## Steps to Reproduce
1. use bolt file download with ssh transport

## Environment
 - Version 2.35.0
 - Platform RHEL7.9

**Comment by breca** [comment]
Still an issue as of version 3.27.2

The lack of this capability is especially noticeable If I'm doing something like running a vendor script via `bolt script run` as root that generates some output with a randomised or node-specific filename(s).

I want to be able to simply `bolt file download /root/*blah*.txt --run-as root`, but now I have to use `bolt command` to mv/cp the file to another location, chown it, then use scp to get the files I need.
