### ISSUE TITLE
Bolt is very slow when applying Manifests

### ISSUE THREAD

**Issue by fionera** [puppetlabs/bolt#2546]
## Describe the Bug
Bolt is very slow

## Expected Behavior
Not take an hour to apply

## Steps to Reproduce
1. Take a big Manifest
2. Apply it onto the node

## Environment
 - Version: 2.19.0
 - Platform: Arch Linux

## Additional Context
I just started using Bolt for setting up VMs that dont have Access to our Puppet Master, but it is very slow. The last run took one hour:

```
  changed: 346, failed: 11, unchanged: 471 skipped: 1616, noop: 0
Finished: apply catalog with 1 failure in 3596.72 sec
Failed on 1 target: s190
Ran on 1 target in 1 hr, 0 min, 30 sec
```

When I deploy the same machine via the Puppet Provisioner in Vagrant it only takes at max 15 minutes

**Comment by adreyer** [comment]
Does the vagrant provisioner successfully apply the manifest without failures? Are there large files in the modules? 
Can you run with `--log-level trace` and see where it hangs?

**Comment by gucki** [comment]
@adreyer I have the same issue - bolt is taking about 5 minutes to deploy. It deploys successfully witout any errors. `--log-level trace` doesn't really help, because it only prints a lot at the beginning and then just hangs for a long time in "Executing `/tmp/7e5f60e6-0e4b-4fd3-b205-af3899bb3430/apply_catalog.rb` without printing any details what bolt is doing...

**Comment by itszn** [comment]
@adreyer Same issue here...
To sanity check I added a `$stderr.puts()` call at the very top of the `apply_catalog.rb` file.

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

$stderr.puts("Requiring gems...")

require 'fileutils'
...
```

It takes it several min from starting to execute `apply_catalog.rb` to actually hitting the print.... I have no idea what it could be doing? Trying to bring up the ruby env/interpreter??

Anyone have any idea what the startup time for `apply_catalog.rb` can be attributed to? I see no CPU usage from the process during this time.

```
3:15:12 Executing `sudo -S -H -u root -p \[sudo\]\ Bolt\ needs\ to\ run\ as\ another\ user,\ password:\  sh -c echo\ 4fc9ede3-462a-43fb-bec1-7df0b5d3b6f0\ 1\>\&2\;\ cd\;\ /tmp/79ee67f8-f5ea-4d3e-a17d-af5775c5c0da/apply_catalog.rb`
3:19:32 [target_host] err: Requiring gems...
```

I had expected that it was the cost of transferring the files, but that doesn't happen until the `args = JSON.parse(ARGV[0] ? File.read(ARGV[0]) : $stdin.read)` further down the script and doesn't get executed until after this 3-4 min startup delay, so it is not hanging on that as far as I can tell.
