### ISSUE TITLE
Ship with Ruby 2.7.2

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2548]
## Use Case
Ship Bolt packages with Ruby 2.7.2

- [ ] Update bolt-runtime puppetlabs/puppet-runtime#414 puppetlabs/puppet-runtime#419
- [x] Update Bolt for testing in and targeting 2.7 #2604

**Comment by jpogran** [comment]
Set 2.7.2 in https://github.com/puppetlabs/bolt/pull/2291
