### ISSUE TITLE
wait_until_available function along with options needs a bit of clarification

### ISSUE THREAD

**Issue by jordi-garcia** [puppetlabs/bolt#2572]
Hi,

Currently, [wait_until_available.rb](https://github.com/puppetlabs/bolt/blob/1e39049fe349d6c8fba5a0c59ad617119eabd62a/bolt-modules/boltlib/lib/puppet/functions/wait_until_available.rb) covers the description for the ``wait_until_available`` function as ``Wait until all targets accept connections``. Based on customer feedback [Support Ticket](https://puppetlabs.zendesk.com/agent/tickets/42828) and my view as part of the research on this ticket, the ``wait_until_available`` function could do with a bit of clarification (e.g. add the typical use case `waiting for remote hosts to reboot`). Furthermore, `wait_time` and `retry_interval` options for ``wait_until_available`` function lack the specific unit of mesuare in its description. It is implied that seconds is the unit of mesuare but we need to detail it in our documentation in order to avoid any confusion.

Best regards,
Jordi Garcia

**Comment by beechtom** [comment]
Closed by #2573
