### ISSUE TITLE
Support additional Puppet parameters in apply-settings

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2575]
## Use Case
Running puppet using `puppet agent -t` is quite common.
I think it would be great if the settings available in `-t/--test` were available in `apply-settings` so we could tweak the output to match.

```
* --test:
  Enable the most common options used for testing. These are 'onetime',
  'verbose', 'no-daemonize', 'no-usecacheonfailure', 'detailed-exitcodes',
  'no-splay', and 'show_diff'.
```

## Additional Context
https://github.com/puppetlabs/bolt/issues/2516

**Comment by adreyer** [comment]
we support `show_diff` and `log_level` which is more a more general `verbose`  everything else seems specific to `agent` rather then `apply`

**Comment by adreyer** [comment]
I don't think there is anything left to do with this.
