### ISSUE TITLE
parameter 

### ISSUE THREAD

**Issue by tdtheautomator** [puppetlabs/bolt#2582]
## Describe the Change You Would Like
A clear and concise description of what you would like changed.
looks need to mention explicitly the case of the task parameter must be lowercase

**Comment by beechtom** [comment]
@tdtheautomator Thanks for opening this issue. We have an existing issue to document task parameter constraints (https://github.com/puppetlabs/bolt/issues/2240) so I'm going to close this as a duplicate.
