### ISSUE TITLE
get_targets('host1', 'host2', 'hostred', 'hostblue') no longer works

### ISSUE THREAD

**Issue by GMZwinge** [puppetlabs/bolt#2591]
## Describe the Change You Would Like
In [Writing plans in the Puppet language](https://puppet.com/docs/bolt/latest/writing_plans.html), section [Creating target objects](https://puppet.com/docs/bolt/latest/writing_plans.html#creating-target-objects), the example `$target_list = get_targets('host1', 'host2', 'hostred', 'hostblue')` no longer works. It gives this error:
```
{
  "kind": "bolt/pal-error",
  "msg": "'get_targets' expects 1 argument, got 4",
  "details": {
    "file": "<path>/<module>/plans/plan.pp",
    "line": <n>,
    "column": <n>
  }
}
```

**Comment by beechtom** [comment]
@GMZwinge The `get_targets` function expects a `TargetSpec`. This can be either a `String`, a `Target`, or an `Array[TargetSpec]`. You can wrap those target names in an array, and the function will work.

```
$target_list = get_targets(['host1', 'host2', 'hostred', 'hostblue'])
```

https://puppet.com/docs/bolt/latest/plan_functions.html#get-targets
