### ISSUE TITLE
Writing your first task page

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/bolt#2619]
## Describe the Change You Would Like

I think we need a “Writing your first task” page. That goes something like this.  

When you are getting started with bolt getting your inventory setup so you can connect to different hosts can be its own job to tackle.  In order for you to understand how bolt works we’re going to write a task to run locally against your machine ( don’t worry, we won’t do anything destructive).

Let’s say we want to see the contents of the /tmp directory.  We can run ls -l /tmp to see what’s in there.  First we can run that as a script

```
echo 'ls -l /tmp' > scripts/list_tmp.sh
bolt script run scripts/list_tmp.sh
```

<show output>

Now that’s great but in order to make this more flexible maybe we want to allow our users to choose which directory they want to list the contents of.  That’s where a task comes in

now we’ll change the script to accept an environment variable for the directory and add a new metadata file that will describe what we call a task so the user knows what parameters they can change .

<show changes to script>
<show metadata.json>

`bolt task run list_tmp --dir = /tmp/foo`

<show output >

This is great it works!! However, when you are trying to make a task you might make mistakes and it might fail.  Tasks capture stderr separately and that can be confusing when you are expecting  the output from the task to look like what you are used to seeing when you run commands or scripts directly on the CLI.

So you should try one of the following options to debug your task when it’s not working.
 - run it as a script
 - run bolt task run <some extra args that help debug it>

<Show adding in an error to the script>
<show the output of the above options indicating to users how they can do this themselves>

Now you'll know how to troubleshoot your task if you introduce any issues along the way!

**Comment by adreyer** [comment]
I don't think we should frame it like this. There is no reason to write a task to test inventory you should be doing that with a command or a built in task. We should frame tasks as the building blocks of complex plans that rely on structured input and output and we generally should't encourage users to write tasks that purely dump text to stdout.

**Comment by npwalker** [comment]
This isn't a task to test inventory it's just a task that doesn't need to rely on inventory.  Something one can write that doesn't require anything other than their local machine.  

I'm fine with a different example but it should run on the machine without changing anything and it should then we something we can introduce an error into and talk about how to troubleshoot that.

**Comment by hestonhoffman** [comment]
I don't think it makes sense to create a "Getting started" doc just to handle troubleshooting. It makes more sense to call out troubleshooting in the dedicated task docs. I'll be looking at the tasks docs soon - possibly in combination with the script stuff that the team is working on. I'll work on improving this in the docs and possibly include a "Writing your first task" doc if it turns out we still need one.
