### ISSUE TITLE
I want to restart a plan that failed partway though

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2622]
## Use Case
It's painful to start a slow plan over when a step fails. There should be a way to investigate the problem and restart the plan from where it failed. This can be useful either for debugging a plan or avoiding costly steps during production plan use.

## Describe the Solution You Would Like
You should be able to restart a plan with `bolt plan run --start-at<step-name>` and any step before that name should be skipped. For yaml plans this should be the actual step name for puppet language plans we can consider a `step` function.

see the peadmin::plan_step function https://github.com/puppetlabs/puppetlabs-peadm/blob/main/plans/convert.pp#L19-L27

## Questions
Do we need to support caching step values? This is easy to handle in puppet language by not returning from the step function but in yaml naming a step means it's value can be used later and we may get ugly errors.
How do we deal with steps in subplans?
How do we deal with duplicate step names?

**Comment by reidmv** [comment]
Just finished a day-long repeated fail & resume session. Another thing that would be hugely useful: a flexible `--skip-steps` option which could accept an array/csv of individual steps or ranges to omit when running a plan.
