### ISSUE TITLE
Unable to pass sensitive parameters from plans to tasks.

### ISSUE THREAD

**Issue by gsparks** [puppetlabs/bolt#2630]
## Describe the Bug
When running a plan from within a module that calls a task with a Sensitive parameter, Bolt does not understand how to pass a sensitive plan parameter to a sensitive bolt parameter. A generic error is produced.

{
    "msg": "Plan aborted: run_task 'servicenow_tasks::create_ci' failed on 1 target",
    "kind": "bolt/plan-failure",
    "details": {
        "class": "Bolt::RunFailure"
    }
}

Removing the sensitive key on the task metadata for the parameter in question resolves the error.

Unwrapping the sensitive parameter in the task seems to have no effect.

## Expected Behavior
Sensitive parameters should be able to be passed from plans to tasks.

## Steps to Reproduce
1. Create a module with a plan that takes a sensitive parameter.
2. Call a task via run_task from the plan above and pass the sensitive parameter from the plan to the task.
3. Ensure the sensitive metadata key for the parameter in question is true.
4. Attempt to run the plan.

## Environment
 - Ubuntu 18.04.4 LTS
 - PE 2019.8

## Additional Context
Reversing the Optional and Sensitive tags on parameter metadata produces a different error.

{
    "msg": " Task parameters are not of type Data. run_task() variant 0 expects a ScalarData value, got Struct\n  Task parameters are not of type Data. run_task() variant 1 entry 'password' expects a Data value, got Sensitive\n  Task parameters are not of type Data. run_task() variant 2 expects an Array value, got Struct (file: /opt/puppetlabs/puppet/modules/servicenow_tasks/plans/create_ci_with_query.pp, line: 20)",
    "kind": "bolt/plan-failure",
    "details": {
        "class": "Bolt::PAL::PALError"
    }
}

**Comment by donoghuc** [comment]
I think this is expected behavior. It is documented you must unwrap it. https://puppet.com/docs/bolt/latest/writing_plans.html#working-with-the-sensitive-function

**Comment by gsparks** [comment]
Sorry for the confusing wording, this was happening whether you unwrap the sensitive parameter or not.

**Comment by donoghuc** [comment]
I think the underlying issue is that you are trying to run the plan in a version of PE that does not support sensitive parameters in run_* plan functions. This was fixed in PE-30194.

**Comment by gsparks** [comment]
Thanks @donoghuc . Closing.
