### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by erinomalley** [puppetlabs/bolt#2635]
## Describe the Change You Would Like
A clear and concise description of what you would like changed.
I came across a link (Bolt download for macOS Catalina 10.15) that may need to be updated, but I'm not sure. I'm getting this message from Apple that says to contact the developer. 

<img width="1283" alt="Screen Shot 2021-02-09 at 4 24 47 PM" src="https://user-images.githubusercontent.com/73315257/107446805-072ebc80-6af4-11eb-9740-64f57e2c2fe1.png">

**Comment by beechtom** [comment]
@erinomalley You can go to "Security & Privacy" in your settings and click "Open Anyway" after trying to install the package.

![image](https://user-images.githubusercontent.com/30373575/108422411-5dce8180-71eb-11eb-81f3-f1deadcd0f57.png)

We can update our install docs for macOS to describe doing this.

**Comment by lucywyman** [comment]
We should check on this, see if we can find the ticket around signing or notarizing packages from Releng, and see if we can get that prioritized. Ask Mizhai about it.

**Comment by beechtom** [comment]
RE has pulled in a ticket to notarize macOS packages.
