### ISSUE TITLE
how to uninstall bolt which installed by way of mac .dmg installer

### ISSUE THREAD

**Issue by ZDL-Git** [puppetlabs/bolt#2640]
I installed bolt by way of mac .dmg installer.

Can someone help to tell me, how to uninstall it?

Thanks!

**Comment by lucywyman** [comment]
Heh, we *just* added docs for this! https://github.com/puppetlabs/bolt/pull/2638#discussion_r574904490. I believe you just need to `rm` the files themselves - there may be some method with pkgutil that will work, but after polling a few Mac users I know most didn't use pkgutil and just rm'd.

```
sudo rm -rf /opt/puppetlabs/bolt /opt/puppetlabs/bin/bolt
```

**Comment by ZDL-Git** [comment]
pkgutil solved my problem, I think I gained more knowledge about mac.

**Comment by lucywyman** [comment]
Oo wait now I'm curious - how did you use pkgutil to uninstall? That might be a more correct solution for our documentation than rm.

**Comment by ZDL-Git** [comment]
`pkgutil --pkgs | grep bolt | xargs pkgutil --files`
will output all files and dirs. please watch out, they includes each depth dir recursively.

So, except what you said, I found more:

> /etc/paths.d/50-bolt
> /opt/puppetlabs/bolt
> /opt/puppetlabs/bin/bolt
> /usr/local/share/doc/puppet-bolt

**Comment by ZDL-Git** [comment]
The first command can be improved, to get rid of system dirs not belong to bolt.
