### ISSUE TITLE
Make `bolt plan new` help users write script plans

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2654]
## Use Case
Make it easy to generate a plan for wrapping a simple script.

## Describe the Solution You Would Like
Options:
Change the default to be optimized for wrapping a script
Add a new `--script <script name>` flag
Should it support generating parameters?

**Comment by op-ct** [comment]
It would be _really_ handy if this could copy the simple script into `tasks/` and support generating parameters for the task's `.json`.
