### ISSUE TITLE
--password-prompt asks for password too early in Bolt execution

### ISSUE THREAD

**Issue by benridley** [puppetlabs/bolt#2666]
## Describe the Bug
When using the --password-prompt flag to prompt for the users transport password, Bolt seemingly prompts for this before doing any other initialization steps. This often means the user will enter their password, and Bolt may exit unsuccessfully because a plan/task is not found, or parameters are incorrect/missing, or there's parsing errors in plans. 

## Expected Behavior
Bolt should only prompt for a user's password after initial validation is done. 

## Steps to Reproduce
1. Run a bolt plan/task with the --password-prompt flag.

## Environment
 - Version: 3.0.0
 - Platform: RHEL 8

**Comment by adreyer** [comment]
I agree this is a better experience but will require a significant refactor to how the `--password-prompt` option is implemented. If you frequently run bolt with password prompt you can workaround this behavior by creating the following inventory.yaml file in your project.


```yaml
---
config:
  ssh:
    password:
      _plugin: prompt
      message: "Please enter your password:"
```

**Comment by benridley** [comment]
Thanks @adreyer, sad to hear it's a tough one to fix but the workaround achieves exactly the behavior I was after. Cheers for the tip!
