### ISSUE TITLE
Support remote LXD container connections

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2669]
## Use Case
Add support for running Bolt against a [remote LXD server](https://linuxcontainers.org/lxd/advanced-guide/#setup-your-lxd-server-as-remote-server). This should include a `remote` option for the LXD transport, and involve setting `<remote>:<container name>` instead of hard-coding 'local' as the remote (which is default).

Ensure that the current container validation doesn't fail with remote containers, and try to implement container existence validation as part of the `connect` method to fail fast if the remote container doesn't exist.

**Comment by dontlaugh** [comment]
Thanks for taking this on. Happy to test a branch when ready, or field questions, etc
