### ISSUE TITLE
Make `bolt plan new` help users write `run_*` plans

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#2674]
## Use Case

I've been thinking more about the  `bolt plan new --script <script_name>` code generation @adreyer  proposed in #2654.

It might be handy to give `bolt plan new` options that wrap existing tasks and plans in `run_*()` functions and scaffold their parameters (since Bolt already knows them).

## Describe the Solution You Would Like

```console
bolt plan new --pp \
  --task my_project::task_a \
  --task-with my_project::task_b \
  --command 'date utc' \
  --plan my_project::plan_c \
    my_project::new_plan
```

With a result like:
```puppet
# This is the structure of a simple plan. To learn more about writing
# Puppet plans, see the documentation: http://pup.pt/bolt-puppet-plans

# The summary sets the description of the plan that will appear
# in 'bolt plan show' output. Bolt uses puppet-strings to parse the
# summary and parameters from the plan.
# @summary A plan created with bolt plan new.
# @param targets The targets to run on.
plan my_project::new_plan (
  TargetSpec $targets = "localhost"
) {
  
  # Parameters scaffolded based on task's .json:
  $task1_result = run_task( 'my_project::task_a', $targets, {
      'param_a' => 'CHANGEME', # required String
      # 'param_b' => [],       # optional Array
   })

  $task2_result = run_task_with( 
    'my_project::task_b,
    $targets,
  ) |$t| {{
    'param_c' => Sensitive.new('CHANGEME'),  # Required sensitive String
    'param_d' => undef,   # alternate scaffolding for an optional parameter
  }}

  $command1_result = run_command('date --utc', $targets)

  $plan1_result = run_plan( 
    'my_project::plan_c',
    {
      'targets' => $targets,
      'param_e' => {}, # required Hash
    }
  )
  return $plan1_result  # the last scaffolded result?
}

```

## Additional Context

This is not carefully thought out at all—I just want to propose it somewhere for comment, and it's a pretty big chunk of code to throw in the Slack.

**Comment by lucywyman** [comment]
I think the solution for this is something along the lines of having "plan templates" that users can create and then make new plans from. Ideally templates would be available in modules, would be in a well-known or common language. We could start by shipping our own Bolt templates, and as an improvement let users write + ship their own templates.
