### ISSUE TITLE
Support `run_as` user when downloading files

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2679]
## Describe the Bug
When users specify a `run_as` user when using a supporting when using the `download_files` plan function or CLI subcommand we should ensure the file is downloaded as the privileged user, not as the connecting user. This allows users to download files that are owned by the `run_as` user or otherwise not accessible by the connecting user.

**Comment by nmaludy** [comment]
My use case is retrieving OpenSCAP scanning results. We are not allowed to SSH as the root user, so we login with a service account, then sudo to root to run the scans (this is setup very simply using `ssh.run-as` in our inventory).

I would then like to obtain the scan results using `download_file`, however the logged-in-user doesn't have access to the root user's home directory (who ran the scan).

The workaround right now is that we have an intermediate step where we copy the scan results to a world-readable directory like `/tmp` and then obtain them with our SSH user (not ideal, but workable).

**Comment by lucywyman** [comment]
## Solution
Basically the reverse process of uploading files:
1. Copy the existing file to the `tmpdir/some_random_numbers_and_letters/myfile`
2. Chown to the connecting user
3. SCP to Bolt controller
4. Cleanup the temporary instance of the file

Most important is to make sure the file is minimally accessible at each stage, and the intermediary files always get cleaned up.

**Comment by krisavi** [comment]
I think mistake was made when this was implemented. I will make another ticket with same text and refer to this ticket. However it seems the tmp dir is created with another user, copying files to that temp dir may fail if user that created the tmp dir is privileged user. Issue is `mkdir -m 700` which makes that dir accessible only by the user that creates the directory. Maybe it worked and tmp dir creation was changed after this issue.
