### ISSUE TITLE
Apply blocks always report failure when inventory has tty: true

### ISSUE THREAD

**Issue by kreeuwijk** [puppetlabs/bolt#2680]
## Describe the Bug
If the `inventory.yaml` contains `tty: true` for the SSH config, any `apply{}` block in a Bolt Plan will report a failure and cause the Plan to abort after that step. The actual resources get applied correctly, but Bolt thinks the step failed for some reason.
When `tty: true` is removed from the `inventory.yaml`, the same `apply{}` block returns success.

## Expected Behavior
Enabling or disabling the `tty` option should not affect the return code logic of `apply{}` blocks.

## Steps to Reproduce
1. Create a Bolt Plan with a simple apply block
2. Create an inventory file for a remote SSH node and set `tty: true` in the SSH config
3. Run the plan and notice Bolt reports the apply step failed, even though the puppet resources were successfully applied
4. Remove `tty: true` from the SSH config in the inventory file
5. Re-run the plan and notice Bolt now reports success for the apply step.

## Environment
 - Reproduced on Bolt 2.42, 2.44 and 3.0.1
 - Reproduced on MacOS and CentOS 7 as Bolt workstations
 - Reproduced with CentOS 7 and CentOS 8 as SSH targets

## Additional Context
It seems the return code logic breaks for some reason when `tty: true`

**Comment by lucywyman** [comment]
Timebox to 1 day
