### ISSUE TITLE
feature request: possibility to use hostgroups

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/bolt#271]
Compareable to the ansible inventory files, it would be great to support external collections of hosts.
(in addition to "--node" a "--group <name or fact condition>" option)

Ideally bolt should support to load group definition by:
- file
- url
- puppetdb

Groups might be based on facts of puppetdb or manual definitions (a simple file/datastream which defines hostnames in groups).

**Comment by MikaelSmith** [comment]
This is good input for [BOLT-318](https://tickets.puppetlabs.com/browse/BOLT-318). I think the initial attempt will be file-based. PuppetDB might be added later (although it can be handled now by stringing together [puppetdb-cli](https://github.com/puppetlabs/puppetdb-cli) and file-based input for `--nodes`).

What do you aim to accomplish with a URL?

**Comment by MikaelSmith** [comment]
Bolt 0.16.2 and later releases have:
- introduced a file-based inventory with grouping that you can refer to from the CLI and within plans
- added a bolt-inventory-pdb script to generate inventory files from a set of PQL queries
- added the `--query` flag to directly fetch a list of nodes from PuppetDB.

We plan to continue to enhance this. I believe this initial request is satisfied. If you have additional requests please file them as more specific issues.
