### ISSUE TITLE
Make scripts first-class citizens of Bolt by giving them the `scripts/` directory

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/bolt#2717]
## Use Case

I'm frequently led to consider scripts as second-class citizens in the Bolt ecosystem, because unlike tasks and plans, scripts don't have a "home" in projects and modules the way the other two do.

## Describe the Solution You Would Like

We should formally declare that scripts belong in a `scripts/` directory in projects and modules. We should go further, and define naming or calling conventions to make accessing these scripts easy.

Right now we do something that _feels weird_ with scripts, which is support Puppet's **file** naming convention in calling them, implicitly suggesting that they should be put in the `files/` directory of a project or module, mixed in with all the pre-existing use case(s) for `files/`.

Scripts are not intuitively files. This is not where scripts should belong, if we really want to encourage their use.

We should stop doing that, or at a minimum, stop supporting and documenting patterns that encourage it. Of course, to do that, we need to support an alternative—such as giving scripts a real home in `scripts/`.

**Comment by lucywyman** [comment]
Tracking this work through other tickets now - going to close this as a duplicate.
