### ISSUE TITLE
feature request: prompt after execution

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/bolt#273]
Inspired by https://github.com/scoopex/hostctl it might be a good thing to have a interactive possibility to check and rework a execution.

This might look like this:
```
$ bolt command run "ls -l " --nodes foobar.net
Switching teporarily to concurrency of 1
Started on foobar.net.
Finished on foobar.net:
  STDERR:
ls: cannot access '/tmp/lalalal': No such file or directory
Ran on 1 node in 0.77 seconds

Failed on foobar.net:
  The command failed with exit code 1
(c)ontinue, (a)ll, (r)etry, (s)hell, (q)uit
```

- continue : execute next host
- retry: re-execute current host (provide same interactive options after that)
- shell: open a regular shell on the host to examine the situation (provide same interactive options after closing the shell)
- quit: stop execution loop
- all: execute all further hosts without interaction in the defined concurrency

This might help to perform semi-automated automations like distrubution-upgrades or other invasive tasks.

**Comment by adreyer** [comment]
This could be implemented as a plan which would make it easier for different users to customize it as needed.

**Comment by scoopex** [comment]
Oh cool, never used a "plan" :-) 
Probably it would be a good thing, to guide the bolt users to a example set of plans.
(i would welcome a example which suggests how to implement that kind of interaction described  by me)

**Comment by MikaelSmith** [comment]
https://github.com/puppetlabs/tasks-hands-on-lab has labs on writing plans. I'd like to extend it to writing custom Puppet functions and using them. Also figuring out where we need to link that to make it visible to people.

**Comment by MikaelSmith** [comment]
For example, Bolt's core functionality in plans is at https://github.com/puppetlabs/bolt/tree/master/modules/boltlib/lib/puppet/functions, which is just a vendored module `boltlib`.

**Comment by lucywyman** [comment]
@scoopex  I'm not sure if you've had time to implement this as a plan yet, but I don't think there's anything for us to do here. I'm going to close the issue, but let us know if there's any follow up needed!

**Comment by scoopex** [comment]
No, i do not have the time to implement this as a plan. 
Is it possible to the describe things in a plan ? interactive communication, controlling parallelism, ...

As described in this feature request it will be useful for users which need the possibility to review executions in detail or doing canary executions before executing things on all nodes.

From my point of view this feature-set should be part of the bolt core.
