### ISSUE TITLE
Add feature flag to gate loading files from the `scripts/` directory

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2730]
## Use Case
To avoid unexpected behavior (including loading files from `scripts/` that aren't intended to be loaded) we should add a feature flag. Nothing should be loaded from the `scripts/` directory unless the flag is enabled. I think the most efficient way of doing this is to set a context variable in Puppet that will disable script loading altogether - that seems necessary for other tools that rely on Puppet and don't want to load from `scripts/` as well, plus means we don't load something only to do nothing with it.

### Questions
Bikeshed flag name: project-level flag, new `future:` section, and `file_paths:` boolean.

**Comment by beechtom** [comment]
Closed by #2750
