### ISSUE TITLE
Disable host output when running with --stream

### ISSUE THREAD

**Issue by lcrownover** [puppetlabs/bolt#2761]
## Use Case
The --stream option was recently released and it's awesome. It'd be even more awesome if I could silence the output from the host in the results portion of the task/command so it wasn't all printed twice.

## Solution
Adding a custom "quiet" outputter and using "--format quiet" would be an easy approach to fixing this.

**Comment by adreyer** [comment]
I think `--no-verbose` is the flag you want. We should document this as part of the `--stream` flag.

**Comment by lcrownover** [comment]
That seems like it would do the trick. Thanks for pointing me in the right direction.
