### ISSUE TITLE
Enable more intuitive parallelism for varied operations

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2764]
### Varied Actions
The existing parallelize function iterates over a collection executing the same block of code. This is well suited to iterating over an array of targets and doing the same thing on each one but can be non-intuitive to use in cases where the plan needs to do multiple different things at the same time, for example when provisioning a multi-node application you may want to take some actions on one target to set up the db while taking different actions on other targets to set up the application server. This can be accomplished with if/else or case statements but is non-intuitive. 
```
parralellize([db, app]) |$action| {
  case $action {
     'db': { run_plan(install_db, $db_targets) }
     'app': {run_plan(install_app, $app_targets) }
   }
}
```

### Fire and Forget
Sometimes nothing else in a plan depends on an action completing and it's useful to start a slow action then complete the rest of the plan without worrying about its result. This is challenging with the current `parallelize` function as the entire "rest of the plan" needs to be inside a conditional inside a `parallelize` block. If the action is happening in a sub-plan the parent plan cannot continue execution until the long-running action is complete.

## Describe the Solution You Would Like
A `background` function that accepts a block of code to execute in the background returns a `future` object that can be used to wait on or access the result of the block. 
A `wait` function that accepts a `future` or array of futures and returns an array of results. 

- Errors in a backgrounded block should not impact execution.
- Plans should not block returning if a backgrounded block is still running. If a future is unhandled we need to surface errors at a higher logging level (info maybe?).
- New entry point in Pal like 'start_plan' that starts the first thread, and then returns the first fiber result (the Main Plan) and keeps background tasks running.
- Pal should block after the top-level plan has returned until all backgrounded blocks have completed.
- Pal should log any errors from unresolved backgrounded blocks before exiting.
- The background function should accept a name.
- The wait function should return a parallel execution error if any futures in it failed 

The following statements should be functionally equivalent

```
parallelize([1,2,3]) |$val| { .... }
map([1,2,3]) |$val| { background($val) || { .... } }.wait()
```

## Questions
What should the `wait` function be called? `wait` with an alias for `value`? Not for now, just have `wait` that accepts a timeout and can add `value` once we understand how people are using this more.
What methods should the future object have? Should we have a 'state' function? Yes, since we can't have question marks in function names. `running`, `done`, `error` are possible states.

## Solution
- We need a global list of all the threads that are running and then are always cycling through them, even when just running a non-parallel plan. We can keep track of when there's only one thread and then not yield.  Since we don't have an event-based way to know when something is finished, we need to keep looping unless we implement this which just wastes cycles instead of blocking.
- Need to have trace level messages in the executor while we're round-robinning for debugging, which would also make round-robinning with one thread annoying.
- Two functions: one to make a future object, and one to block until a future or array of futures completes and return the array of values (or value if just one).
- `background`, `wait`. We should ensure that errors in `wait` don't exit the plan, and are returned from the function
- As part of this, have `parallelize` return an error instead of raising it if the error is returned from the block, instead of thrown.
- If you call `wait` and it has errors, return a ParallelFailure object and raise unless in a catch_errors.
- What kind of signal can plan function send back to the executor to indicate that it hasn't finished yet? A symbol or object that can't be created in Puppet. We also may not need this, we can try checking if the Fiber is done in the round robin.
- "It is important that the Fibers get named for logging purposes." - Alex

**Comment by beechtom** [comment]
Closed by #2810
