### ISSUE TITLE
Push Facts to PDB from a bolt plan

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#2771]
## Use Case
I want to use PuppetDB from bolt without managing long-running puppet-server and regular agent check-ins.

PuppetDB is a powerful tool to track inventory that can be leveraged for selecting targets from Bolt with `--query` flag or the `pdb_query` function. Unfortunately, that workflow is only available for targets that are part of a larger classic puppet installation not agentless targets or environments without a puppet-server and CA set managed. If Bolt has the ability to push facts directly into pdb from a plan users will be able to leverage the power of PuppetDB without having to run agents or manage more services than required, pdb can even be run on-demand locally inside a container.

## Describe the Solution You Would Like
New function `pdb_command` that posts to PDB's command endpoint.

# Accepts a command, a version, and a payload
`pdb_command('replace_facts', 5, { 'certname' => 'myhost.com'})`

This function should be implemented through a `send_command` method on the pdb_client that can be implemented in orchestrators client implementation. It should fail cleanly if that method is missing.

## Describe Alternatives You've Considered
`pdb::replace_facts` It seems better to abstract over pdb less. We can write puppet language functions or plans on top of a general-purpose command function.

## Solution
- [API spec](https://puppet.com/docs/puppetdb/latest/api/command/v1/commands.html). What can we 'automate' vs making the user set everything? For now, let the user set everything so we don't have to manage different versions, let pdb error appropriately, etc. Can potentially eventually have a puppetdb module that adds a nicer interface around that.
- Don't need to worry about blocking for now.
- Require `command`, `version`, and `payload`. Positional or kwargs? Let's do positional, and we can add a non-positional one later if more keys are needed.
- For the command API, it's command API version 1 which requires certname to be one of the query parameters (along with the command, version, and payload). We should pull the certname out of the payload and pass it to PDB. If the user doesn't specify a certname in their payload just don't include it in the request and let PDB give us an error.
- Returns an object with a UUID key, we should pull that out of the return and return that from the function (which should be just a string).
- Focus testing on `replace_facts` version 5 - document as only supported command and other commands may work
- If it errors, create a Bolt::Error with the error from PDB in the details (or whatever we have for pdb errors already). We've had some issues with stringified JSON inside JSON, so....try to avoid that 😬 
- Document as experimental
- Ping skeletor on the PR (Sean or someone)

Due date: release next week

**Comment by beechtom** [comment]
**Update**

- Errors if the payload is missing `certname`, as PDB returns a `500` status code without any error message if the `certname` is not included. Instead, Bolt will error early with a helpful message.

**Comment by lucywyman** [comment]
Closed by #2781
