### ISSUE TITLE
Deprecation warnings for GSSAPI on RHEL 8

### ISSUE THREAD

**Issue by benridley** [puppetlabs/bolt#2776]
## Describe the Bug
When running a Bolt plan, we receive dozens of messages on stdout like the following:
`[DEPRECATION] Struct layout is already defined for class GSSAPI::LibGSSAPI::GssOID. Redefinition as in /opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/gssapi-1.3.1/lib/gssapi/lib_gssapi_loader.rb:10:in ``<class:GssOID>' will be disallowed in ffi-2.0.`

## Expected Behavior
No deprecation warnings are received when running plans.

## Steps to Reproduce
1. Run any plan

## Environment
 - Version 3.4.0
 - Platform: RHEL 8.3

## Additional Context
Has been happening since 3.0.0

**Comment by beechtom** [comment]
@benridley Thanks for opening this issue. We are aware of the deprecation warnings, which are coming from one of Bolt's dependencies, not Bolt itself. We've opened a ticket with the gem's maintainer, which you can track here: https://github.com/zenchild/gssapi/pull/35

**Comment by benridley** [comment]
Thanks @beechtom, glad to hear it's got a path to resolution. Feel free to close this, otherwise I'll leave it open for tracking and others who might come across this.
