### ISSUE TITLE
Scope for custom functions in puppet task

### ISSUE THREAD

**Issue by vinayakorrapati** [puppetlabs/bolt#2798]
## Describe the Change You Would Like
A clear and concise description of what you would like changed.
Can't we call a functions in side a puppet task ? we do have a section to call a functions in puppet plans. 
And we do not have such a section for puppet tasks. 

Can't we call a Built-in/ Custom functions from puppet task. 

Custom function from same or different module can call from puppet task ?

**Comment by adreyer** [comment]
It's pretty challenging to set up the environment to use puppet functions directly from task code and unless you need all of the puppet libraries it will signifcantly slow down the task. In most cases it's better to extract the shared logic into a ruby module inside the puppet module. By convention that code is nested in `lib/puppet_x` of the module code. You can call the shared code from the puppet function with a relative require or from the task by adding it as a `file` requirement of the task and requiring it.
