### ISSUE TITLE
Kill in-progress command/task/script on target

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/bolt#280]
When hitting Ctrl-C, I'd like to be able to kill in-progress execution on target nodes to prevent them completing a command that may cause problems or take a long time.

One possible UX for this is to Ctrl-C once to prevent starting any new execution (which would then wait for all in-progress execution to complete), then Ctrl-C again to kill any in-progress execution.

**Comment by adreyer** [comment]
Is this specifically with orchestrator or are there cases where it's not happening when using ssh or winrm?

**Comment by MikaelSmith** [comment]
This is about ssh/winrm/local. If I run something like `bolt command run 'sleep 60'`, then Ctrl-C, the sleep will continue running on targets.

It would also be nice to apply to orchestrator, but that's trickier without some work in orchestrator.

**Comment by Iristyle** [comment]
The WinRM implementation is going to be tricky I think... if you intend to cancel the remotely executing code, it may be necessary to send an additional message to the host. @nicklewis and I discovered some interesting / unexpected behavior when we dug into the spec to understand how timeouts work (there are several different ones depending on the layer of the protocol stack).
