### ISSUE TITLE
LXD transport: run_command does not accept _run_as param (and perhaps others)

### ISSUE THREAD

**Issue by dontlaugh** [puppetlabs/bolt#2806]
## Describe the Bug
In a Bolt plan, the LXD transport `run_command` function does not accept the '_run_as' parameter, and throws an exception.

## Steps to Reproduce

Here is an example function call.
```pp
  run_command('systemctl daemon-reload', $targets, '_run_as' => 'root')
```

## Environment
 - Version 3.3.0
 - Platform Manjaro Linux

## Additional Context
Passing --run_as at the command line doesn't throw an error.

**Comment by beechtom** [comment]
Fixed by #2838
