### ISSUE TITLE
Target group globbing

### ISSUE THREAD

**Issue by breca** [puppetlabs/bolt#2818]
## Use Case
I would like to be able to glob target groups

## Describe the Solution You Would Like
`bolt inventory show --targets group:'foo*'`
`bolt command run 'echo "Bolt is great"' -t group:'*bar*'`

## Describe Alternatives You've Considered
Creating groups of groups, which is nice on paper but can become a bit painful when dealing with dynamic inventories at large scales

**Comment by reidmv** [comment]
Suggestion:

No need to include a `group:` prefix. The Bolt inventory already knows group names, in addition to target names, and treats them identically for almost all other interfaces except for globbing. So, globbing shouldn't be special. Make globbing work for and find group names in addition to target names. It should work exactly as it already does for targets, just match group names as well.
