### ISSUE TITLE
Print 'Future <name> aborted' instead of 'Plan aborted' when a PlanFuture fails

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2847]
This is also an issue when users return an error from a plan, or catch errors. This issue specifically is around when a plan finishes but still has futures executing.

Instead of rewording this, we should just remove `Plan aborted` language altogether since it's impossible to know if the Plan will actually exit from an error or keep running.

**Comment by beechtom** [comment]
Closed by #2895
