### ISSUE TITLE
More readable type errors from Puppet

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2853]
## Use Case
When the user passes the wrong type to a plan function, the resulting error message is often unreadable, particularly when the type is a type alias or the function takes a lot of parameters. For example, passing the wrong type as the `target` parameter to `run_task` results in:
```
"msg": "'run_task' parameter 'targets' expects a Boltlib::TargetSpec = Variant[String[1], Object[{name => 'Target', attributes => {'uri' => {type => Optional[String[1]], kind => given_or_derived}, 'name' => {type => Optional[String[1]], kind => given_or_derived}, 'safe_name' => {type => Optional[String[1]], kind => given_or_derived}, 'target_alias' => {type => Optional[Variant[String[1], Array[String[1]]]], kind => given_or_derived}, 'config' => {type => Optional[Hash[String[1], Data]], kind => given_or_derived}, 'vars' => {type => Optional[Hash[String[1], Data]], 
kind => given_or_derived}, 'facts' => {type => Optional[Hash[String[1], Data]], kind => given_or_derived}, 'features' => {type => Optional[Array[String[1]]], kind => given_or_derived}, 'plugin_hooks' => {type => Optional[Hash[String[1], Data]], kind => given_or_derived}, 'resources' => {type => Optional[Hash[String[1], ResourceInstance]], kind => given_or_derived}}, functions => 
{'host' => Callable[[0, 0], Optional[String]], 'password' => Callable[[0, 0], Optional[String[1]]], 'port' => Callable[[0, 0], Optional[Integer]], 'protocol' => Callable[[0, 0], Optional[String[1]]], 'transport' => Callable[[0, 0], String[1]], 'transport_config' => Callable[[0, 0], Hash[String[1], Data]], 'user' => Callable[[0, 0], Optional[String[1]]]}}], Array[Boltlib::TargetSpec]] value, got ResultSet",
```

We can catch this type of error in PAL and issue a nicer error, similar to the one raised when running a task that has mismatched parameters.

**Comment by artlawson** [comment]
Puppe PR opened [here](https://github.com/puppetlabs/puppet/pull/8658)

**Comment by lucywyman** [comment]
We're going to table this work for now and potentially come back to it later, [see the discussion here](https://puppet.slack.com/archives/CGJ0GTF4Y/p1625248148489300). One option is to always expand aliases but to not expand aliases *inside* the aliases, which would result in a message like `expects a Boltlib::TargetSpec = Variant[String[1], Target, Array[Boltlib::TargetSpec]]`. We should more clearly define:
* When are error messages too long? This issue specifically is about the `TargetSpec` alias, but `Objects` are likely also an issue
* What do we want the error message to be for each case?
