### ISSUE TITLE
Automate verifying that functions in Executor are defined in the Orchestrator PlanExecutor

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2857]
## Use Case
Updates to the Bolt executor are often not communicated clearly, and adding or modifying methods on the class will break the [Orchestrator PlanExecutor::Executor](https://github.com/puppetlabs/orchestrator/tree/main/ruby/bolt-plan-executor-lib/bolt_plan_executor/executor.rb). It'd be useful to automate verifying that any functions defined in Bolt's Executor are also defined in the PlanExecutor::Executor, and if possible verify that their signatures are compatible.

**Comment by beechtom** [comment]
This test would likely look similar to the one for BoltSpec's mock executor: https://github.com/puppetlabs/bolt/blob/main/spec/bolt_spec/plans/mock_executor_spec.rb

Comparing method signatures is straightforward using the `Object#instance_method` method. That returns the method instance. Y can then call `Method#parameters` on the method, which returns an array of parameter names, type (positional or keyword), and whether they're required.

```ruby
Bolt::Executor.instance_method(:foo).parameters
=> [[:req, :one], [:opt, :two], [:keyreq, :three], [:key, :four]]
```

One question I have is whether this test belongs in Bolt (run on commit) or Orchestrator (triggered by merge to Bolt) and whether it fails or triggers a Slack notification when there's a mismatch.

**Comment by lucywyman** [comment]
This also applies to any plan function signature changes that are defined in pe-bolt-modules
