### ISSUE TITLE
Migrate Bolt modules to use GH Actions workflow for release

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2880]
## Use Case
The IAC team recently developed a Github Actions workflow for releasing modules to the Forge, which gives us better control over the environment modules are released in and means we don't have to make changes in CI Job Configs to update module release pipelines. We piloted a new GH Action release workflow that is manually triggered which tags and then release modules with [the PKCS7 module](https://github.com/puppetlabs/puppetlabs-pkcs7) which worked great. Now that it's proven out, we should remove our current module release pipelines from CI Job Configs and create GH Action workflows that copy the workflow from pkcs7.

**Comment by donoghuc** [comment]
The apply_helpers module 0.3.0 did not get pushed to forge, it is part of https://github.com/puppetlabs/ci-job-configs/blob/8ae5544231244a57c67fdea1df525e7b4187c609/jenkii/platform/projects/bolt.yaml#L280 can we do a push then when that gets ported over as part of this work?

**Comment by lucywyman** [comment]
Sure - the workflow will tag the repo, and I'm not entirely sure what it'll do if the tag already exists....but we can try.

**Comment by beechtom** [comment]
### To review

- [ ] https://github.com/puppetlabs/puppetlabs-apply_helpers/pull/11
- [ ] https://github.com/puppetlabs/puppetlabs-powershell_task_helper/pull/5
- [ ] https://github.com/puppetlabs/puppetlabs-python_task_helper/pull/19
- [ ] https://github.com/puppetlabs/puppetlabs-ruby_task_helper/pull/19
- [ ] https://github.com/puppetlabs/puppetlabs-ruby_plugin_helper/pull/4
- [ ] https://github.com/puppetlabs/puppetlabs-azure_inventory/pull/15
- [ ] https://github.com/puppetlabs/puppetlabs-aws_inventory/pull/20
- [ ] https://github.com/puppetlabs/puppetlabs-gcloud_inventory/pull/13
- [ ] https://github.com/puppetlabs/puppetlabs-http_request/pull/12
- [ ] https://github.com/puppetlabs/puppetlabs-secure_env_vars/pull/4
- [ ] https://github.com/puppetlabs/puppetlabs-terraform/pull/25
- [ ] https://github.com/puppetlabs/puppetlabs-vault/pull/17
- [ ] https://github.com/puppetlabs/puppetlabs-yaml/pull/6
