### ISSUE TITLE
macOS installer package for 3.9.2 is not signed

### ISSUE THREAD

**Issue by gerardkok** [puppetlabs/bolt#2881]
## Describe the Bug
The macOS installer package for 3.9.2 is not signed.

## Expected Behavior
I expected the package to be signed (like earlier versions).

## Steps to Reproduce
1. Download the macOS DMG for 3.9.2 from https://downloads.puppet.com/mac/puppet-tools/10.14/x86_64/puppet-bolt-latest.dmg
2. Mount the DMG: `hdiutil mount puppet-bolt-latest.dmg`
3. Find the package in the mounted volume, and check its signature:
```
pkgutil --check-signature puppet-bolt-3.9.2-1-installer.pkg 
Package "puppet-bolt-3.9.2-1-installer.pkg":
   Status: no signature
```
compared to 3.9.1:
```
pkgutil --check-signature puppet-bolt-3.9.1-1-installer.pkg 
Package "puppet-bolt-3.9.1-1-installer.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: PUPPET LABS, INC. (VKGLGN2B6Y)
       SHA1 fingerprint: 2A 8D 04 E0 3A 7B 0E 01 56 67 71 AD 85 98 6E 54 F6 BE 28 05
...
```

## Environment
 - Bolt 3.9.2
 - macOS 10.14/10.15

**Comment by lucywyman** [comment]
Confirmed this is a bug (in 3.10.0 as well), we'll investigate!

**Comment by lucywyman** [comment]
Hopefully closed by https://github.com/puppetlabs/packaging/pull/1109
