### ISSUE TITLE
Parallelize causes plan variable to be 'forgotten'

### ISSUE THREAD

**Issue by benridley** [puppetlabs/bolt#2889]
## Describe the Bug
In some cases, using parallelize in a plan causes variables declared previously in that plan to be 'forgotten', and attempting to use them results in an error of the form "Evaluation Error: Unknown variable: '\<variable\>.'"

## Expected Behavior
Parallelize has no effect on variables declared in a higher scope.

## Steps to Reproduce
I am having trouble reproducing this easily, however I have managed to reproduce it reliably with a complex set of plans and tasks. Some of these rely on internal network services, so it's difficult for me to disclose details. 
 
In this case, I'm using parallelize to shutdown a number of clustered applications at once. I've narrowed the culprit down to a single Puppet function, which is a custom function that calls a task on localhost to lookup secrets from an external system. When this function is called in specific circumstances, it appears to *sometimes* cause this bug, but not all the time. This function is called at multiple places in the parallel blocks and they all complete successfully. Only after completing and exiting the block is this problem occurring. 

Accessing the variable inside the parallelize blocks, even as the final step of the block, works successfully in all cases. It's only once we exit the parallelize function that the variable seems to disappear. To test this I added an `out:message` to simply print the variable before and after executing a plan inside parallelize. This always prints the expected value. Immediately after exiting the `parallelize` function, trying to use the variable causes the above error. 

## Environment
 - Version: 3.9.2
 - Platform: Red Hat Enterprise Linux 8
 
## Additional Context
I initially suspected a child plan might be overwriting a top level plan or something like that. I've tried renaming the variable to a unique name which didn't fix the problem. When I use the `each` function to iterate instead of `parallelize`, the problem does not occur.

**Comment by lucywyman** [comment]
Hm, is there any chance you can provide the custom function you're using that's causing the issue? Or some pseudocode for the plan you have that's forgetting variables?

**Comment by benridley** [comment]
Thanks @lucywyman, I'll do my best to provide details.

```puppet
function resolve_secret(
  Integer $secret_id
){
  run_task('get_secret', localhost, {'secret_id' => $secret_id}.first.sensitive
}
```

The task `get_secret` is just a Python script to call out to the service that stores our secrets. It looks like this (simplified):
```python
import json
import requests

params = json.load(stdin)
with open('credentials.json', 'r') as f:
  creds = json.load(f)

sid = params['secret_id']
resp = requests.get(f"{secret_endpoint}/api/secrets/{sid}")
print(json.dumps({"_sensitive": resp.json()})

**Comment by beechtom** [comment]
It looks like this might be a thread-safety or scoping issue, though we'll need to do more investigating. This error specifically happens when:

- Running a `parallelize()` or `background()` block
- That runs with more than 1 input
- And invokes a custom Puppet language function
- That invokes a Bolt function that creates a new thread (anything that calls `executor.in_parallel`)

Here's a plan and function that replicate the error:

```puppet
# bolt/plans/init.pp
plan bolt (
  TargetSpec $targets
) {
  $nodes = get_targets($targets)

  parallelize($nodes) |$node| {
    bolt::function($node)
  }

  out::message($nodes)
}
```

```puppet
# bolt/functions/function.pp
function bolt::function (
  TargetSpec $target
) {
  run_command('whoami', $target)
}
```

Running the plan with more than one input to `parallelize()` gives the following error:

```shell
$ bolt plan run bolt -t localhost,local://127.0.0.1
Starting: plan bolt
Starting: command 'whoami' on localhost
Starting: command 'whoami' on local://127.0.0.1
Finished: command 'whoami' with 0 failures in 0.89 sec
Finished: command 'whoami' with 0 failures in 1.37 sec
Finished: plan bolt in 2.03 sec
{
  "kind": "bolt/pal-error",
  "msg": "Evaluation Error: Unknown variable: 'nodes'. (file: /Users/tom/.puppetlabs/bolt/plans/init.pp, line: 10, column: 16)",
  "details": {
    "file": "/Users/tom/.puppetlabs/bolt/plans/init.pp",
    "line": 10,
    "column": 16
  }
}
```

Running with a single input to `parallelize()` does not error:

```shell
$bolt plan run bolt -t localhost
Starting: plan bolt
Starting: command 'whoami' on localhost
Finished: command 'whoami' with 0 failures in 0.75 sec
[
  "localhost"
]
Finished: plan bolt in 1.52 sec
Plan completed successfully with no result
```

Prying into Puppet shows that the ephemeral in the plan's scope is being popped off before it should be, which is causing the error.

**Comment by beechtom** [comment]
@benridley This is definitely a bug and we're currently working on getting it fixed so you can use your custom function as expected. In the meantime, if you need to run the function in parallel, a workaround is to move the contents of the function to a plan and run it using `run_plan` in the parallel block.

**Comment by benridley** [comment]
@beechtom Wow, great troubleshooting! Thanks for identifying this and providing a workaround.

**Comment by lucywyman** [comment]
Mmk, I think we need to test if this same issue occurs with

**Comment by lucywyman** [comment]
Next steps: Move pushing ephemerals to be inside the `create_future` block and pop them off when the block finishes. I would also try some of the guarded scope or without ephemerals functions on the `Puppet::Parser::Scope` object and see how those handle. Worst case scenario Fibers can keep track of their own scope objects and override the Puppet scope with their own scope every time we switch Fibers.
