### ISSUE TITLE
Sensitive task output not supported for pcp transport

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#2892]
## Describe the Bug
Plans that attempt to use the `Result` from tasks run over PCP with `_sensitive` output are unable to `unwrap` the result.

## Expected Behavior
Sensitive task results usable run over PCP

## Additional Context
The orchestrator `task` command will always return a `Sensitive: [value redacted]` string (as it is not stored in the orch database). 

## Solution

Document this behavior in "Writing/Running Tasks". Potentially reference it from "Using Bolt with Puppet Enterprise".

**Comment by donoghuc** [comment]
We could first perhaps just document this behavior.

**Comment by lucywyman** [comment]
Document in the `bolt_shim` module and link from the Troubleshooting page in Bolt

This doesn't seem like it's something that will ever work: even if the Orchestrator unwrapped and encrypted the value, it doesn't know who's allowed to access the value and who isn't, and Bolt can't get this result from anywhere other than the database. The takeaway is pretty much "you shouldn't be doing this with Bolt over PCP anyway". I think documenting is sufficient to close this ticket.
