### ISSUE TITLE
Fix brittle plan cache spec tests

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2896]
## Describe the Bug
The plan cache spec tests have been sporadically failing recently, causing the Linux test suite to report as failing.

## Additional Context
A few examples of the tests failing:
- https://github.com/puppetlabs/bolt/runs/2878320272?check_suite_focus=true 
- https://github.com/puppetlabs/bolt/runs/2878240848?check_suite_focus=true
- https://github.com/puppetlabs/bolt/runs/2877088807?check_suite_focus=true

**Comment by lucywyman** [comment]
I think we should just remove this - I did that as part of https://github.com/puppetlabs/bolt/pull/2887

**Comment by beechtom** [comment]
👍  Awesome. I'll close this then.
