### ISSUE TITLE
Document `allow_any_task`, `allow_any_plan` etc. matchers in BoltSpec

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/bolt#2907]
## Use Case

Many Bolt plans are essentially sequential calls to Bolt execution functions, without regard for the specific outputs. BoltSpec provides a way to test execute plans, but at present it is necessary to enumerate every execution function used in the plan at least once in the spec test with correct arguments.

Because of how many plans work, it's useful to generically `allow_any_*` Bolt execution function by default. Then, spec tests could focus on setting specific expectations that matter to the test, rather than on correctly repeating every Bolt execution function listed in the plan.

## Describe the Solution You Would Like

Turns out, we already have BoltSpec helpers for that!

* `allow_any_plan`
* `allow_any_task`
* ... etc

However, I didn't know this until I was about to file a ticket asking for them, and was spelunking around in the code.

We should document these helpers on the [Testing Plans](https://puppet.com/docs/bolt/latest/testing_plans.html) page.

**Comment by artlawson** [comment]
After some digging, I'm still not 100% where this should go. My best guess would be [here](https://puppet.com/docs/bolt/latest/testing_plans.html#execution-modes). I think part of this is me needing a better understanding of what `allow_any_plan` does. After reading the description for `execute_any_plan`, it seems like  they would be similar in functionality. I searched and the only places `execute_any_plan` and `execute_no_plan` are referenced in Bolt are `boltspec_reference.md` and `testing_plans.md`. Did `allow_any_plan` replace `execute_any_plan`? In which case I could just update the description for `excecute_any_plan`. Also totally possible I'm misreading this lol.

**Comment by beechtom** [comment]
The `allow_any_*` functions are stubs that allow any invocation of the matching plan function to be called during a test. For example, if you're testing a plan that runs task `foo` and `bar` you could write:

```ruby
allow_task('foo')
allow_task('bar')
```

Or you could just allow all tasks like so:

```ruby
allow_any_task
```

We likely want to add a "Any stub functions" column to the table [here](https://puppet.com/docs/bolt/latest/testing_plans.html#supported-stubs-and-mocks), and then add a new "Any stubs" section [here](https://puppet.com/docs/bolt/latest/boltspec_reference.html) that describes each `allow_any_*` function. We'll want to check whether those functions accept modifiers, and if so list the ones that are compatible.
