### ISSUE TITLE
Even simple commands take up to one minute to run in windows

### ISSUE THREAD

**Issue by johnmetta** [puppetlabs/bolt#2909]
## Describe the Bug

Commands take an extremely long time in windows. This is related to the MacOS disparity (See: #1951 ) but at a scale of 10x the disparity. 

For example, #1951 illustrates this disparity with `bolt --version` taking 0.5 seconds on Linux and 1.7 seconds on MacOS. The same command takes 12.5 seconds on Windows.

Similarly, #1951 notes `bolt task show` taking 1.7 seconds on Linux and 3.3 seconds on MacOS. The same command takes 38.5 seconds on windows.

I routinely run commands that take almost a whole minute.

## Expected Behavior

Commands should run within one standard deviation of the average command response time of the environment one is working in. This should apply to Windows, but also MacOS and Linux. I don't think there's as much value in comparing response times in different OSes as there is comparing times across contexts in the same OS. Bolt should respond within the expected response time of a Windows user when in Windows, and the expected response time of a MacOS user on a Mac. 

Despite that argument, having a 30-45 second response time for a simple command is an obvious failure of usability.

## Steps to Reproduce

`Measure-Command { bolt --version }`
`Measure-Command { bolt task show }`

## Environment
 - Bolt Version: 3.1.0
 - Platform: Win10 Version 10.0.19042 Build 19042
 - Powershell: 5.1.19041.1023

## Additional Context
Filed as a different ticket than #1951 because that seemed to indicate the use of Bundler and a MacOS-specific path of resolution.

**Comment by johnmetta** [comment]
Response times are analogous in Powershell 7.1.

```
PS C:\Projects\ANPC\Boltdir> Measure-Command { bolt plan show }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 41
Milliseconds      : 67
Ticks             : 410676353
TotalDays         : 0.000475319853009259
TotalHours        : 0.0114076764722222
TotalMinutes      : 0.684460588333333
TotalSeconds      : 41.0676353
TotalMilliseconds : 41067.6353
```

**Comment by beechtom** [comment]
@johnmetta Thank you for filing this issue. We're aware of performance differences on Windows and have been working on finding ways to improve this. The most relevant open PR you can follow is https://github.com/puppetlabs/bolt/pull/2291
