### ISSUE TITLE
ServiceNow CMDB inventory plugin

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2965]
## Use Case
Create and ship a Bolt inventory plugin to get targets from ServiceNow CMDB.

## Notes
Assuming we move forward with this inventory plugin, keep the following in mind:
- Include detailed documentation for having proper permissions for accessing tables and how to use the plugin.
- Tables are idiomatically rigid. Some tables (like `cmdb_ci_linux_server`) are global and have set defaults.
- Likely want to use the [table API](https://docs.servicenow.com/bundle/paris-application-development/page/integrate/inbound-rest/concept/c_TableAPI.html#table-GET), which returns all CI in the table. Alternative is to use the [CMDB instance](https://docs.servicenow.com/bundle/paris-application-development/page/integrate/inbound-rest/concept/cmdb-instance-api.html#cmdb-instance-api) API, but that would likely be more cumbersome and require more requests (f(n)).
- Only one table specified per request to the table API. Can be difficult to munge data between multiple sources. Could potentially accept a `tables` parameter, but might be more appropriate to just use groups in the inventory for now.
- Other Puppet tasks ignore refresh token for OAuth, just create an auth token with an arbitrarily TTL. We do something similar for either Azure or GCloud.
- Users typically have a custom defined UUID for instances. Could be anything. This should be covered by documentation (i.e. plugin users need to know their system to use the plugin successfully)
- MVP should include OAuth, as just shipping with support for basic auth won't cover many users.
- On prem installations are rare. More typical that requests could be blocked by a firewall, though users will probably know how to correctly allow requests through.

## Next steps
- Determine use cases and whether this should be an inventory plugin or some other integration.
- If we continue with this plugin, `gcloud_inventory` serves as a good base. It has all the logic for making multiple requests and validating the responses. Would need additional work to generate the correct `Authentication` header. Documentation is available covering [authentication](https://docs.servicenow.com/bundle/paris-application-development/page/integrate/inbound-rest/concept/c_RESTAPI.html#d1925641e527), and we should likely support basic, MFA, and OAuth.
- It seems like we could start shipping a minimal SNOW plugin that behaves like `gcloud_inventory` now, and then verify that this works for the provided use case and add on if not.

## Use case questions
- Are you looking to just get targets from SNOW? Or other configuration options as well?
- Do you have them all in a single table, or would this need to make multiple requests to multiple tables?
- Are you using OAuth to authenticate?

**Comment by miharp** [comment]
Thanks @lucywyman  was just going to open same

**Comment by lucywyman** [comment]
@miharp Are you looking to just get targets from SNOW? Or other config? And do you have them all in a "main table"? Are you using OAuth to authenticate? (So many questions! I'd just like to know more about your use case)

**Comment by beechtom** [comment]
From internal discussion, what would be of more interest to ServiceNow users is a spoke rather than an inventory task plugin. Closing this since development of a spoke falls outside the scope of Bolt and we do not anticipate moving forward with an inventory task plugin.
