### ISSUE TITLE
`bolt plan show <plan>` hides untagged description block, unlike Puppet Strings

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#2974]
## Describe the Bug

When a Bolt Plan is documented with a `@summary` tag and a longer, untagged block of descriptive text, `bolt plan show` and `bolt plan show <specific::plan>` only display  the `@summary` text and ignore the content of the untagged block. This behavior is inconsistent with Puppet Strings, which renders the `REFERENCE.md` TOC using the plan's `@summary` **and** the plan's details using the content of the untagged block.

## Expected Behavior
When a plan is documented with both `@summary` and an untagged text block,  `bolt plan show <specific::plan>` should include the content of the untagged text block.

## Steps to Reproduce
1. Review the `canary` plan's inline documentation at https://github.com/puppetlabs/bolt/blob/main/modules/canary/plans/init.pp, noting the `@summary` tag + untagged description block.
2. Run `bolt plan show canary`
3. All of the untagged description block's documentation is missing

## Environment
 - Version 3.13.0

## Additional Context

There don't seem to be any good options to add detailed documentation to Bolt Plans in a way that displays well in both Puppet Strings and `bolt plan show`.

I've pushed an example Bolt project to https://github.com/op-ct/bolt_doc_example.  It contains 3 small plans that demonstrate what goes wrong in `bolt plan show` and/or Puppet Strings' `REFERENCE.md` when rendering plan docs with each combination of:

* [Short `@summary` with untagged description block](https://github.com/op-ct/bolt_doc_example/blob/main/plans/a/mixed_docs.pp)
* [Multi-line `@summary`, without an untagged block](https://github.com/op-ct/bolt_doc_example/blob/main/plans/b/multiline_summary.pp)
* [Untagged description block, without `@summary`](https://github.com/op-ct/bolt_doc_example/blob/main/plans/c/untagged_only.pp)

Each plan's docs summarize what happens, and the resulting [`REFERENCE.md`][0] shows how Puppet Strings renders each example.  You can validate how bolt renders each plan's docs with `bolt plan show` and `bolt plan show <plan::name>`.

[0]: https://github.com/op-ct/bolt_doc_example/blob/main/REFERENCE.md

**Comment by lucywyman** [comment]
Puppet Strings [recommends a summary character limit of 140 characters](https://github.com/puppetlabs/puppet-strings/blob/8a4a87e1b44e7581855d2c59ab4402abf438f9d8/lib/puppet-strings/yard/handlers/helpers.rb), which isn't enforced, but looking at how it parses the Canary plan strings it treats that first `summary` line as a summary, and the rest of the untagged text as just "text". We can definitely append the untagged `text` data to the summary in `bolt plan show` output, though it's worth noting that untagged text *anywhere* in the header will appear there, not just what's underneath the "summary" tag. I expect it's the same for Reference.md.

**Comment by beechtom** [comment]
Fixed by #3077 and released in 3.23.0
