### ISSUE TITLE
Feature Request - File upload/download progress indicator

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2975]
## Use Case
I'm connecting to an environment over a very slow link while uploading and downloading files with Bolt. Often times i'm not sure if the link has gone down or if it's just being slow.

## Describe the Solution You Would Like
It would be great to have some sort of progress indicator (amount data transferred, amount data remaining, current speed, estimated time remaining).

Thanks!

**Comment by jay7x** [comment]
I'd say it might be nice to have some general-purpose `show_progress()` function which can be used in a plan to track it's progress.

**Comment by jay7x** [comment]
Please reopen the issue.
