### ISSUE TITLE
Create `.gitignore` with `bolt project init`

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#2985]
## Use Case
The `bolt project init` / `New-BoltProject` commands should create a `.gitignore` file that includes the following files:

- `.modules/`
- `.resource_types/`
- `bolt-debug.log`
- `.plan_cache.json`
- `.plugin_cache.json`
- `.task_cache.json`
- `.rerun.json`

**Comment by donoghuc** [comment]
Should `.rerun.json` also be ignored?

**Comment by lucywyman** [comment]
Can we also add an empty `scripts/` directory as part of this?
