### ISSUE TITLE
Password Auth Breaks When ed25519 Keys Exist

### ISSUE THREAD

**Issue by RiverHeart** [puppetlabs/bolt#3012]
## Describe the Bug
Password auth fails when unsupported pub/priv keys exist in the client's ".ssh" folder. `unsupported key type ssh-ed25519'`. Moving those keys to another folder fixed the issue since there was nothing to error on.

**Issues**
- **net-ssh** gives [precedence](https://github.com/net-ssh/net-ssh/blob/a859e03c5845db1579bceb56482636abd96b2d3e/lib/net/ssh/config.rb#L52) to publickeys over password
- Can't change auth precedence or disable pubkey auth in Puppet Bolt yaml files
- Passing `PubkeyAuthentication=no` to **ssh-command** isn't a great solution because it relies on `sshpass` to do non-interactive logins which isn't available in the standard OpenSSH tooling on Windows (and might not get recognized by net-ssh either).

## Expected Behavior
Ruby/Bolt sees that I've configured it for password based authentication and doesn't attempt to load or use pub/priv keys on the client machine or lets me set `PubKeyAuthentication=no` via yaml.

**And** before anyone suggests it, using a pubkey instead is a workaround not a fix and pubkeys are better but that has nothing to do with the bug itself.

## Steps to Reproduce
1. Create an ed25519 pub/priv keypair in ".ssh"
2. Run `bolt command run date --targets $node -u $user -p $pass` modifying the vars as needed

## Environment
 - Version [3.17.0]
 - Client Platform [Windows 10]

**Comment by lucywyman** [comment]
Apologies, I'm just skimming this, but I think this known issue isn't the exact problem you're running into, but may have thee same solution https://puppet.com/docs/bolt/latest/bolt_known_issues.html#unable-to-authenticate-with-ed25519-keys-over-ssh-transport-on-windows

**Comment by RiverHeart** [comment]
The issue is that it attempts to use keys when it should only be attempting password auth. Using native-ssh isn't a good solution though because sshpass isn't available on Windows and would be required to do non-interactive authentication with passwords.
