### ISSUE TITLE
error 126

### ISSUE THREAD

**Issue by ingridm7** [puppetlabs/bolt#3040]
## Describe the Change You Would Like
A clear and concise description of what you would like changed.

tengo un erro error 126  al correr

bolt task run mysql::export --targets bdd database=empresa file=root@192.168.122.20:/home/admin/copias  password=12345678 user=jadmin
Started on 192.168.122.20...
Failed on 192.168.122.20:
  The task failed with exit code 126 and no stdout, but stderr contained:
  bash: /tmp/bolt/16922f0b-ed93-4fa0-81c7-39d38fba20b0/export.rb: /opt/puppetlabs/puppet/bin/ruby: bad interpreter: No such file or directory
  
  
  This might be caused by the default tmpdir being mounted using 'noexec'. See http://pup.pt/task-failure for details and workarounds.
Failed on 1 target: 192.168.122.20

**Comment by lucywyman** [comment]
It looks like your target `192.168.122.20` doesn't have the configured Ruby interpreter `/opt/puppetlabs/puppet/bin/ruby`. If you want to install that interpreter on the system you can run:
```
bolt task run puppet_agent::install --targets bdd
```

Or configure a different Ruby interpreter.

**Comment by ingridm7** [comment]
muchas gracias, le cuento que probre el error, ahora me sale esto:

# bolt task run mysql::export --targets bdd database=empresa file=root@192.168.122.21:/root/copias password=12345678 user=jadmin
Started on 192.168.122.21...
Failed on 192.168.122.21:
  The task failed with exit code 1 and no stdout, but stderr contained:
  /tmp/396f9223-4b33-4b33-9424-4b6f2950c48d/export.rb:10:in `get': can't modify frozen String: "mysqldump" (FrozenError)
  	from /tmp/396f9223-4b33-4b33-9424-4b6f2950c48d/export.rb:26:in `<main>'
Failed on 1 target: 192.168.122.21

**Comment by lucywyman** [comment]
Hmm, me parece que es un error en el módulo [puppetlabs-mysql](https://github.com/puppetlabs/puppetlabs-mysql/blob/main/tasks/export.rb), pero no hay pull requests o issues para arreglalo. ¿Cuál es el resultado si ejecuta:
```
bolt command run "/opt/puppetlabs/puppet/bin/ruby --version" -t bdd
```

**Comment by ingridm7** [comment]
> Hmm, me parece que es un error en el módulo [puppetlabs-mysql](https://github.com/puppetlabs/puppetlabs-mysql/blob/main/tasks/export.rb), pero no hay pull requests o issues para arreglalo. ¿Cuál es el resultado si ejecuta:
> 
> ```
> bolt command run "/opt/puppetlabs/puppet/bin/ruby --version" -t bdd
> ```

root@srv-bolt:/home/admin/produccion/.modules# bolt command run "/opt/puppetlabs/puppet/bin/ruby --version" -t 192.168.122.21
Started on 192.168.122.21...
Finished on 192.168.122.21:
  ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
Successful on 1 target: 192.168.122.21
