### ISSUE TITLE
bolt fails to install the puppet-agent

### ISSUE THREAD

**Issue by gucki** [puppetlabs/bolt#3046]
## Describe the Bug
Bolt fails to install the puppet-agent when it tries to automatically install it. Looking at the filename it seems like it doesn't properly detect the system's os version (debian bullseye).

## Expected Behavior
It should install the correct puppet-agent package.

## Steps to Reproduce
bolt plan run profiles::lb01
Starting: plan profiles::lb01
Starting: install puppet and gather facts on lb01-1
Finished: plan profiles::lb01 in 7.06 sec
Failed on lb01-1:
  The task failed with exit code 1
  19:55:31 +0000 INFO: Version parameter not defined and no agent detected. Assuming latest.
  19:55:31 +0000 INFO: Downloading Puppet latest for Debian...
  19:55:31 +0000 INFO: Debian platform! Lets get you a DEB...
  19:55:31 +0000 INFO: Downloading http://apt.puppet.com/puppet-release-.deb
  19:55:31 +0000 INFO:   to file /tmp/install.sh.47257.64316/puppet-release-.deb
  19:55:31 +0000 INFO: Trying wget...
  19:55:31 +0000 INFO: Retrying... [1/5]
  19:55:31 +0000 INFO: Return code: 8
  19:55:32 +0000 INFO: Retrying... [2/5]
  19:55:32 +0000 INFO: Return code: 8
  19:55:33 +0000 INFO: Retrying... [3/5]
  19:55:34 +0000 INFO: Return code: 8
  19:55:35 +0000 INFO: Retrying... [4/5]
  19:55:35 +0000 INFO: Return code: 8
  19:55:36 +0000 INFO: Retrying... [5/5]
  19:55:36 +0000 INFO: Return code: 8
  19:55:37 +0000 CRIT: ERROR 404
  19:55:37 +0000 CRIT: Unable to retrieve a valid package!

## Environment
bolt --version
3.17.0

root@lb01-1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by MikaelSmith** [comment]
Bolt uses https://github.com/puppetlabs/puppetlabs-puppet_agent to install the agent. Seems like something's going wrong with https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/main/tasks/install_shell.sh#L627.

**Comment by gucki** [comment]
@MikaelSmith Yeah, I'll see if I find some time to investigate further.

The image I used is https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-nocloud-amd64.raw, in case you want to reproduce the issue.
