### ISSUE TITLE
Provide get_groups function in apply block

### ISSUE THREAD

**Issue by gucki** [puppetlabs/bolt#3047]
It seems there's no way to find out the parent groups of the current target (as defined in the inventory.yaml). That'd be really helpful information, for example how to lookup data in Hiera:

    version: 5

    hierarchy:
      - name: "Per-node data"
        path: "nodes/%{trusted.certname}.yaml"

      - name: "Per-groups data"
        mapped_paths: [groups, tmp, "groups/%{tmp}.yaml"]

      - name: "Per-OS defaults"
        path: "os/%{facts.os.family}.yaml"

      - name: "Common data"
        globs: ["common/**", "common.yaml"]

My current approach is to define them manually in my deploy plan, see https://github.com/puppetlabs/bolt/issues/1765#issuecomment-1015116707

Having a `$target.get_groups()` function available in the apply block would solve this issue.

**Comment by danielkza** [comment]
It would be even better to have all of a target's groups as a top level variable so it can be used in Hiera hierarchy as well.
