### ISSUE TITLE
structured data that is just an array is not accepted

### ISSUE THREAD

**Issue by rlpowell** [puppetlabs/bolt#3073]
## Describe the Bug
$result = run_task("test"...), where the task is a python file consisting of `json.dump(list(range(12,500)), sys.stdout)`, ends up with the `$result.first().values` containing "_output => "[12,13,..."".  That is: values points to the output as a string, it is not an array.

(If that's not clear enough I can show you a full minimal repro.)

## Expected Behavior
`values` should point to an array.

## Environment
```
root@server:/tmp/testproj# bolt --version
3.21.0
root@server:/tmp/testproj# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by nicklewis** [comment]
Tasks are only allowed to return JSON _objects_. Any other output (including a JSON array) is treated as a plain string, under the `_output` key.

The workaround is to wrap your array in an object by nesting it under some key:

```python
json.dump({'values': list(range(12, 500))}, sys.stdout)
```
