### ISSUE TITLE
When running with PCP transport, include associated orchestrator job ID in job results

### ISSUE THREAD

**Issue by ALawley** [puppetlabs/bolt#3130]
## Use Case
Currently cd4pe runs its jobs by hitting a containerized bolt and using bolt's pcp transport to run via the orchestrator. This indirection means that we can't associate the orchestrator job ids within PE with the cd4pe jobs that they were run as part of, making cd4pe jobs difficult to troubleshoot for support. Ideally we'd like to be able to retrieve these within cd4pe when we run via bolt, letting us log the associated orchestrator job IDs, as well as potentially include them as a field on the cd4pe job.

## Describe the Solution You Would Like
When bolt runs a job using pcp transport, return the associated job ID in bolt's results output.

## Describe Alternatives You've Considered
The ideal solution here is likely to simplify the architecture of cd4pe jobs and just run directly against the orchestrator rather than using bolt as a middleman. This is something we'll likely want to consider at some point when the team has bandwidth, but represents a much larger chunk of work, and for now we're just trying to make quick improvements to the product's supportability.

**Comment by adreyer** [comment]
Is adding an optional `_transport` key to results that contains information like this a reasonable solution?

**Comment by ALawley** [comment]
That should work
