### ISSUE TITLE
closed_stream exception when running task generating long logs

### ISSUE THREAD

**Issue by surajbora1** [puppetlabs/bolt#3186]
When I am trying to run task which is generating log with multiple lines, bolt is executing all the commands but final status is failed with below exception

{kind: puppetlabs.tasks/exception-error", "issue_code":"EXCEPTION","msg":"closed_stream", "details": "class":"IOError"}

## Expected Behaviour
Task should have been completed without exception

## Steps to Reproduce
1. run task which generate long logs during execution, bolt will fail with above exception

## Environment
 - Version 3.22.1
 - Platform : RHEL
 
Please suggest if there is any to avoid stream exception.

**Comment by donoghuc** [comment]
What do you mean by "long logs"? Is your task writing a ton of data to STDERR?

**Comment by surajbora1** [comment]
Yes. Task has multiple log output more than 500 independent lines

**Comment by surajbora1** [comment]
@donoghuc any configuration which can avoid IOError due to closed_stream?

**Comment by donoghuc** [comment]
What transport are you using and what operating systems are involved? I am unable to reproduce this issue.

**Comment by surajbora1** [comment]
I am using ssh on rhel 7.

**Comment by donoghuc** [comment]
That is comprable to what I was testing against. Can you share any details about the task itself? Maybe the language it is written in and some examples of data being streamed to stderr? I tried a ruby task that sent a ton of data to stderr and no matter how much data I tried adding the task always returned it.

**Comment by surajbora1** [comment]
Hi @donoghuc, 
In task I am running python script which is running procedure to install software and perform some configuration.
One more thing I just observed its getting failed only after 900sec. Is this something related to timeout? I am using ssh transport and did not set any timeout (disconnect-timeout).
Just wondering if this is timeout, then It should return timeout error.

**Comment by donoghuc** [comment]
Ah, there are no timeouts in bolt itself for action execution. Likely there is a configuration issue in your ssh setup (either on the bolt controller or the target).

**Comment by surajbora1** [comment]
Yes IOError is because sshd configuration, but it should have thrown error like ssh connection terminated or so. Thanks @donoghuc for providing inputs.
You can close this ticket.
