### ISSUE TITLE
Bolt "getting started repo" needs to be updated to bolt 3.0

### ISSUE THREAD

**Issue by nod0n** [puppetlabs/bolt#3203]
[Getting started with Bolt](https://www.puppet.com/docs/bolt/latest/getting_started_with_bolt.html) should be updated to be compatible to bolt 3.0.
See: https://puppetcommunity.slack.com/archives/C7GP57T50/p1682538663686969?thread_ts=1682538449.203429&cid=C7GP57T50

**Comment by davidsandilands** [comment]
At a glance @donoghuc I think this has been done

**Comment by donoghuc** [comment]
Yep, looks like this got addressed.
