### ISSUE TITLE
CLI run-as option doesn't seem to work

### ISSUE THREAD

**Issue by nwolfe** [puppetlabs/bolt#3215]
## Describe the Bug
It would seem from documentation that I could configure Bolt to run as `root` user via the CLI like `bolt plan run --run-as root ...` or in the inventory.yaml file transport options here https://www.puppet.com/docs/bolt/latest/bolt_transports_reference.html#run-as-5 yet the CLI one doesn't work; I have to put this in inventory file under `ssh: config: run-as: root`.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by donoghuc** [comment]
What actions are not using the run-as flag? When i test this with a minimal example (using run_command) the `run-as` cli option is respected:
```
(positive_ev) ➜  foo cat foo/plans/init.pp
plan foo(){
  return run_command(whoami, localhost)
}
```

**Comment by davidsandilands** [comment]
@nwolfe just to check in and see if this is still an issue for you or if we can close this issue?

**Comment by nwolfe** [comment]
We can probably close this.

I realized that despite this flag, the module itself needs to be written in such a way to actually honor it. It depends what you're executing whether this flag works or not.

This flag seems to work for Bolt-only commands like `bolt module install`, but may or may not work with other modules.
For instance, `peadm::install` nor `cd4peadm::install*` do not work with this flag.

Thankfully our automation can just as easily `cd` into the project directory before running Bolt, but otherwise this flag is only marginally useful given this behavior.
