### ISSUE TITLE
Puppet Lab is not running

### ISSUE THREAD

**Issue by haihahoang123** [puppetlabs/bolt#3225]
Hello Team, 
I've followed the links as below trying to install the Primary Server on Puppet lab (using Windows) but I could not do anything, the error message as screenshot below: 
https://training.puppet.com/learn/course/247/play/691/pe101-deploy-discover-lesson-1 
https://play.instruqt.com/puppet/invite/ctruqfn5pzxi

![image](https://github.com/puppetlabs/bolt/assets/140804698/67d14641-4193-4626-af81-c8b48e6e5786)

Please help! Thanks so much in advance.

**Comment by davidsandilands** [comment]
@haihahoang123 this looks like an issue with a training environment rather than bolt. I will assume on the age of this ticket this will no longer be relevant but do feel free to reopen if you do need help
