### ISSUE TITLE
Publish Gemfile.lock

### ISSUE THREAD

**Issue by rrotter** [puppetlabs/bolt#3327]
## Use Case
I'd like to be able to install Bolt from source and get the same gems that are in the binary packages. This would be nice for local installs, but would be especially useful for getting Bolt packaged in Homebrew and other package managers.

## Describe the Solution You Would Like
Remove Gemfile.lock from .gitignore. Update/commit Gemfile.lock before tagging a new release.

## Describe Alternatives You've Considered
#3282

**Comment by donoghuc** [comment]
We dont use bundler to package bolt so there is no Gemfile.lock to publish. Packaging (including not only gems, but the entire ruby runtime) is defined in public vanagon repos https://github.com/puppetlabs/puppet-runtime https://github.com/puppetlabs/bolt-vanagon . Also we have a cask for bolt https://github.com/puppetlabs/homebrew-puppet

**Comment by rrotter** [comment]
Thanks, I'll take a look a vanagon.

Really not interested in the cask. Need native arm support, and in any case IMO a brew formula would be superior to a binary-only package even once arm support is available.
