### ISSUE TITLE
Enhancement: Authentication Should Support ssh config file

### ISSUE THREAD

**Issue by darkn3rd** [puppetlabs/bolt#416]
For ssh support, I wish I could use ssh-configuration file.  Vagrant is one use case I would use this:

```bash
vagrant ssh-config > ssh-config
bolt command run $command -F ssh-config web-01.dev
``` 

`Net::SSH::Config` support this with load method:

* https://net-ssh.github.io/net-ssh/classes/Net/SSH/Config.html

**Comment by nicklewis** [comment]
This should be working already. If not, there might be a bug. What are you trying to use in the ssh config and what isn't working?

**Comment by darkn3rd** [comment]
I don't see an option for this:

**Comment by nicklewis** [comment]
Ah yes, it's done automatically and only uses the default ssh-config file. We certainly could add the option to specify a different ssh-config.

**Comment by nicklewis** [comment]
If you have SSH > 7.3, you can use the `Include` directive in ssh-config. So you could add something like `Include config.d/*` and write your environment-specific files to `~/.ssh/config.d/<filename>`. That's a workaround, but it seems like it might work, if the version of SSH supports it.

**Comment by darkn3rd** [comment]
```bash
$ lsb_release -cs
xenial
$ ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
```

:'(
