### ISSUE TITLE
Enhancement: Run Context to support Executable Inventory

### ISSUE THREAD

**Issue by darkn3rd** [puppetlabs/bolt#417]
I would like to use a dynamic inventory that I can generated based on the state of my current instances, whether vagrant, google cloud, azure, or aws.  In these scenario, I would want to auto-generate a configuration and use it.  

This can be supported by doing stat on file, find if it is executable, and execute it.  If it is not, then it assumes normal format.

```bash
bolt command run $commmand --inventoryfile ec2.rb  --nodes stage-web-01
```

**Comment by adreyer** [comment]
It seems like automatically executing files has caused some issues with external facts. Those may not apply here though. Explicitly using --inventory_cmd may be preferable

How large is the inventory you intend to generate? Right now you can pass it in as an environment variable too.

BOLT_INVENTORY=`./ec2.rb` bolt command run <command> --nodes stage-web-01

**Comment by adreyer** [comment]
That already works. I was suggesting it as a workaround you should be able to use now.

You can put deploy keys and ip addresses into the inventory. https://puppet.com/docs/bolt/0.x/inventory_file.html#override-a-user-for-a-specific-node

**Comment by darkn3rd** [comment]
For reference, does that documentation have all the possible options?  I was trying to elicit for example all the options in ssh transport, hoping this would be another way to configure all the options in ssh (Identityfile , Hostname, Port, etc).  Currently, node name is the Hostname entry, no way to separate them.

**Comment by darkn3rd** [comment]
Out of gate then bolt is feature parity deficient (them's marketing words) to Ansible and even Chef's Knife tool.  If that's alright, cool. I can maybe use templates on-top of the inventory, build meta tool wrappers.

**Comment by nicklewis** [comment]
Better inventory / integrations are definitely on our radar, but need to learn a little more about what's needed. Do you expect like an AWS plugin, azure plugin, etc, or do you want to bring your own that can get data from your particular set of sources?

**Comment by darkn3rd** [comment]
I think a plug-in looks complex, just programmatic flexibility not to lock a hostname as way to configure these systems.  I typically have a wrapper script that extracts a name used for configuration, and corresponding configuration IP (plus private ssh key) that is used for configuration the system.  After installing initial system, such as a puppet agent, I then hand off to puppet, where I would inject state (such as list of internal IPs) into Puppet to configure systems, such as an cluster.

Some examples (staging type of environment):

* Knife Boostrap Wrapper Script - https://gitlab.com/darknerd/simple-elasticsearch/blob/master/config/bootstrap.sh
* Bolt boostrap wrapper script - https://gitlab.com/darknerd/simple-elasticsearch/blob/sre-google-experiments/config/boltcutter.sh

In these scenarios (3 so far): 
* **vagrant** machine name is identifier for configuration, the ip is always `127.0.0.1` and the port varies, hostname will be configured the same as well (unless overridden) 
* **google cloud**   
    * name = `web-01`
    * hostname = `web-01.c.dk-gcp-elasticsearch.internal` 
    * public = `35.196.211.209`
* **amazon web services**
    * Tag of `Name` = `web-01`
    * hostname  = `ip-172-31-7-91.us-east-2.compute.internal`
    * public = `ec2-52-14-162-150.us-east-2.compute.amazonaws.com`

I can extract the information from each cloud provider in various ways, but bolt's design to lock hostname as identity for configuration makes it challenging to support it for modern Cloud Age computing.  No one relies on hostname given that they change, and instead use something else.

**Comment by adreyer** [comment]
https://tickets.puppetlabs.com/browse/BOLT-510
