### ISSUE TITLE
Bolt SSH Key Verification Failure

### ISSUE THREAD

**Issue by darkn3rd** [puppetlabs/bolt#418]
I am unable to use `bolt command run` with ssh-configuration (`~/.ssh/config`) that uses `Hostname`, `User`, `Port`, `IdentityFile`, etc.  Alternatively `ssh $machine $command` works fine.

I deleted my `~/.ssh/known_hosts` just in case this was a part of the problem.

### STEPS TO REPRODUCE:

I ran this:

```bash
vagrant up
vagrant ssh-config >> ~/.ssh/config
ssh tools.dev hostname ### <========================== SUCCESS
bolt command run 'hostname' --nodes tools.dev  ### <== FAILS
```

My Vagrantfile:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# default constants
TIME = Time.now.strftime('%Y%m%dT%H%M%S')
VAGRANT_BOX = 'bento/ubuntu-14.04'
CONFIGFILE_HOSTS='./config/hosts'

# build hosts hash
hosts = {}
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
  ipaddr, hostname = line.split(/\s+/)             # only grab first two columns
  hosts[hostname] = ipaddr                         # store in hash
  PRIMARY_SYSTEM = hostname if (line =~ /primary/) # match primary
end

Vagrant.configure('2') do |config|
  hosts.each do |hostname, ipaddr|
    default = if hostname == PRIMARY_SYSTEM then true else false end
    config.vm.define hostname, primary: default do |node|
      node.vm.box = VAGRANT_BOX
      node.vm.hostname = hostname
      node.vm.network 'private_network', ip: ipaddr
      node.vm.provider('virtualbox') do |vbox|
        vbox.name = "#{hostname}_#{TIME}"
        vbox.memory = 1024 if hostname =~ /es-[0-9]{2}/
        vbox.cpus = 2 if hostname =~ /es-[0-9]{2}/
      end
    end
  end
end
```
And sourced configuration in `config/hosts`:
```
172.16.0.30	tools.dev	primary
172.16.0.31	es-01.dev
172.16.0.32	es-02.dev
172.16.0.33	es-03.dev
```

###  EXPECTED RESULTS

As it works with ssh, expected no problem with bolt.

### ACTUAL RESULTS

Using the `--debug` option:

```
2018-04-26T16:27:46.565471 DEBUG  Bolt::Inventory: Did not find config for tools.dev in inventory
2018-04-26T16:27:46.566197 DEBUG  Bolt::Executor: Started with 100 max thread(s)
2018-04-26T16:27:46.566307 INFO   Bolt::Executor: Starting: command 'hostname' on ["tools.dev"]
2018-04-26T16:27:46.623426 DEBUG  Bolt::Transport::SSH: Authentication method 'gssapi-with-mic' is not available
2018-04-26T16:27:46.623810 INFO   Bolt::Executor: Running command 'hostname' on ["tools.dev"]
2018-04-26T16:27:46.623969 DEBUG  Bolt::Transport::SSH: Running command 'hostname' on tools.dev
Started on tools.dev...
2018-04-26T16:27:46.649479 INFO   Bolt::Executor: {"node":"tools.dev","status":"failure","result":{"_error":{"kind":"puppetlabs.tasks/connect-error","msg":"Host key verification failed for tools.dev: fingerprint 77:87:4f:9c:cc:ec:e6:99:26:3e:f2:2f:5b:87:98:ac is unknown for \"[127.0.0.1]:2222\"","details":{},"issue_code":"HOST_KEY_ERROR"}}}
Failed on tools.dev:2018-04-26T16:27:46.649879 INFO   Bolt::Executor: Finished: command 'hostname' on 1 node with 1 failure

  Host key verification failed for tools.dev: fingerprint 77:87:4f:9c:cc:ec:e6:99:26:3e:f2:2f:5b:87:98:ac is unknown for "[127.0.0.1]:2222"
Failed on 1 node: tools.dev
Ran on 1 node in 0.08 seconds
```

The vagrant ssh-config will automatically generate a configuration like this:

```
Host tools.dev
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /path/to/vagrant-project/.vagrant/machines/tools.dev/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**Comment by adreyer** [comment]
Bolt has it's own options for host key checking since net::ssh does not support that from ssh config.

Set `--no-host-key-check` on the cli or `host-key-check: false` in config or inventory.

**Comment by adreyer** [comment]
Fair enough, It's a shortcoming of the underlying library we use but there is no reason we can't add it.

**Comment by darkn3rd** [comment]
That would be great to defer to ssh-config (or ~/.ssh/config) settings used by the underlying OpenSSH tool.  I hope we can have more exposure in the inventory settings, and separate out a inventory name vs. actual hostname or IP address.  This way I can meta generate per environment (local dev vagrant vs. google cloud vs. aws vs. ... ) on the fly, and not have to aggregate out explicit IP address or hostnames: when I have, prod-web-01 vs stage-web-01 vs. web-01.dev, but want to configure web-01 per environment.

**Comment by ahpook** [comment]
At SF puppetizelive - @torrancew mentioned that he's running into this problem when there's an EC-DSA key that overlaps with an existing (erroneous) RSA key - net::ssh prefers the RSA key (even when configured not to), which causes the known_hosts mismatch error. there is an upstream bug open on this - net-ssh/net-ssh#627 but it's not getting much traction. either helping them fix it upstream or working around it in bolt would help a lot!  🥇

**Comment by blackknight36** [comment]
Was this ever fixed in bolt?  I'm getting the same error when I try to run a task on some of our CentOS nodes.

```
ailed on mdct-00ut.dartcontainer.com:
  Host key verification failed for host.example.com: fingerprint 9c:e6:8c:c8:13:01:9a:42:c9:73:49:7f:48:bd:1e:7a is unknown for "host.example.com,192.168.0.5"
```

Adding --no-host-key-check to the bolt command works but should not be necessary.

**Comment by donoghuc** [comment]
@blackknight36 Are you asking if picking up `StrictHostKeyChecking` from OpenSSH config files is supported? This is not currently available in the underlying net-ssh gem (https://net-ssh.github.io/net-ssh/classes/Net/SSH/Config.html ). We are working on documenting what OpenSSH options are configurable outside of bolt config ( https://tickets.puppetlabs.com/browse/BOLT-1227 ).

**Comment by blackknight36** [comment]
@donoghuc I do not have StrictHostKeyChecking enabled in my .ssh/config and the default setting is set to "ask" which works fine with the regular ssh command.  Does net-ssh work with the /etc/ssh/known_hosts file?  All of our host keys are exported by puppet and collected into this file any time the host key on a node changes.

**Comment by donoghuc** [comment]
Yes, net-ssh will respect known_hosts. I am not 100% if that location (/etc/ssh) is a default (for me its ~/.ssh/known_hosts). You can configure it with:
```
Host *example.com
  UserKnownHostsFile=/etc/ssh/known_hosts
  IdentityFile ~/.ssh/private_key
  User foo
```

**Comment by blackknight36** [comment]
@donoghuc Thanks for the help.  I'm still not sure why bolt is giving an ssh key error when I connect to a host that is already in my known_hosts file and my ssh-agent is working correctly.  I'm not having any issues connecting to hosts through ssh outside of bolt either.
