### ISSUE TITLE
feature request: node lists seperated by spaces

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/bolt#495]
Bolt currently only accept comma separated node lists.

This is often a bit awkward if you work in unix envionments because things like this that are not possible:
```
bolt command run "df -h" -n ceph-cluster-{001..111} # using shell expansion
awk '/Host ceph-mon/{print $2}' ~/.ssh/config|xargs echo bolt command run "df -h" -n
```

Bolt should accept multipe arguments for "--nodes".
If a argument contains a comma, the argument is splitted in multiple host names.

**Comment by lucywyman** [comment]
You may already have this workaround in place, but in the meantime you can use
```
bolt command run "df -h" -n `echo ceph-cluster-{001..111} | tr '  ' ,`
```

**Comment by MikaelSmith** [comment]
This should work with `bolt command run "df -h" --nodes=ceph-cluster-{001..111}`.

**Comment by MikaelSmith** [comment]
We use something similar as an example in https://puppet.com/docs/bolt/0.x/bolt_options.html#concept-743.

**Comment by scoopex** [comment]
This is not the same, because it adds multiple --nodes arguments using shell expansion.
Using a single --nodes argument with number of hosts separated by spaces provides a additional (and for many users useful) possibility. 
``
$ echo bolt command run "la" --nodes={web{5,6,7},elasticsearch{1,2,3}.subdomain}.mydomain.edu  
bolt command run la --nodes=web5.mydomain.edu --nodes=web6.mydomain.edu --nodes=web7.mydomain.edu --nodes=elasticsearch1.subdomain.mydomain.edu --nodes=elasticsearch2.subdomain.mydomain.edu --nodes=elasticsearch3.subdomain.mydomain.edu
```

**Comment by MikaelSmith** [comment]
I'm resistant to supporting multiple arguments to `--nodes` because it makes CLI parsing more complicated and can make it harder to provide clear errors. I believe the use cases you're interested are all possible, just in slightly different forms than you expected.

**Comment by scoopex** [comment]
I think i understand your argument. But you should also consider that using node names separated by spaces gains a lot of convenience for at least unix users. 
Typical shell expansion / usage works without hacky conversion tricks (pipes, subshells, ...)

**Comment by exic** [comment]
Would it be an option to treat the "remaining arguments" as nodes? Like this, but without giving "Unknown argument(s)":

```
bolt command run "docker exec whatever status" -- $(custom_get_hosts --filter node-)
Unknown argument(s) node-01, node-02, node-03, node-04, node-05, node-06, node-07, node-08, node-09, node-10, node-11, node-12, node-13, node-14, node-15, node-16
```

**Comment by MikaelSmith** [comment]
That seems like a promising possibility.

**Comment by nicklewis** [comment]
Since this issue was first opened, Bolt now supports:
a) multiple `--target` options
b) space-separated target lists (only as a single CLI argument)
c) reading targets from STDIN
d) inventory globbing

That means there are a few new ways to accomplish this:
```
$ bolt inventory show -t\ foo-{1..10}
$ bolt inventory show -t `echo foo-{1..10}`
$ echo foo-{1..10} | bolt inventory show -t -
```

**Comment by nmaludy** [comment]
FYI i did some work on this just now, not from the CLI but from an inventory file perspective. In my work you can use ERB to generate some YAML, then the YAML will be parsed and the structured data returned from the plugin. This results in us being able to use ERB to generate a ranges of hosts:

Example inventory:
```yaml
version: 2
groups:
 - name: hosts_range
   targets:
     _plugin: task
     task: inventory_utils::erb_template
     parameters:
       parse: yaml
       template: |
         <% (0..10).each do |num| %>
         - web<%= '%02d' % num %>.domain.tld
         <% end %>
```

Example nodes generated and available in Bolt:
```shell
$ bolt inventory show --targets hosts_range
web00.domain.tld
web01.domain.tld
web02.domain.tld
web03.domain.tld
web04.domain.tld
web05.domain.tld
web06.domain.tld
web07.domain.tld
web08.domain.tld
web09.domain.tld
web10.domain.tld
11 targets
```



Reference: https://github.com/EncoreTechnologies/puppet-inventory_utils#inventory_utilserb_template---creating-hosts-ranges
