### ISSUE TITLE
list nodes and groups

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/bolt#537]
To allow convenient inspection of group/node definitions  bolt should support a "list" and "show" option for groups and nodes.

```
$ bolt group list
mygroup-01
mygroup-02
mygroup-03
$ bolt group show mygroup-02
foo-001,foo-002,foo-003
$ bolt group show mygroup-02 --with-spaces
foo-001 foo-002 foo-003
$ bolt group show mygroup-02 --with-newlines
foo-001
foo-002
foo-003

$ bolt group show all --with-newlines
foo-001
foo-002
foo-003
...
foo-400
```

This is a precondition to add host and group completion for shell completions like "./resources/bolt_bash_completion.sh"
See also: https://github.com/puppetlabs/bolt/issues/495

**Comment by adreyer** [comment]
To keep this aligng with the behavior of the task and plan show commands it should be:

```
$bolt group show
mygroup-01
mygroup-02
mygroup-03
```

```
$bolt group show mygroup-01
foo-001
foo-002
foo-003
```

**Comment by scoopex** [comment]
Sounds good :-)

**Comment by lucywyman** [comment]
We now have a command `bolt inventory show` (https://puppet.com/docs/bolt/latest/bolt_command_reference.html#inventory-show) which accepts a TargetSpec and lists nodes that match that spec. This includes listing groups in the inventory, so `bolt inventory show -n mygroupname` will list nodes in that group. Let me know if this issue needs to be reopened.

**Comment by scoopex** [comment]
Clone the recent repository: https://github.com/puppetlabs/bolt and executed bolt directly in the repository.

Played around with the first example of https://puppet.com/docs/bolt/latest/inventory_file.html#inventory-facts-vars-and-features

How can i gather the list of group-names? (this is essential for the bash completion)

Also other things are working not in a expected way:
```
# ok
$ bolt inventory show -n all
10.23.27.148
10.23.27.149
10.23.27.150
10.23.27.151
10.23.27.152
10.23.27.153
10.23.27.154
10.23.27.155

# wrong: result should be  192.168.100.179, 192.168.100.180, 192.168.100.181
$ bolt inventory show -n webservers
webservers
1 target

# wrong: result should be 192.168.100.179, 192.168.100.180, 192.168.100.181,192.168.101.50, 192.168.101.60
$ bolt inventory show -n ssh_nodes
ssh_nodes
1 target

# wrong: execution should be on 192.168.100.179, 192.168.100.180, 192.168.100.181,192.168.101.50
$ bolt command run "uptime" -n ssh_nodes
Started on ssh_nodes...
Failed on ssh_nodes:
  Failed to connect to ssh_nodes: getaddrinfo: Name or service not known
Failed on 1 node: ssh_nodes
an on 1 node in 0.1 sec
```

**Comment by lucywyman** [comment]
Can you post a (scrubbed) version of your inventory? Are you using inventory version 1 or 2?

**Comment by lucywyman** [comment]
It's working as expected for me locally with both inventory v1 and v2...

**Comment by scoopex** [comment]
I am sorry, i accidentally placed the example to ~/.bolt/inventory.yaml.
The correct location "~/.puppetlabs/bolt/inventory.yaml" contained a outdated file.

Probably it is a good idea to enhance the last line "x targets" with the origin of the targets.
(i.e. '12 targets, loaded from "~/.puppetlabs/bolt/inventory.yaml" ')

How can i query the list of group-names? (this is essential for shell completion)

**Comment by lucywyman** [comment]
There isn't currently, but I think we can have a way to expose that. 

## The Solution
This should be a new subcommand `bolt groups show`, which will need a new `elsif` in this block: https://github.com/puppetlabs/bolt/blob/master/lib/bolt/cli.rb#L291-L311. That should call a new function in `cli.rb` called `list_groups`, which should be defined right after the `def list_targets` definition and look like this:
```
def list_groups
  groups = 
```
We have a function that lists group names from the inventory (https://github.com/puppetlabs/bolt/blob/master/lib/bolt/inventory.rb#L107), and can add a command handler to `cli.rb` to print that (going through the outputter).

**Comment by genebean** [comment]
> Probably it is a good idea to enhance the last line "x targets" with the origin of the targets.
> (i.e. '12 targets, loaded from "~/.puppetlabs/bolt/inventory.yaml" ')

^^ would be a great addition too.
