### ISSUE TITLE
Puppet Integration

### ISSUE THREAD

**Issue by cjedwa** [puppetlabs/bolt#586]
This is more of a general question. It seems like there should be more integration to puppet in Bolt. 

It seems like it would be useful to use bolt to augment puppet modules. It would be great to see support for using the agent TLS authentication for running arbitrary tasks if you already have a traditional puppet architecture. It would also be good to see the integration of Bolt tasks as a Puppet function. I would see this as similar to custom functions or facts. 

Something like a ```<module name>/bolt/bolt_task``` that you could execute during your puppet run to exec on the client and return the output as a variable. 

I see the lack of this type of behavior in Puppet to be a big gap and something that pushes people to something like Ansible. 

Apologies for asking this here if it's not the right forum. I'm curious if these type of features are on a future roadmap.

**Comment by lucywyman** [comment]
Hi @cjedwa!

For using agent TLS authentication, you can configure bolt to use the puppet communication protocol by connecting it to the orchestrator, if you have PE managed nodes https://puppet.com/docs/bolt/0.x/bolt_configure_orchestrator.html. I don't think we have plans to add that kind of support to OS puppet installations.

We don't have support for running a task or plan from puppet, though I'm not sure how that's different from just running a script? 

We do, however, allow you to include puppet code in your plans: https://puppet.com/blog/introducing-masterless-puppet-bolt . Do you have a specific use case in mind?

**Comment by cjedwa** [comment]
Hi, thanks for the response. Honestly, I think I'm hoping for something that Bolt just isn't meant to be. 

I would like to be able to get information from clients during a traditional puppet run without using a fact. For example, if I had a json file of something deployed to the client from a package install I'm looking for the ability to read that in as a variable and use it in a later operation. Maybe merge something into it and write the file out.

**Comment by nicklewis** [comment]
@cjedwa You actually may want to look into the recently released `Deferred` functionality in Puppet, which lets you evaluate functions on the agent at catalog application time.

https://github.com/puppetlabs/puppet-specifications/blob/master/language/types_values_variables.md#deferrednew

**Comment by lucywyman** [comment]
@cjedwa  Unless there's other action you think we can take, I'm going to close this. Please let us know if you think it should remain open though!

**Comment by MikaelSmith** [comment]
It could be interesting as a feature request for Puppet: https://tickets.puppetlabs.com/projects/PUP
