### ISSUE TITLE
bolt gem doesn't ship facts module

### ISSUE THREAD

**Issue by catay** [puppetlabs/bolt#591]
When installing Bolt as a gem (gem install bolt) it doesn't contain the facts module.
The same version installed through rpm (puppet-bolt.x86_64 0:0.21.7-1.el7) does contain the module.

If this is intentionally it would be good to update the docs to make the end user aware this module can be found on the forge.  

The current documentation implies the facts module is shipped by default (Writing plans - collects facts from the targets) and this might cause some confusion when trying out the examples.

**Comment by MikaelSmith** [comment]
Yeah, we stopped shipping module content in gems at some point. I think we intend to stay that way, to leave the Bolt gem as a stripped down core. That does mean for `apply`, you'll need to install some module dependencies.

I think we can add something to the instructions around installing via gem to clarify this.

**Comment by katelopresti** [comment]
Looks like we added this to the Known Issues section of the release notes. I'll update relevant sections of the docs. 
https://puppet.com/docs/bolt/0.x/bolt_known_issues.html#task-module-removed-from-bolt-gem

Thanks!

**Comment by catay** [comment]
Ok thanks. Some instructions would be good. It took myself a few minutes to figure out where to find that facts plan. :)

**Comment by lucywyman** [comment]
@catay  We've added some documentation around this - I'm going to close the issue but let us know if there's anything else we can do to make this less frustrating!
