### ISSUE TITLE
Allow ~ in path to list of nodes

### ISSUE THREAD

**Issue by genebean** [puppetlabs/bolt#600]
Right now the allowance of `~` is not uniform within bolt's parameters. It can be used in the path to a script but cannot be used in the path to a list of nodes.

For example, this works fine:
```
╔ ☕️  gene:~
╚ᐅ bolt script run ~/Downloads/esxi-hyperthreading-mitigation.sh \
> -u root -p $esxipw --no-host-key-check -n some-node.example.com
```
But this fails:
```
╔ ☕️  gene:~
╚ᐅ file ~/Downloads/hosts.csv
/Users/gene/Downloads/ci-hosts.csv: ASCII text

╔ ☕️  gene:~
╚ᐅ bolt script run ~/Downloads/esxi-hyperthreading-mitigation.sh \
> -u root -p $esxipw --no-host-key-check -n @~/Downloads/hosts.csv
Error attempting to read ~/Downloads/hosts.csv: No such file or directory @ rb_sysopen - ~/Downloads/hosts.csv

╔ ☕️  gene:~   [exit code 1]
╚ᐅ
```

I can work around this by using `${HOME}` instead of `~` but would much prefer to be able to use the shorter version. An example of the workaround would be
```
╔ ☕️  gene:~
╚ᐅ bolt script run ~/Downloads/esxi-hyperthreading-mitigation.sh \
> -u root -p $esxipw --no-host-key-check -n @${HOME}/Downloads/hosts.csv
```

**Comment by MikaelSmith** [comment]
Ah, I guess we mess up shell expansion with the `@`.

**Comment by MikaelSmith** [comment]
Created [BOLT-813](https://tickets.puppetlabs.com/browse/BOLT-813)
