### ISSUE TITLE
Running 'bolt puppetfile install' should tell the user what is happening

### ISSUE THREAD

**Issue by trevor-vaughan** [puppetlabs/bolt#606]
As a user with a large Puppetfile, I need to know whether or not the command is hanging or I'm just being impatient.

Having the output simply clear the first output line and use a spinner or something would be great.

**Comment by lucywyman** [comment]
I think https://github.com/puppetlabs/bolt/blob/d5feadb234b07b9681493aba27d46dfbc92dad92/lib/bolt/cli.rb#L364 is a good place to start with this, at least to output something before starting to install modules to acknowledge the command is running. 

https://github.com/puppetlabs/r10k/blob/master/lib/r10k/action/puppetfile/install.rb#L11 and https://github.com/puppetlabs/r10k/blob/master/lib/r10k/puppetfile.rb#L154 would be good places to start if you wanted to log each module install, or what r10k is doing when installing

**Comment by siddharth1001** [comment]
Correct me if I am wrong but it doesn't look like this can have a progress-bar.
