### ISSUE TITLE
Garbled output when running task with --tty

### ISSUE THREAD

**Issue by lutter** [puppetlabs/bolt#627]
I have a task `atask` that looks like this and that I run against a CentOS 7 system

```
#! /bin/bash

cat <<EOF
{ "name": "cat",
EOF
sleep 1  # Do real, slow work here
cat <<EOF
  "legs": 4 }
EOF
```

When I run this task with `bolt task run atask` without passing `--tty`, everything is fine: the output returned is proper JSON. When I run the task with the `--tty` flag, a spurious `{"_task": "atask"}` is inserted into the output as if `sleep` had produced that output, making the result not legal JSON. This behavior seems timing dependent: removing the sleep, or reducing it, to `sleep 0.05` makes things work again, even with the `--tty` flag.

I've tried this with bolt version 0.22.0.

**Comment by MikaelSmith** [comment]
Yeah, this is a problem we haven't figured out how to fix generally. If we pass input, some platforms seem to echo it back. You can fix a particular task by adding metadata with `input_method: environment`. Related: [BOLT-691](https://tickets.puppetlabs.com/browse/BOLT-691)

**Comment by lucywyman** [comment]
@lutter  We plan to document that you should always specify the input method if you're only going to use one or the other. Other than that we plan to close this as a known issue and leave it at that? We don't have a good solution :(
