### ISSUE TITLE
feature request: ability to resolve IPs from PuppetDB

### ISSUE THREAD

**Issue by sergeyarl** [puppetlabs/bolt#628]
Hi! 

I'm sorry if this is already implemented, but unfortunately I was not able to find any references. I'm new to Bolt. 

Part of our infrastructure is hosted in AWS environment and is dynamic - new nodes are created and destroyed every now and then automatically. Some of them do not have DNS names set.

As I see Bolt is capable of performing queries against PuppetDB. And PuppetDB has different facts gathered from connected nodes, including nodes' IP addresses. 

It would be great if Bold could use these facts to connect  to nodes via ssh. 

For example now, if I execute 

`# bolt command run "hostname -f" --query 'inventory { certname ~ "certname_mask" }'`

I get 

Failed to connect to certname_mask_1: getaddrinfo: Name or service not known
Failed to connect to certname_mask_2: getaddrinfo: Name or service not known

Thanks! 

Regards,
Sergey

**Comment by MikaelSmith** [comment]
Ok, that definitely isn't something that works right now. `--query` assumes the certname is identical to a domain name it can connect to.

I think we could modify that to ask for domain name and/or ip address. I'm not sure we'd want to default to ip address, as that could behave strangely with SSH's known_hosts file.

**Comment by lucywyman** [comment]
Hello! We now have an AWS dynamic inventory plugin, which I think alleviates this specific problem for now. https://github.com/puppetlabs/bolt/blob/master/pre-docs/inventory_version2.md#aws-ec2 Let me know if this issue needs to be reopened!
