### ISSUE TITLE
Improve Readme documentation to include more examples about how to use Bolt with different PQL queries

### ISSUE THREAD

**Issue by jdub55** [puppetlabs/bolt#631]
In the past, MCO made it fairly easy to run arbitrary scripts against a specific set of machines based on the results of different fact values. However, since starting to use Bolt, I've been struggling to find good examples of how to do this. Can the Readme file be improved to include some more complex examples of using PQL queries with Bolt? For example:

bolt task run package action='status' name='openssl' -q 'inventory {facts.os.name = "windows" and facts.fqdn ~ "puppetdemos.net"}' --transport winrm -u 'administrator' -p ‘puppetlabs’

I would also suggest including a link with more information on how to leverage PQL queries in general, if such documentation already exists.

**Comment by lucywyman** [comment]
Hi @jdub55! We're restructuring our README to point to our official docs, but I've opened https://github.com/puppetlabs/bolt/pull/635 to address this issue. Also ping @katelopresti

**Comment by lucywyman** [comment]
Fixed!
