### ISSUE TITLE
Feature-request: Preview / read-only run mode for Tasks and Tasks Plans

### ISSUE THREAD

**Issue by jdub55** [puppetlabs/bolt#644]
As a user of bolt, I would really like the ability to be able to "preview" a run without actually executing the specified script. This process would validate that my node list is valid, all of the specified hostnames / IPs resolve as expected, connections ((PXP or ssh) to these nodes are successful, that script file(s) can be transferred successfully, etc. It would also output the specific hostname and IP resolved to help me troubleshoot issues with DNS / etc/hosts discrepancies.

The output would return information about each stage of the process (connections successful, script file(s) transferred, etc.) but instead of running the actual script, it just runs a dummy command (e.g. echo to STDOUT) in place of the actual script. There's been several occasions where I've wanted to test a very specific set of command parameters to bolt against specific servers and pre-validate everything before running but the actual script I'm trying to run is not idempotent, so I can only run it once. (I realize I could just create a dummy script to accomplish this same goal but I think having a flag where you can turn this on and off would be a nice feature) 

Additionally, having something similar for Task plans where it provides a "noop" / "readonly" ability would greatly improve the usability of Bolt for me. 

Thanks!

Joel

**Comment by adreyer** [comment]
For tasks that support "noop" you should already be able to do this.

**Comment by lucywyman** [comment]
Related: We have plans to add a 'noop' mode for plans. https://tickets.puppetlabs.com/browse/BOLT-273 @jdub55 unless there are other actions items, going to close this issue for now.
