### ISSUE TITLE
puppetfile install fails to remove last module

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/bolt#712]
If you remove all modules from Puppetfile and run `bolt puppetfile install` you are informed that the modules are being sync'd however no modules are purged from `~/.puppetlabs/bolt/modules/`

Steps to reproduce:

Set `~/.puppetlabs/bolt/Puppetfile` to:

```
mod 'puppetlabs-stdlib'
```

Run `bolt puppetfile install`

Observe the module is now installed by running `puppet module list --modulepath /home/ubuntu/.puppetlabs/bolt/modules`:

```
/home/ubuntu/.puppetlabs/bolt/modules
└── puppetlabs-stdlib (v5.1.0)
```

Remove the stdlib line from Puppetfile

Run `bolt puppetfile install`

Observe the module is still installed `puppet module list --modulepath /home/ubuntu/.puppetlabs/bolt/modules`:

```
/home/ubuntu/.puppetlabs/bolt/modules
└── puppetlabs-stdlib (v5.1.0)
```

*Expected behaviour*

When the Puppetfile lists no modules `bolt puppetfile install` should remove all modules. 

*Actual behaviour*

No modules are removed when the Puppetfile is empty.

**Comment by lucywyman** [comment]
I'm not 100% sure why this is happening, but we use r10k's puppetfile install action: https://github.com/puppetlabs/r10k/blob/master/lib/r10k/action/puppetfile/install.rb#L11 seems like a good place to start addressing this. Thanks for letting us know!

**Comment by nicklewis** [comment]
It looks like r10k decides it's not actually managing the moduledir if you don't have *any* modules specified in your Puppetfile, and skips doing any work (including purging existing modules). Since Bolt just uses r10k under the hood, this looks like an r10k issue (whether bug or intentional behavior I can't say...)

**Comment by adreyer** [comment]
However we fix this we need to be sure we don't remove modules when a user has never had a Puppetfile

**Comment by nicklewis** [comment]
I'm closing this as `bolt puppetfile install` has been replaced by the `bolt module` workflow, where this isn't a problem.
