### ISSUE TITLE
Sudo Credentials leaked if alerting TargetSpec object

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/bolt#728]
When alerting in plan if passing just the TargetSpec object it will leak credentials to the console.

```
plan pe::wait_for_service(
  Targetspec $nodes,
  Integer $port,
  Integer $timeout,
  )
{
  $nodes.each |$n| {
     alert("connection restored to ${n}")
  }
}

```

```connection restored to Target('puppet-compile-master-cloud-va2-2.pm.company.com', {"connect-timeout"=>10, "tty"=>false, "host-key-check"=>false, "run-as"=>"root", "sudo-password"=>"Woops"}) moving on```

**Comment by cyberious** [comment]
So I have done some more debugging of this and if we simply override the to_s method further to scrub any option that has password in it. 

```def to_s
      opts = @options.select {|k,v| k !~ /password/ }
      "Target('#{@uri}', #{opts})"
    end```

**Comment by lucywyman** [comment]
Opened #730

**Comment by MikaelSmith** [comment]
Should be resolved.
