### ISSUE TITLE
Enhancement: Provide Fedora Package

### ISSUE THREAD

**Issue by buckaroogeek** [puppetlabs/bolt#750]
It would be helpful to have a Fedora specific packages for Bolt. Fedora 29 is the current release. 

thanks

**Comment by buckaroogeek** [comment]
I would be glad to help with testing.

**Comment by MikaelSmith** [comment]
Filed https://tickets.puppetlabs.com/browse/BOLT-978. This seems pretty easy, I think we'll end up doing it.

**Comment by buckaroogeek** [comment]
Thank you very much. As an addendum, I would note that Fedora 29 is now the current release. I would expect the Fedora team to announce shortly that Fedora 27 will be at end of life and no longer supported.

**Comment by lucywyman** [comment]
The platform selection is mostly limited by the build tools we use. Once those have Fedora 29 support we can build thos packages! For now they do not though :(

**Comment by buckaroogeek** [comment]
Understood. I do appreciate any effort in this direction.
