### ISSUE TITLE
Support global configuration file

### ISSUE THREAD

**Issue by baurmatt** [puppetlabs/bolt#759]
We want to use `bolt` on our Jumphosts which we share within our team. For this, it is essential for us to use a shared configuration so everybody is using the same configuration (especially for Analytics).

In my opinion the configuration folder should be located at `/etc/puppetlabs/bolt/`

**Comment by MikaelSmith** [comment]
Ticketed as https://tickets.puppetlabs.com/browse/BOLT-821. We believe there should be a `bolt config print` command first to help with understanding config resolution.

**Comment by baurmatt** [comment]
Sure! :) Is there a planned timeline?

**Comment by MikaelSmith** [comment]
No timeline yet. We tend to only prioritize a week or two in advance, and this hasn't bubbled up on our team's priority compared to other work. However I'd be happy to support someone else taking it on.

**Comment by baurmatt** [comment]
Hey, is there any update on this? We're still really interested in this feature! :)

**Comment by baurmatt** [comment]
Current workaround:

site/bolt/lib/facter/users.rb:
```ruby
# frozen_string_literal: true

Facter.add('users') do
  setcode do
    Dir.chdir('/home/') do
      Dir.glob('*').select { |f| File.directory? f }
    end
  end
```

site/bolt/manifests/config.pp:
```puppet
# Class: bolt::config
class bolt::config (
) {
  $::users.each |$user| {
    file { "/home/${user}/.puppetlabs":
      ensure => directory,
      tag    => $user,
    }
    vcsrepo { "/home/${user}/.puppetlabs/bolt/":
      ensure   => latest,
      source   => 'https://git.example.com/bolt/control.git',
      user     => $user,
      owner    => $user,
      group    => $user,
      provider => 'git',
      revision => 'master',
      tag      => $user,
    }
    ~> exec { "bolt-puppetfile-install-${user}":
      command     => '/usr/local/bin/bolt puppetfile install',
      environment => [ "HOME=/home/${user}", ],
      user        => $user,
      group       => $user,
      refreshonly => true,
      tag         => $user,
    }
  }

```

**Comment by lucywyman** [comment]
This was resolved by #1557

**Comment by baurmatt** [comment]
Hey @lucywyman, we‘ve just landed back home in Berlin after 3 days in Ghent and I found a Github notification mail in my inbox telling me you‘ve implemented this feature. In that moment the airline played a fanfare celebrating the landing :D Just matched perfectly! :)

Thank you for adding yet another awesome feature to Bolt! :)

**Comment by lucywyman** [comment]
Hahaha that's awesome!! I think our global config is in a slightly different place than the one specified here, but let us know if you have any other issues or feature requests. And welcome home!
