### ISSUE TITLE
Support SSH config or bastion host

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/bolt#776]
As am AWS user, I would like to be able to use bolt to connect to hosts through a bastion host or proxy. 

I am fond of how Terraform handles it, via its [connection block](https://www.terraform.io/docs/provisioners/connection.html#connecting-through-a-bastion-host-with-ssh), where it transparently connects to hosts using a bastion.

A less smooth alternative is to let users provide an external ssh config file, so I can check it into my git repo and define hosts and set ProxyCommand that way.

This is how ansible chose to manage this:
* https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-ssh-args
* https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-configure-a-jump-host-to-access-servers-that-i-have-no-direct-access-to

Even though they suggest modifying `~/.ssh/config`, I would rather be able to check the configuration in.

**Comment by jeefberkey** [comment]
I now have `ProxyJump` set in my `~/.ssh.config`, which works without issue. It still requires ssh configuration outside of the Boltdir, which would prevent me from checking it in.

**Comment by adreyer** [comment]
https://tickets.puppetlabs.com/browse/BOLT-1039

**Comment by adreyer** [comment]
@jeefberkey BOLT-1039 was released in Bolt 1.7.0 yesterday allowing you to set "proxyjump" in `bolt.yaml` or `inventory.yaml` can you verify that it solves your problem?

**Comment by jeefberkey** [comment]
@adreyer Sorry it took so long to get back! This works great. Thanks for making this workflow possible so fast.
