### ISSUE TITLE
Allow SUDO password prompt

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/bolt#80]
In our echo system we require any sudo tasks to prompt password as a result we require that we need be able to have it request the password from the user in a secure manner similar to playbooks

**Comment by logicminds** [comment]
Yes please add support for sudo.  Also we are using a tool like sudo but called `dzdo` so please also allow for other commands besides just sudo.

**Comment by cyberious** [comment]
@logicminds I would add a ticket to allow for a sudo command option, but make sure you open a ticket otherwise might get lost

**Comment by Iristyle** [comment]
Thanks - we already have this ticket tracked in JIRA as https://tickets.puppetlabs.com/browse/BOLT-98

**Comment by ahpook** [comment]
Just for a housekeeping measure, I'm gonna close this issue and keep the conversation in the ticket @Iristyle referenced [https://tickets.puppetlabs.com/browse/BOLT-98](BOLT-98)
