### ISSUE TITLE
Support ssh connection to windows targets

### ISSUE THREAD

**Issue by ndelo** [puppetlabs/bolt#813]
Problem
Bolt transport make assumptions about what shell and commands are available on the the target based on the transport that is being used. 

Solution:
Command building logic should be split out of command execution logic in the transports. Each transport should probe what the login shell is on the other side of the connection and cache that information with the "connection" for the duration of a bolt execution. It should then build shell specific commands to run over the transports execute functionality.

We only need to support sh/bash for linux and we should assume the same LCD versions of unix commands are available. The code should be written in such a way that we can add csh support without a further refactor however.
We do not need to implement shell discovery functionality in the winrm transport but should for local, ssh, and docker.

Questions:
* How will transport provided features work? We should lazily evaluate provided features by connecting to the target when a user requests features or runs a task for the first time.
* If we know the login shell should we use the login shell when running commands with sudo? Yes, we should make this the default v2.0 behavior. 
* How do we detect powershell?

**Comment by lucywyman** [comment]
Hi @ndelo! We do indeed assume that users using the ssh transport are connecting to unix hosts - https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/ssh/connection.rb#L309 is the specific lines that will need to change. I'm not sure what the best approach to this will be though - maybe adding a check for the host os? Or having some kind of 'tag' on the hosts that are windows, and using that instead of the transport to determine commands like mkdir? Most of the team is off this week and early next week, so you might hear more next Wednesday or so!

**Comment by MikaelSmith** [comment]
We'd like to separate the context of transport from the shell you're operating in on the target, but that'll be a bit of an undertaking. We've started it for powershell. I imagine it would look like

Transports: ssh, winrm, local
Shell: powershell, (linux) shell

ssh would default to shell, but could have a config to override that and use powershell on the target.
winrm would default to powershell and could be overridden to shell.

**Comment by ndelo** [comment]
That would work for our use cases. I think Win OpenSSH defaults to CMD, but we’re testing with changing the default shell to PS.

In your thinking, would ‘shell’ be an available CLI option when executing bolt?

Sent from my iPhone

On Jan 2, 2019, at 3:57 PM, Michael Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


We'd like to separate the context of transport from the shell you're operating in on the target, but that'll be a bit of an undertaking. We've started it for powershell. I imagine it would look like

Transports: ssh, winrm, local
Shell: powershell, (linux) shell

ssh would default to shell, but could have a config to override that and use powershell on the target.
winrm would default to powershell and could be overridden to shell.

**Comment by MikaelSmith** [comment]
It would definitely be a configuration option in inventory. We add it elsewhere (bolt.yaml and CLI) when it seems useful.

**Comment by pigam** [comment]
`bolt file upload` also fails for windows hosts over ssh, with `Could not make tempdir`. I think it's the same cause, am I right ?

**Comment by nmaludy** [comment]
+1

**Comment by lucywyman** [comment]
Relates to #1492
