### ISSUE TITLE
Error when launch bolt on localhost (transport local)

### ISSUE THREAD

**Issue by langoureaux-s** [puppetlabs/bolt#818]
Hi,

I use bolt 1.7.0.
Wen I try to lauch task on localhost for test purpose, I get 

```bash
bolt --modulepath /etc/puppetlabs/code/modules task run hm_ambari::ambari_setup java_home=/usr/lib/jvm/java db_type=postgres db_host=db db_name=ambari db_user=ambari db_password=ambari --nodes localhost
Started on localhost...
Failed on localhost:
  Could not make tempdir: No such file or directory - /tmp/d20190104-258-yiqocu/ambari_setup.rb
Failed on 1 node: localhost
Ran on 1 node in 0.09 seconds
```

It seems like it doesn't create folder `/tmp/d20190104-258-yiqocu`.

Any help please ?

**Comment by adreyer** [comment]
Are you running on linux or windows?

`/tmp/` is not the default tmp path when using the localhost transport is there perhaps a `tmpdir` set somewhere? Can you create a directory in `/tmp`?

Can you try with `--tmpdir <some directory that exists>`
Can you try with `--nodes local://localhost` to ensure it's using the local transport?

**Comment by langoureaux-s** [comment]
I run it on Linux (centos 7).

It's the same problem
```bash
bolt --modulepath /etc/puppetlabs/code/modules task run hm_ambari::ambari_setup java_home=/usr/lib/jvm/java db_type=postgres db_host=db db_name=ambari db_user=ambari db_password=ambari --nodes local://localhost --tmpdir /tmp 
Started on localhost...
Failed on localhost:
  Could not make tempdir: No such file or directory - /tmp/d20190107-361-zrtddq/ambari_setup.rb
Failed on 1 node: local://localhost
```

The path `/tmp` already exist on my workstation. It's like bolt not create the random directory  `d20190107-361-zrtddq` in /tmp

**Comment by lucywyman** [comment]
Hi @langoureaux-s! I'm honestly really unsure of what's causing the problem, and can't seem to replicate it on my own centos 7 machine. https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/local.rb#L39 is the specific line that's raising the error, and https://ruby-doc.org/stdlib-2.0.0/libdoc/tmpdir/rdoc/Dir.html#method-c-mktmpdir is what's failing. Maybe check that you have permissions to `/tmp`? My only other suggestion for now is to upgrade to our latest version (1.8.1) and try again.

**Comment by langoureaux-s** [comment]
Hi, 
thanks, your are right, after install puppet-agent, all work as expected ;).
It's juste packaging issue with bad messages.
