### ISSUE TITLE
Relative paths in upload_file

### ISSUE THREAD

**Issue by jeefberkey** [puppetlabs/bolt#837]
I have a project where I would like to copy in a directory from the project onto a node. I want others to be able to use my bolt plans as well, and would like to use  a relative path as the first argument in the `upload_file` function. 

```puppet
upload_file(
  './scripts',
  '/usr/local/scripts/',
  $nodes,
  'Copying in the scripts',
)
```

## Solution
We should at least add a `file::join` plan function which joins paths using `/`, which accepts repeated params and returns a string. Users can use this with their own `pwd` function to compute relative paths.

**Comment by MikaelSmith** [comment]
One way to do this is by putting `scripts` in the `files/` directory next to your `plans/` directory. Then you refer to them as `<modulename>/scripts`. See https://puppet.com/docs/bolt/1.x/plan_functions.html#upload-file for documentation on upload_file.

I'm not sure that covers your use case though.
