### ISSUE TITLE
Howto -Array parameter on plan

### ISSUE THREAD

**Issue by langoureaux-s** [puppetlabs/bolt#839]
Hi,

I try to create plan that require on Array of string as parameter.
In my plan definition, I put `Array[String] $mpacks_url`, and when I run the plan I set paremeter like this `mpacks_url=['http://public-repo-1.hortonworks.com/HDP-SOLR/hdp-solr-ambari-mp/solr-service-mpack-3.0.0.tar.gz']`

Bolt say `parameter 'mpacks_url' expects an Array value, got String`

Any help please ?

**Comment by MikaelSmith** [comment]
I believe the shell messes with that a bit. The CLI will coerce scalars to their type if possible (like `5.0` could be used as a String or a Number). For arrays and hashes we expect JSON:
```
mpacks_url='["http://public-repo-1.hortonworks.com/HDP-SOLR/hdp-solr-ambari-mp/solr-service-mpack-3.0.0.tar.gz"]'
```
