### ISSUE TITLE
FEATURE: Add nodes file

### ISSUE THREAD

**Issue by leemachine** [puppetlabs/bolt#86]
Please add the ability to use a json or yaml file with a list of nodes to execute on.

For example:

bolt command run 'rpm -qa | grep openssl' --nodes nodes.yaml
```yaml
nodes:
  - node1
  - node2
  - node3
```
bolt would then iterate through the list of nodes

**Comment by joshcooper** [comment]
Hi @leemachine, we're tracking this in https://tickets.puppetlabs.com/browse/BOLT-29. There's also BOLT-167 to get node lists from pdb. Is there a particular reason for YAML or JSON vs a flat list, one node per line?

**Comment by leemachine** [comment]
@joshcooper Nope. Doesn't have to be structured data. A flat txt file works as well.

Being able to get a list of nodes via pdb would be great also but I manage a lot of nodes that are not CM'd via Puppet/PE and using Bolt may be able to bring them into the workflow vs using our custom scripts and/or Fabric/Ansible scripts. :)

**Comment by joshcooper** [comment]
Fixed in https://github.com/puppetlabs/bolt/commit/c27cde0cc5a6cbd3cb44edff5354e69b28de24c7
