### ISSUE TITLE
Bolt should support asynchronous communications plugins

### ISSUE THREAD

**Issue by trevor-vaughan** [puppetlabs/bolt#87]
To work at scale, Bolt needs to be able to process asynchronous commands.

As a test/example API, I would recommend setting up a `file` backend that uses an input and output FIFO pipe to get the kinks worked out of the send/receive system.

I feel that the following should be done:

1. Support independent backend configuration files in...say...`/etc/puppetlabs/bolt/backend/<backend_name>.yaml`
  * I chose YAML since I can add comments and it's built into native Ruby

2. There should be a consistent API for setting up any backend service.
  * Since the backend services are independent, only the basic capabilities should be made generic. Perhaps even just `Backend.new` and `Backend.run`

3. Lack of a response to the Bolt CLI should not be considered a failure, for large systems it is quite possible that the system will output logs and results to other systems altogether

**Comment by MikaelSmith** [comment]
One idea I've talked with a few people about is building on https://github.com/puppetlabs/pxp-agent/blob/master/exe/task_wrapper.cc (as a self-contained static binary) to run a task on a remote host and then hit an HTTP endpoint when the task finishes.

Currently it writes output to a file, which could be polled for completion and output.

**Comment by trevor-vaughan** [comment]
@MikaelSmith This got me thinking and it might be nice to be able to send along checksums of files that are to be executed so that the runner knows that it is executing the *right* thing.

Obviously not a requirement, but it might be a nice to have in the future.

**Comment by MikaelSmith** [comment]
Definitely, passing checksums is part of Orchestrator's task running. That happens at an earlier layer in pxp-agent than the code I linked to though.
