### ISSUE TITLE
Bolt should support a gem-based plugin architecture

### ISSUE THREAD

**Issue by trevor-vaughan** [puppetlabs/bolt#88]
I was speaking to a few colleagues at the conference and we realized that the best option for Bolt plugins may be to follow in Beaker's footsteps and have a gem-based plugin architecture.

This would keep Bolt itself to a minimum, easily tested, architecture and allow the addition of user plugins in the easiest manner possible.

In theory, adding a Bolt::Backend object that does the following, should suffice:

1. Discover the plugin configuration file
  * Each configuration file could, in theory, just default to `/etc/puppetlabs/bolt/backend/<backend_name>.yaml`
2. Read the configuration file and merge the hash with the global CLI options
  * debug
  * verbose
  * config file path
  * ???
3. Discover the available plugins installed on the system and allow them to be processed
4. Call Bolt::Backend::<Backend>::.new
5. Configure the object
6. Execute the backend

Asynchronous backends will probably need a send/receive mode that can be independently executed

**Comment by trevor-vaughan** [comment]
@ahpook What would I not want plugins to do?!

Basically, any time we want to add a new synchronous or asynchronous protocol to the stack, we should be able to do that without affecting Bolt-core unduly. This will allow users to add support for their internal protocols as necessary under a consistent Bolt API framework.

**Comment by ripienaar** [comment]
@ahpook transports

**Comment by ahpook** [comment]
@trevor-vaughan but you're saying plugins for transports, not things like output formats.

**Comment by joshcooper** [comment]
I was thinking node lists/inventory could be another useful extension point, e.g. query LDAP/AD, puppetdb, etc..

**Comment by trevor-vaughan** [comment]
@ahpook Well, I'd love plugins for both, but I'll settle for transports as a start.

The reason I'm saying both, is that when I'm managing 10k nodes, I probably don't want that to come back to my screen (or maybe I want a summary). But I *do* want all the data to go to ElasticSearch/Splunk/Whatever based on the output plugin that is selected and configured.

Also, there may be environments (HIPAA) where you may be able to send back a summary that things succeeded, but the output needs to be multiplexed based on the system where the task is running and cannot get transmitted back to the running system.

**Comment by adreyer** [comment]
https://tickets.puppetlabs.com/browse/BOLT-610
