### ISSUE TITLE
Cannot remove files when use wildcard

### ISSUE THREAD

**Issue by hardoverflow** [puppetlabs/bolt#903]
If i use a wildcard in my command, bolt don't delete any files. If i use the filename, file will be removed.

```bolt command run 'rm -f /path/to/dir/*' --nodes my.fqdn.tld --user '' --run-as root --sudo-password -v --debug```

bolt --version: 1.14.0

```
Finished on my.fqdn.tld:
{"node":"zmy.fqdn.tld","status":"success","result":{"stdout":"","stderr":"","exit_code":0}}
Finished: command 'rm -f /path/to/dir/*' with 0 failures in 1.0 sec
Successful on 1 node: my.fqdn.tld
Ran on 1 node in 1.01 seconds
```

**Comment by adreyer** [comment]
I can't replicate this issue with the ssh transport. What is users login shell? Does it work without sudo?

**Comment by MikaelSmith** [comment]
There's a good chance this is transport-dependent based on whether the command is run in a shell on the target.
