### ISSUE TITLE
Bolt should allow setting default connection type (ssh, winrm)

### ISSUE THREAD

**Issue by TJM** [puppetlabs/bolt#92]
Bolt should allow setting default connection type (ssh,  winrm, etc.), through a "config" file and/or command line option.  It should not be necessary to prefix all windows hosts with `winrm://` when you are only connecting to windows hosts. It should still allow a user to "override" the default connection type by specifying it on the node list.

**Comment by joshcooper** [comment]
Yep makes sense @TJM, I'm working on a patch for this in [BOLT-53](https://tickets.puppetlabs.com/browse/BOLT-53)

**Comment by joshcooper** [comment]
This was merged to master in https://github.com/puppetlabs/bolt/commit/a3de6e10221a5328c8d4f826f6795d96c491a23a and will be released in the 0.7.0 release later this week.
