### ISSUE TITLE
service restarts - puppet interface for bolt

### ISSUE THREAD

**Issue by jordiprats** [puppetlabs/bolt#928]
When trying to create a simple task like force a NTP update using ntpdate I need to:

- stop the ntp service
- execute the ntpdate
- start again the ntp service

I believe it makes no sense to reinvent the wheel on how to stop a service and how it's called the service in the distro it is running since puppet already have the code to stop a service and the puppet module also have what's the service name. 

Whould it be possible to create an interface between the task and the puppet module to perform such actions?

thanks,

**Comment by donoghuc** [comment]
Hi @jordiprats you can use the tasks that are bundled with bolt (for example in the [service](https://forge.puppet.com/puppetlabs/service) module) directly or use them as a starting point to build your own custom tasks. You can also try to write a plan to apply manifest code in an [apply](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html) block.

Please join the conversation on the #bolt channel in the puppet community slack instance. Another channel of interest is the #office-hours where once a week a Bolt developer leads a Q&A session about using Bolt

**Comment by jordiprats** [comment]
Definitely there might be workarounds to get things done but this is more conceptually:

Is it by design that bolt wants to unload all the complexities that puppet already solves (like stopping a service) to the bolt scripts?

I think that bolt should be providing an interface to puppet for modifying the state of the managed items instead of simply being a script executor on asteroids

kind regards,

**Comment by MikaelSmith** [comment]
There are several ways Bolt already supports sharing that interface:
- applying Puppet manifest code (which can use Puppet resources) in an [apply](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html) block within a plan
- writing tasks that directly [use library code](https://puppet.com/docs/bolt/latest/writing_tasks.html#concept-2127) that helps implement Puppet's resources

For example a plan that does what you mentioned might look like
```
apply($target) {
  service { 'ntp':
    ensure => stopped,
  }
}

run_command('ntpdate', $target)

apply($target) {
  service { 'ntp':
    ensure => running,
  }
}
```

The service and package tasks themselves show methods of [re-using Puppet's provider implementations](https://github.com/puppetlabs/puppetlabs-service/blob/master/tasks/init.rb#L60) for their Ruby implementations, but also include versions that don't require any additional packages on the target.

**Comment by adreyer** [comment]
Closing since this is solved by `apply`
