### ISSUE TITLE
hints to ignore text printed before command output

### ISSUE THREAD

**Issue by sambowry** [puppetlabs/bolt#940]
Linux hosts may print text before printing the output of a command. When bolt execute "['id', '-g', owner]", the command output is not the first output line, but the last:

C:\Program Files\Puppet Labs\Bolt\lib\ruby\gems\2.5.0\gems\bolt-1.15.0\lib\bolt\transport\ssh\connection.rb line 43

            # group = result.stdout.string.chomp
              group = result.stdout.string.chomp.lines.last

similarly SCP should drop bytes until the protocol is starting:

C:\Program Files\Puppet Labs\Bolt\lib\ruby\gems\2.5.0\gems\net-scp-1.2.1\lib\net\scp.rb line 395

      def await_response_state(channel)
        return if channel[:buffer].available == 0
        c = channel[:buffer].read_byte

        #### drop non scp bytes
        while c > 2 && channel[:buffer].available > 0
          c = channel[:buffer].read_byte
        end
        return if c > 2

        raise "#{c.chr}#{channel[:buffer].read}" if c != 0
        channel[:next], channel[:state] = nil, channel[:next]
        send("#{channel[:state]}_state", channel)
      end

**Comment by adreyer** [comment]
Do you know what ssh configuration is causing lines to always be printed and captured by bolt?

**Comment by sambowry** [comment]
Sorry, i was not able to reproduce the exact issue. I have no idea how can i force connection.rb chown() to run. The issue caused by unexpected text during execution of profile, bashrc or other shell init script. In my case an init script run:

$ id -gn
id: cannot find name for group ID 2000000
2000000

in bolt.debug.log

DEBUG  Executing: mkdir -m 700 /tmp/eb3c780c-f20b-47b7-a5cf-a952aa8da9ff
DEBUG  stdout: /usr/bin/id: cannot find name for group ID 2000000
DEBUG  Command returned successfully

Unexpected text is the reason why i recommend reading the last line of the id command output, and to skip "junk" during scp.

**Comment by lucywyman** [comment]
This may be an issue with `--tty`, which unifies stdout and stderr.

**Comment by nicklewis** [comment]
I missed the part where this command is being run by a login script of some kind. Unfortunately, we don't really have a way to cause those messages _not_ to be printed, and we also have no way of knowing which lines of output are desired and which are noise.

If you're not using `--tty` then at least some messages ought to go to stderr and be ignored. If your bashrc/profile/etc are printing to stdout when they're executed, that seems like a problem that needs to be fixed on the target machine.

We could _potentially_ solve this similarly to how we handle knowing when to provide stdin when running sudo, which is to first echo some uuid that we can detect as part of our state machine. But this seems like an uncommon case where something is misconfigured on the target, so I'm not sure it's something we want to work around in Bolt.
