### ISSUE TITLE
Update travis-ci config to test ruby versions beyond latest 2.0 and 2.4 

### ISSUE THREAD

**Issue by cyberious** [puppetlabs/bolt#98]
Update .travis.yaml to support the Ruby versions of supported PE i.e. 2.1.9 and above, currently tests will not pass on some of those versions.

**Comment by joshcooper** [comment]
@cyberious can you paste the errors you're seeing when running the tests?

**Comment by cyberious** [comment]
This was actually originally related to the git submodule problem, but would like to see tested on the supported PE Ruby versions not just 2.0 and 2.4.

**Comment by joshcooper** [comment]
puppet-agent 5.0 and up ships with ruby 2.4.1 (recently updated to 2.4.2), which is what we're testing in CI. I'd like to hold off testing more combinations unless there is a known interoperability problem with bolt and different ruby versions.

**Comment by cyberious** [comment]
So is it only going to be supported with Puppet 5.x, is that what PE 2017.3 is built on?

**Comment by cyberious** [comment]
NVM answered my own question with the [2017.3 Release Docs](https://puppet.com/docs/pe/2017.3/overview/component_versions_in_recent_pe_releases.html#component_versions_in_recent_puppet_enterprise_releases) I never heard the major version bump for this in the announcement.
